### ISSUE TITLE
Languages link is broken on docs page

### ISSUE THREAD

**Issue by danswick** [mapbox/mapbox-navigation-ios#1073]
The `languages.md` link on https://www.mapbox.com/mapbox-navigation-ios/navigation/0.13.0/ results in a 404 -- https://www.mapbox.com/mapbox-navigation-ios/navigation/0.13.0/languages.md. 

cc @clindahl821

**Comment by bsudekum** [comment]
For now while we fix this, you can use this link: https://github.com/mapbox/mapbox-navigation-ios/blob/master/languages.md

**Comment by 1ec5** [comment]
The jazzy documentation reuses this repository’s README.md as the cover page, since we don’t provide a custom cover page.

The language guide is at the root of this repository:

https://github.com/mapbox/mapbox-navigation-ios/blob/c1fbff57490e342619b4e80e65a7176cd843f7a7/languages.md#L1

The readme uses a relative link, which jazzy keeps intact:

https://github.com/mapbox/mapbox-navigation-ios/blob/c1fbff57490e342619b4e80e65a7176cd843f7a7/README.md#L197

The fix is to provide a [custom cover page](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/ios/docs/doc-README.md), as the iOS and macOS map SDKs do. This is also an opportunity for us to split the installation instructions into a separate guide, as in mapbox/mapbox-navigation-ios#499. Also, just as in mapbox/mapbox-gl-native#11044, we could use the cover page to outline the relationships between the SDK’s main classes.

/cc @ericrwolfe @captainbarbosa @colleenmcginnis

**Comment by 1ec5** [comment]
We might as well make the language document into a guide by moving it into docs/guides/. But we’ll need to fix mapbox/mapbox-navigation-ios#1014 at the same time.

**Comment by 1ec5** [comment]
This issue is being addressed in #1112 and #1113.
