### ISSUE TITLE
Task <1BCAAC25-CFB0-4FFC-B7C6-E8F55C7C9761>.<5> finished with error - code: -1002

### ISSUE THREAD

**Issue by bidadh** [mapbox/mapbox-navigation-ios#1137]
**Mapbox Navigation SDK version: 0.13.0**

Hi,

since yesterday I'm getting the following error in the navigation mapkit blocking the app to respond to the ui interactions!:

Task <1BCAAC25-CFB0-4FFC-B7C6-E8F55C7C9761>.<5> finished with error - code: -1002
Task <1BCAAC25-CFB0-4FFC-B7C6-E8F55C7C9761>.<5> finished with error - code: -999

it keeps logging theses lines and prevents any interaction to the app.

Any quick help is much appreciated

Thanks,
Arthur

**Comment by bidadh** [comment]
if I remove styles it works!

**Comment by frederoni** [comment]
Thanks for the report. This bug with infinite UIApplicationSignificantTimeChange notifications being fired was fixed in https://github.com/mapbox/mapbox-navigation-ios/pull/990. Please use two styles or pin to the master branch until we make a new release.

**Comment by bidadh** [comment]
@frederoni Thanks.
I've done a temporary fix for now. will wait until you merge.

Actually I was gonna chat with you guys. the API is very closed and that's basically all or none for the navigation. it's not easy to customise the navigation screen

**Comment by bidadh** [comment]
@frederoni There is also another bug with the sound notifications.
if you start from a location and arrive to a destination and then start from the destination to another destination then sound notifications will be played twice. 

Sorry for reporting it here it's easier

**Comment by frederoni** [comment]
WRT customization; there are improvements being discussed and implemented in:
https://github.com/mapbox/mapbox-navigation-ios/issues/830, https://github.com/mapbox/mapbox-navigation-ios/pull/1063, https://github.com/mapbox/mapbox-navigation-ios/pull/993. Please feel free to make suggestions in these issues or PRs.

> There is also another bug with the sound notifications.

I believe this bug was fixed in https://github.com/mapbox/mapbox-navigation-ios/pull/1121 but not yet released. Please open a separate issue if this still occurs.

**Comment by bidadh** [comment]
Thanks @frederoni
