### ISSUE TITLE
Cache voice instructions on disk 

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-navigation-ios#1219]
The goal here is to reduce the number of times we need to go out to the network to get voice instructions. Per discussion this morning, we have a few ideas of lightweight ways to store fetched voice instructions on disk. 

* Use NSURLCache
* Repurpose our [ImageCache](https://github.com/mapbox/mapbox-navigation-ios/blob/master/MapboxNavigation/ImageCache.swift) to handle other data formats.

Open to other ways to skin the cat here.

/cc @mapbox/navigation-ios

**Comment by akitchen** [comment]
I'm going down the path of extending the current image cache abstraction we have in order to handle this case as well. URLCache is a less viable option here as we don't have direct hooks into the networking stack that downloads the voice instruction, and there would be a bit more friction and/or boilerplate to implement.

**Comment by akitchen** [comment]
will be closed by #1226 which is waiting for a 👍

**Comment by akitchen** [comment]
#1226 was merged to master
