### ISSUE TITLE
MBCancelButton cornerRadius  

### ISSUE THREAD

**Issue by shatk0vskiy** [mapbox/mapbox-navigation-ios#1293]
Hey everyone,

I need your help. I just want to change corner radius of cancel button (MBCancelButton) in navigation and nothing works for me. Any suggestions? 

Thanks

**Comment by frederoni** [comment]
If you can use Swift in your codebase, I'd recommend subclassing the style that you want to use and override the `apply()` method to set the new corner radius there.

```swift
class CustomDayStyle: DayStyle {
    override func apply() {
        super.apply()
        CancelButton.appearance().cornerRadius = 20
    }
}
```

but since the default styles (day and night) doesn't set a corner radius, you can use the appearance proxy wherever you want for that particular property. Just call:

```objc
[[MBCancelButton appearance] setCornerRadius:20];
```

before you present the `NavigationViewController`.
