### ISSUE TITLE
NSRegularExpression issue

### ISSUE THREAD

**Issue by zijiazhai** [mapbox/mapbox-navigation-ios#1325]
Hi, guys
The app is using navigation v0.14.1 or v0.15
I have a HongKong user reporting this "The app will show the navigation screen briefly (half a second) then the app crashed every time", but I can not reproduce this bug.

I can see the crash in my crashlytics:

Fatal Exception: NSInvalidArgumentException
*** -[NSRegularExpression enumerateMatchesInString:options:range:usingBlock:]: nil argument

also this:
![snip20180423_26](https://user-images.githubusercontent.com/10751092/39141116-5e404694-46ec-11e8-9956-73a8b8fedd1e.png)

Do you guys have any clue what is going on here?

**Comment by 1ec5** [comment]
Unfortunately, that isn’t very much information to go off. This library doesn’t use NSRegularExpression, but [MapboxDirections.swift does](https://github.com/mapbox/MapboxDirections.swift/blob/42ec86382b180277394e3c1717c6c1992f86b84a/MapboxDirections/MBRouteStep.swift#L520) when cleaning up road names in the Directions API response. It would help a lot to know if a particular road is causing this crash. In OpenStreetMap, most Hong Kong street names are bilingual; perhaps some street name has characters that are causing the regular expression to crash for some reason.

The only other thing I can think of is that some of the road name abbreviation functionality may have indirectly used a regular expression. If that’s the case, try upgrading to v0.16.0 or newer, since  #1169 removed that functionality in favor of road names preabbreviated by the Directions API.

**Comment by zijiazhai** [comment]
@1ec5 Thanks, it solved the crash after i release the app with V0.16.2 SDK.
