### ISSUE TITLE
steps list appears to be pulsing

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-navigation-ios#1386]
This started after https://github.com/mapbox/mapbox-navigation-ios/pull/1382. I'm not doing anything to the device here.

![new3](https://user-images.githubusercontent.com/1058624/39646964-006e3356-4f92-11e8-8d20-42448a35ba87.gif)

/cc @frederoni @vincethecoder

**Comment by JThramer** [comment]
[It's Alive!](https://i.imgur.com/RBGyi2i.gif)

It's probably pulsing because we're [redrawing the visible table](https://github.com/mapbox/mapbox-navigation-ios/commit/b56a9848104778ee7081cb5142072aa2996481d5#diff-05dcf05089a2947433b80faae897f68dR96) at every progress update, and on a performance note that's probably not necessary (all of the upcoming maneuver data is static)... but yeah, there's definitely a weird half-pixel dithering thing going on or something.
