### ISSUE TITLE
show current street name below user puck

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-navigation-ios#142]
I think instead of querying the map tiles for the current street, we could:

* snapping is enabled
* if we're snapping the user to the route, we have a good idea where the user is not only on the route but in the world
* Grab the steps way name, put below the puck

/cc @frederoni @1ec5

**Comment by 1ec5** [comment]
One hiccup is that, if I'm not mistaken, the Directions API coalesces similar-looking names, such as "North 1st Street" and "South 1st Street", as well as temporary name changes (Project-OSRM/osrm-backend#2744).

**Comment by 1ec5** [comment]
If we do rely on querying features in the map, we can rely on the fact that a route with full resolution matches the vector tiles exactly (modulo any differences in precision), regardless of whether the developer has enabled snapping to the route.

We can query the map as soon as the user passes each maneuver point or intersection (to avoid the coalescing issue above). Roundabouts pose an interesting challenge, but maybe we can live with a missing or slightly inaccurate street name label within roundabouts for now.

**Comment by emiltin** [comment]
if using a custom osrm server, i guess there's no guarantee that tiles and route really match

**Comment by 1ec5** [comment]
That’s true. However, is there a use case where having the tiles and route line up (even with minor discrepancies) is unimportant for the user experience?

Along these lines, feature querying would break down if the developer uses a style that doesn’t show the road that the route traverses (such as Mapbox Satellite), but I’m inclined to think the developer should make sure to choose a style that does include roads (such as Mapbox Satellite Streets).

**Comment by frederoni** [comment]
I would also prefer to get the way name from the step.
I noticed a few caveats when working with `queryRenderedFeatures/visibleFeatures`.
A tile may not be loaded or fully rendered when we try to grab the features either due to slow connection or a significant location update. An animated user puck adds another layer of complexity when converting coordinate space.

The route controller approach seems rock solid as it doesn't rely on visual elements being aligned and in sync.

**Comment by 1ec5** [comment]
> A tile may not be loaded or fully rendered when we try to grab the features either due to slow connection or a significant location update.

I agree that this could be problematic. This would be a good argument for falling back to the way name in the route step.

> An animated user puck adds another layer of complexity when converting coordinate space.

The user puck isn’t animated; the camera is, using mbgl transforms. So the conversion reflects the instantaneous state of the camera.

Conceptually, it makes a lot of sense to get the way name from the route step; however, we need to have an answer for https://github.com/mapbox/mapbox-navigation-ios/issues/142#issuecomment-294176614. OSRM suppresses name changes that are unworthy of a voice notification but worthy of an UI update. It’s one thing to remain silent; it’s another to explicitly state misinformation.

Consider [heading along this street in Indianapolis](http://map.project-osrm.org/?z=16&center=39.772617%2C-86.159484&loc=39.771438%2C-86.168754&loc=39.771339%2C-86.156909&hl=en&alt=0): OSRM emits no name change instruction where W. New York St. becomes E. New York St., because no user action is required. However, if the user glances at the screen to verify the current street, they may be confused because the navigation SDK says they’re on the wrong side of town. This is especially important in cities that rely on a quadrant system to name streets, such as Washington, D.C.

I don’t think we can rely on the route step except as a fallback strategy until OSRM’s behavior changes, perhaps by introducing the concept of a silent name change.

**Comment by danpat** [comment]
One way to fix this could be https://github.com/Project-OSRM/osrm-backend/issues/3964 (not yet implemented).

**Comment by 1ec5** [comment]
We’re working through this problem in #155 using feature querying. The general outline looks like this:

* [x] Add an invisible layer to the style that includes the geometry and `name` of every road in Mapbox Streets source
* [ ] Convert the user’s location (snapped to the route line) to a point on screen
* [x] Query the invisible layer for features that intersect that location
* [ ] To disambiguate at intersections and under/overcrossings, try to match at least two coordinates to the route line

We think a similar approach could allow us to label cross streets using manually placed points in a dynamically generated shape source: query the map at each `intersection` in the route step. This would be an alternative to the “routing-centric labeling” mode proposed in mapbox/mapbox-gl-js#3992. I think it makes sense to explore labeling based on route data because we already know precisely which streets we want labeled.

> The route controller approach seems rock solid as it doesn't rely on visual elements being aligned and in sync.

As long as the user location remains in view, we don’t need to align visual elements: https://github.com/mapbox/mapbox-navigation-ios/pull/155#discussion_r112574484.
