### ISSUE TITLE
Alternates routes should be under main routes casing

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-navigation-ios#1434]
The darker blue casing for the main route should be above the line used for alternate routes.

![image](https://user-images.githubusercontent.com/1058624/40085631-040f807a-5850-11e8-8165-5764c5126a7e.png)

**Comment by 1ec5** [comment]
For what it’s worth, it’s not uncommon in map design for a single casing to surround a full set of related roadways instead of delineating each individual roadway. The casing above could be seen as a way to distinguish the full set of routes from the rest of the map, as opposed to distinguishing the selected route from the others routes. In other words, all the routes are contrasted as a whole against the base map, while the selected route is highlighted.

Putting casing between the selected route and the other routes will increase the visual noise of the map. I suppose it’s possible that there would also be increased legibility, but I’m on the fence about making that tradeoff.

/cc @aparlato @nickidlugash

**Comment by captainbarbosa** [comment]
This will be fixed in https://github.com/mapbox/mapbox-navigation-ios/pull/2377.

A preview:

<img width="328" alt="Screen Shot 2020-06-17 at 5 19 17 PM" src="https://user-images.githubusercontent.com/10850812/84963707-f6da5500-b0be-11ea-9060-4ae4c1747cc6.png">

**Comment by captainbarbosa** [comment]
Fixed in https://github.com/mapbox/mapbox-navigation-ios/pull/2377 ✅
