### ISSUE TITLE
Improve route overview button

### ISSUE THREAD

**Issue by brsbl-zz** [mapbox/mapbox-navigation-ios#1455]
We're implementing a route overview button and animation on Android [here](https://github.com/mapbox/mapbox-navigation-android/pull/967#issuecomment-391836478) that is integrated into the trip tray instead of as a button on the map. This saves some map space and feels more where a user would expect to preview the current route they're on. 

Here's how the animation will look on Android:
![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/8434572/40433589-5bc09d42-5e7a-11e8-8572-1fee89320762.gif)

And it will use these light/dark icons: [routepreview_icons.zip](https://github.com/mapbox/mapbox-navigation-android/files/2036876/routepreview_icons.zip)

Note, the arrival time should also be moved from its current position to the left near the route's distance remaining to better match Android and make room for this button.

Additionally, while we are making this UI/UX change, it's worth investigating this bug in the current route overview implementation where the full route is obscured in overview mode:
![asdf](https://user-images.githubusercontent.com/19296229/40515696-9bdfd97c-5f62-11e8-988a-a25fa7506270.gif)

**Comment by bsudekum** [comment]
The bug can occur when the route is short:

https://github.com/mapbox/mapbox-navigation-ios/blob/53d5802f19bd4c0e34f0e0b6a2927474f6a0d8e3/MapboxNavigation/NavigationMapView.swift#L1032-L1039

We're setting the camera, but breaking early if the distance is short.

**Comment by 1ec5** [comment]
> integrated into the trip tray instead of as a button on the map

In other words, is the idea that we’d repurpose the ✖️ button (which currently ends the trip) so that it would conditionally zoom out to the overview or end the trip? If so, that would quite counter to iOS human interface design principles. At the least, we’d need to change the design from a ✖️ to a textual button that says “End” or “Overview” depending. But there are still two usability issues with this design:

* Overview mode and turn-by-turn mode look more or less identical. It’s too easy for the user to accidentally end their trip – a destructive action – because they didn’t realize they were already in overview mode.
* If the user is in turn-by-turn mode and wants to end the trip, the affordance for doing so (tapping twice on the ✖️) is undiscoverable.

**Comment by Cjballard** [comment]
@1ec5 I think the screenshot @brsbl attached was before Android had implemented the button in the trip tray. Here it is with the route preview icon integrated into the trip tray:

![rp-android](https://user-images.githubusercontent.com/7535952/41317329-df56b64e-6e62-11e8-92f5-a7369ad1b71d.gif)


Thinking that could look something like this on iOS. The ETA jumps beside the mileage to free up space for the route preview icon, keeping the end-trip **X** in its place. (animation is choppy but just to get the idea across)

![rp-ios](https://user-images.githubusercontent.com/7535952/41317338-e50b1968-6e62-11e8-8600-86e0c15d146c.gif)
