### ISSUE TITLE
Better default font size for top banner

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-navigation-ios#1472]
![image](https://user-images.githubusercontent.com/1058624/41063997-1e735004-698f-11e8-82ea-c3a5cb9b0f56.png)

If a developer adds a `InstructionsBannerView` to their custom navigation UI, the text should have a better default size so they do not have to style this on their own.

/cc @mapbox/navigation-ios

**Comment by bsudekum** [comment]
@frederoni what do you think about this? Should we move more styling from `DayStyle` to the InstructionBannerView class. IE font size and font color.

**Comment by frederoni** [comment]
> Should we move more styling from DayStyle to the InstructionBannerView

I don't think we should move the styling of these attributes since it would break the day and night styling behavior. We could set a default font size, color, ... in each `PrimaryLabel`’s, `SecondaryLabel`’s initializer but since a developer is using a component from the UI part of this framework, it would be safe to assume that the styles are also included.

Just call `DayStyle().apply()` before presenting a custom nav/view controller.

**Comment by bsudekum** [comment]
Fixed in https://github.com/mapbox/mapbox-navigation-ios/commit/0a5e75ccab13f5e95e9ac25360bc458cba37c7a8
