### ISSUE TITLE
:tag => 'v0.2.0' is not compatible with MapboxDirections 0.9.0

### ISSUE THREAD

**Issue by mgurreta** [mapbox/mapbox-navigation-ios#148]
`RouteControllet.swift` line `166`

`let profileIdentifier = routeProgress.route.profileIdentifier` 
should be
`let profileIdentifier = routeProgress.route.routeOptions.profileIdentifier`

**Comment by 1ec5** [comment]
This is fallout from mapbox/MapboxDirections.swift#122. We merged the change suggested above in #139, but only after we tagged v0.2.0. Unfortunately, the v0.2.0 podspec was pinning to `~> 0.8` of MapboxDirections.swift instead of `~> 0.8.0`. So after we released MapboxDirections.swift v0.9, CocoaPods considered v0.9 to satisfy the `~> 0.8` requirement, breaking the MapboxNavigation pod.

I’ve opened #150 with a temporary fix that more specifically depends on MapboxDirections.swift v0.8.x. I’ll tag that change as MapboxNavigation v0.2.1 and publish it to CocoaPods trunk. However, you may want to pin to a more recent commit on master in the meantime. Once the dust settles on some refactoring we’ve been doing in MapboxNavigation, we’ll publish a v0.3.0 with the fix as well.

**Comment by mgurreta** [comment]
you are asesome @1ec5
