### ISSUE TITLE
Combine NavigationViewController and RouteMapViewController

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-navigation-ios#1502]
I can't think of any reasons why we have both [NavigationViewController.swift](https://github.com/mapbox/mapbox-navigation-ios/blob/master/MapboxNavigation/NavigationViewController.swift) and [RouteMapViewController.swift](https://github.com/mapbox/mapbox-navigation-ios/blob/master/MapboxNavigation/RouteMapViewController.swift). I think we should refactor the two files into a single view controller with a few goals in mind:

* This file should be used as a reference on how different pieces can be combined to create a custom navigation view.
* We should think more about making more functions public that are useful and require inside knowledge of the project to do correct. Example, [`recenterMap()`](https://github.com/mapbox/mapbox-navigation-ios/blob/a9d45a4b79eb5058bc8c55250ad1d319af04028f/MapboxNavigation/NavigationMapView.swift#L1057-L1060) function added recently.
* There is a lot going on between the two files. This will be a good opportunity to do some house cleaning.

/cc @mapbox/navigation-ios

**Comment by 1ec5** [comment]
For context, the difference between NavigationViewController and RouteMapViewController was originally that:

* NavigationViewController was responsible for pushing other view controllers that weren’t related to a map, such as the step table view controller or feedback view controller.
* In time, NavigationViewController would sit at the same level as a preview view controller (#808), which might also embed a route map view controller.

Things have certainly changed since the original design, especially now that much of the layout has moved into views.

**Comment by JThramer** [comment]
Resurrecting this as a 1.0 release blocker. /cc @1ec5

**Comment by 1ec5** [comment]
#2548 tracks making the code to populate the current road name label more reusable by moving it outside of RouteMapViewController.

**Comment by Udumft** [comment]
Resolved in mapbox/mapbox-navigation-ios/pull/2902
