### ISSUE TITLE
UI is partially styled when exiting tunnel at night

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-navigation-ios#1540]
![image](https://user-images.githubusercontent.com/1058624/42284990-0904b7f0-7f63-11e8-93a9-9131a385091f.png)

List of what was happening:

* Started in night mode, 5:30am in SF
* Entered a very short tunnel, UI began to flash between day/night style
* Exited small tunnel, UI was partially styled

Thoughts on where the bug could lie:

* We should double check if it's possible to enter day mode if entering a tunnel at night. We should not be doing this.
* We should write some code to toggle between the two styles and see if we can reproduce a partially styled UI.

Request where the issue occurred: https://api.mapbox.com/directions/v5/mapbox/driving-traffic/-122.408051%2C37.737974%3B-122.40266659832733%2C37.72714780042833.json?geometries=polyline&annotations=congestion&steps=true&overview=full&access_token=YOUR_ACCESS_TOKEN

/cc @mapbox/navigation-ios

**Comment by macdrevx** [comment]
We can reproduce something very similar (possibly the same) to this bug via the following:

1. open the route overview list
2. select one of the steps in the list
3. toggle the theme

expected:

the top bar updates to the new theme

actual:

the background color of the top bar gets stuck with the old theme until you open the route overview list again.

**Comment by akitchen** [comment]
Thanks @macdrevx for the helpful list of steps to reproduce. We'll address this in an upcoming release

**Comment by macdrevx** [comment]
I think these two lines are the culprits here:

https://github.com/mapbox/mapbox-navigation-ios/blob/c56e802836b388b13c5a7e956fd3f865a7be4206/MapboxNavigation/RouteMapViewController.swift#L228

https://github.com/mapbox/mapbox-navigation-ios/blob/c56e802836b388b13c5a7e956fd3f865a7be4206/MapboxNavigation/RouteMapViewController.swift#L943

The problem is that as soon as you set the background color property on an instance of a UIView, that property stops participating in UIAppearance.
