### ISSUE TITLE
Cannot assign value of type 'NSExpression' to type 'MGLStyleValue

### ISSUE THREAD

**Issue by grass008** [mapbox/mapbox-navigation-ios#1562]
I get this problem at that line
https://github.com/mapbox/mapbox-navigation-ios/blob/v0.18.1/MapboxNavigation/NavigationMapView.swift#L894

**Comment by bsudekum** [comment]
Can you verify that you are using a newer version of the Mapbox Maps SDK? Can you share your podfile, the version of xcode you are using and the version of the nav sdk you are using?

**Comment by grass008** [comment]
it is not the latest version of The MapBox Maps SDK.. I am using this manually

**Comment by 1ec5** [comment]
You’re getting a compiler error because you’re trying to use an MGLStyleValue whereas MGLStyleValue has been removed in favor of NSExpression. Navigation SDK v0.18.0 and above requires map SDK v4.0.0 and above. Please consider upgrading the map SDK to the latest version. [This migration guide](https://github.com/mapbox/mapbox-gl-native/wiki/Upgrading-from-Mapbox-Maps-SDK-for-iOS-v3.7.x-to-v4.0.x) may be of help.

**Comment by grass008** [comment]
@1ec5 thank you very much)) have a nice day
