### ISSUE TITLE
invalid route

### ISSUE THREAD

**Issue by zijiazhai** [mapbox/mapbox-navigation-ios#1579]
**version: 0.18.1**

![681532551564_ pic](https://user-images.githubusercontent.com/10751092/43226591-e13bdbf2-9021-11e8-97fb-67e0b8467566.jpg)

![671532551135_ pic](https://user-images.githubusercontent.com/10751092/43226480-9f4f94f4-9021-11e8-9464-f6b38254224f.jpg)

**Comment by JThramer** [comment]
@zijiazhai Thanks for submitting this issue!

Did you submit a feedback event in-app (third button down) when you encountered this issue, by chance?

Cheers,
-Jerrad

**Comment by zijiazhai** [comment]
ok, I just did. Also, I think this happen because of bad/weak GPS signal? It happens a lot when I test it inside of my office.

**Comment by JThramer** [comment]
@zijiazhai Thanks for that! Yeah in the future: If you encounter an issue during a navigation session, the in-app feedback mechanism is the best way for us to help, as it provides us with extra information that is very useful during debugging.

I can see where a weak signal _could_ cause issues, but that doesn't explain the "elbow" in your route. I'll bring this up to our team about this tomorrow and we'll go from there.

Best,
-Jerrad

**Comment by 1ec5** [comment]
Thanks for reporting this issue. It’s unrelated to GPS. The problem was incorrect data in OpenStreetMap introduced by a first-time mapper. [The node in question](https://pewu.github.io/osm-history/#/node/271175340) has since been corrected, as you can see from [this route](https://www.mapbox.com/get-directions/#16.12/41.89326/-87.62402?coordinates=-87.622839,41.891746;-87.624112,41.897275).
