### ISSUE TITLE
Z-index from multiple annotations change after you rotate the mapView.

### ISSUE THREAD

**Issue by joshpuente** [mapbox/mapbox-navigation-ios#1593]
SDK version:

Mapbox-iOS-SDK (4.2.0)
MapboxCoreNavigation (0.18.1):
MapboxDirections.swift (> 0.21.0)
MapboxMobileEvents (> 0.4)
Turf (> 0.1)
MapboxDirections.swift (0.21.0):
Polyline (> 4.2)
MapboxMobileEvents (0.4.3)
MapboxNavigation (0.18.1):
Mapbox-iOS-SDK (> 4.0)
MapboxCoreNavigation (= 0.18.1)
MapboxSpeech (> 0.0.1)
Solar (~> 2.1)
MapboxSpeech (0.0.1)
Installed with: CocoaPods
iOS: 11.1.2
iPad model: iPad mini MF069LL/A
Xcode version: 9.4.1

Steps to reproduce:

1. Add multiple annotations to the navigationMapView close enough in which some could overlap with another. (The order in which these annotations are added should determine which annotation is above another annotation).
2. Rotate the mapView.
3. Notice that the annotation's z-indexes change upon rotation.

Before rotating:
<img width="155" alt="screen shot 2018-08-08 at 3 16 13 pm" src="https://user-images.githubusercontent.com/15850673/43859234-101860d8-9b1e-11e8-876f-221381126ba4.png">

After rotating 180 degrees:
<img width="200" alt="screen shot 2018-08-08 at 3 16 30 pm" src="https://user-images.githubusercontent.com/15850673/43859243-1aab4da8-9b1e-11e8-8af0-b91ab2615ea1.png">

**Comment by 1ec5** [comment]
Annotations are sorted by vertical screen position of each annotation’s `coordinate`, so that marker-like images don’t overlap in confusing ways. (More on that at mapbox/mapbox-gl-js#7076.) This does mean that two annotations will swap z-orders when you rotate the map by 180°. If you’re using view-backed annotations via MGLAnnotationView, you can force one annotation to appear above another using `-[UIView bringSubviewToFront:]` and related methods, as described in https://github.com/mapbox/mapbox-gl-native/pull/5287#issue-73102981.

**Comment by macdrevx** [comment]
@joshpuente did this answer your question?

**Comment by joshpuente** [comment]
Thanks for this helpful info @1ec5. We are actually using annotations via MGLAnnotationImage. Good to know that if we use annotations via MGLAnnotationView instead, we can bring our preferred subviews to the front.
