### ISSUE TITLE
Make route snapping logic available for external developers?

### ISSUE THREAD

**Issue by leviathan** [mapbox/mapbox-navigation-ios#1627]
In my context we’re using the `MapboxCoreNavigation.RouteController` for turn-by-turn navigation directly. Our user interface is so customised, that we're unable to use the default mapbox navigation user-interface.

### Intention

I've seen that there is a lot of utility logic in the `CLLocation.swift`extensionn ([link](https://github.com/mapbox/mapbox-navigation-ios/blob/master/MapboxCoreNavigation/CLLocation.swift)) regarding snapping a potential user location marker to the actual route, which is performed during turn-ty-turn navigation.

### Problem
However, nearly all methods in this extension are not visible outside the mapbox package.

### Question

Could these methods be made `public`, so that the logic could be used by developers using the core navigation library?

**Mapbox Navigation SDK version:**

taken from our `Cartfile.resolved`
```
github "mapbox/MapboxDirections.swift" "v0.21.0"
github "mapbox/mapbox-navigation-ios" "v0.18.1"
```

**Comment by 1ec5** [comment]
Though that particular utility method isn’t exposed publicly, `RouteController.location` is already snapped to the route line using that method under the hood when the raw location reading meets certain reliability criteria.

**Comment by akitchen** [comment]
This has come up a few different ways recently. We should consider adding a delegate method to the appropriate protocol when the RouteController's [snappedLocation](https://github.com/mapbox/mapbox-navigation-ios/blob/45b74c0ab0c06091f3808f6fd0eae9af2800d68d/MapboxCoreNavigation/RouteController.swift#L151) is updated, in order to push that information out rather than requiring apps/integrations to pull it from the RouteController, especially as it's not guaranteed to be non-nil.

**Comment by 1ec5** [comment]
#2410 adds a CLLocationManager workalike that snaps locations independently of the turn-by-turn navigation infrastructure. This functionality is especially well-suited for a pre-navigation map view, but it could also be useful for a bespoke turn-by-turn navigation UI that uses none of the RouteController infrastructure.

I realize this isn’t quite what was requested originally. However, the logic mentioned in https://github.com/mapbox/mapbox-navigation-ios/issues/1627#issuecomment-429357510 is no longer particularly relevant. We’ve since replaced RouteController with an implementation that uses a cross-platform, closed-source MapboxNavigationNative dependency to snap locations based on map matching. The old logic remains in LegacyRouteController, but it isn’t nearly as well-tested or reliable.
