### ISSUE TITLE
MapboxCoreNavigation RouteController.swift  No such module 'MapboxDirections'

### ISSUE THREAD

**Issue by aloveric** [mapbox/mapbox-navigation-ios#163]
/mapbox-navigation-ios-master/MapboxCoreNavigation/RouteController.swift:3:8: No such module 'MapboxDirections'

**Comment by bsudekum** [comment]
@aloveric can you give us more information about your setup? what version are you using? pods or carthage? How have you tried to fix the problem so far?

**Comment by ericrwolfe** [comment]
If you're using cocoapods, can you try running `pod repo update` before `pod install`?

**Comment by Hbombre** [comment]
I've had this issue the past couple days trying with Cocoapods. I've tried using the example project and a fresh project, "No such module 'MapboxDirections'".
 I'm new to cocoa pods, so I will list the exact steps I've tried, I might be missing something simple:

-Download this project
-Open Terminal, _cd "folder directory"_
- _init podfile_
-open Podfile with Xcode
- uncomment platform, add pod to Example-Swift (I've also tried adding it to all the targets, same result), Pod file reads:
```
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Example-Objective-C' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Example-Objective-C

  target 'Example-Objective-CTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Example-Swift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Example-Swift
pod 'MapboxNavigation', '~> 0.2.1'

  target 'Example-SwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'MapboxCoreNavigation' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MapboxCoreNavigation

  target 'MapboxCoreNavigationTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'MapboxNavigation' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MapboxNavigation

  target 'MapboxNavigationTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```
-Terminal _pod repo update_ (because of a previous comment)
-Terminal _pod install_
-Open workspace
-Attempt to build to receive the  "No such module 'MapboxDirections'"

**Comment by ericrwolfe** [comment]
@aloveric have you gotten this working? If not, can you let us know how you've set up your project so far?

@Hbombre We updated our instructions for getting the example up and running. Could you try these out and let us know how it works for you? https://github.com/mapbox/mapbox-navigation-ios#running-the-example-project

**Comment by DundiGuy** [comment]
I think you forgot step 2 (the carthage build stuff), then the example will work.

**Comment by Hbombre** [comment]
@ericrwolfe I got it working using the updated directions. Thanks!
