### ISSUE TITLE
Overlaying Buttons/Resizing the Frame - routeViewController

### ISSUE THREAD

**Issue by nickesh23** [mapbox/mapbox-navigation-ios#166]
Is there a simple way to overlay buttons on top of the routeViewController? I've tried many of the suggestions on stackoverflow but they haven't worked, the navigation frame always comes to the front. 

Alternatively, it would be nice to be able to add constraints to the routeViewController so that it does not take up the full screen, thus letting me put labels or buttons on the sides of the screen while the navigation is happening inside a smaller view, is that possible? 

I'm a Swift beginner, so any code examples would be very helpful, thanks in advance. If this question is poorly written or incomplete, my apologies in advance.
--

*this is what my code looks like for the routeViewController:

 override func viewDidLoad() {
        super.viewDidLoad()
        
        let origin = Waypoint(coordinate: CLLocationCoordinate2D(latitude: 37.328492, longitude: -122.004065), name: "StartingLocation")
        let destination = Waypoint(coordinate: CLLocationCoordinate2D(latitude: 37.763237, longitude: -122.390706), name: "Hub1")
        let options = RouteOptions(waypoints: [origin, destination], profileIdentifier: .automobileAvoidingTraffic)
        options.routeShapeResolution = .full
        options.includesSteps = true
        Directions.shared.calculate(options) { (waypoints, routes, error) in
            guard let route = routes?.first else { return }
            let viewController = NavigationUI.routeViewController (for: route)
            viewController.routeController.snapsUserLocationAnnotationToRoute = true
            self.present(viewController, animated: true, completion: nil)
        }        
    }

**Comment by frederoni** [comment]
The RouteViewController (NavigationViewController as of v0.0.3) consist of two container views.
<img src="https://cloud.githubusercontent.com/assets/764476/25383979/abebb9a6-29be-11e7-9bf9-c36112810b19.png" width=240>
It's likely that your button ends up below the container views.
You can bring them to the front by:
```swift
routeViewController.view.bringSubview(toFront: myButton)
```
(assuming your views are added to the RouteViewController's root view)

The other alternative you mention about smaller navigation screen can be achieved by moving the content of the RouteViewController to your own view controller.

```swift
routeViewController.willMove(toParentViewController: self)
myView.addSubview(routeViewController.view)
routeViewController.didMove(toParentViewController: self)
```
instead of presenting it as a full screen view controller.
