### ISSUE TITLE
Install without Carthage or Cocoapods

### ISSUE THREAD

**Issue by datwelk** [mapbox/mapbox-navigation-ios#1712]
How would I go about adding this SDK to my project without Cocoapods or Carthage? Is there a pre-built framework available somewhere? Could I use submodules?

**Comment by frederoni** [comment]
It's possible. However, even if you don't use Carthage or CocoaPods in your own project, I would use Carthage to build this framework to avoid a lot of manual work. You would have to clone all dependencies listed in the [Cartfile](https://github.com/mapbox/mapbox-navigation-ios/blob/master/Cartfile) and drag the corresponding .xcodeproj-files to your workspace in order to build it as part of your project.

A simpler way would be to use Carthage to build the frameworks and drag them into your project. It doesn't necessarily mean you have to use Carthage to manage your current dependencies.

Just create a new folder, and add a `Cartfile` containing:
```
github "mapbox/mapbox-navigation-ios"
```
Run `carthage bootstrap --platform ios`.  Pre-built binaries needed to run this SDK will be listed under `./Carthage/Build/iOS`.

**Comment by datwelk** [comment]
Awesome thank you @frederoni!
