### ISSUE TITLE
Add instructions for installation from download

### ISSUE THREAD

**Issue by ctaylor4874** [mapbox/mapbox-navigation-ios#1752]
Add instructions/ability to download compiled SDK, similar to Mapbox's iOS SDK instruction: https://www.mapbox.com/install/ios/download/

Is this already possible?  I cannot use Carthage or Cocoapods in my project and can only add dependencies this that way.

Thanks!

**Mapbox Navigation SDK version:v0.21.0**

**Comment by 1ec5** [comment]
We don’t distribute built binaries of the navigation SDK, because the SDK is written in Swift and Swift doesn’t have ABI stability between Xcode releases. However, as https://github.com/mapbox/mapbox-navigation-ios/issues/1712#issuecomment-421981713 explains, you can use Carthage to facilitate a manual installation process without making your project depend on Carthage.
