### ISSUE TITLE
mapbox navigation dismiss the text filed toolbar done button issue .

### ISSUE THREAD

**Issue by mahenrda1990** [mapbox/mapbox-navigation-ios#1770]
I have add inputAccessoryView add to toolbar done button in using textfield . in than I click Mapbox navigation open navigation view and dismiss button click back my inputAccessoryView and done button textfield will gone for all the app instance.  

![img_0486](https://user-images.githubusercontent.com/26245051/46730884-dda4c280-cca6-11e8-8fac-6b2ad6cb3e21.PNG)
![img_0485](https://user-images.githubusercontent.com/26245051/46730889-e09fb300-cca6-11e8-96ca-6f8cb1cfbffb.PNG)
![img_0484](https://user-images.githubusercontent.com/26245051/46730892-e1d0e000-cca6-11e8-8614-778586dbb044.PNG)
![img_0483](https://user-images.githubusercontent.com/26245051/46730897-e6959400-cca6-11e8-80c0-2b5eb0cc0df9.PNG)

**Comment by akitchen** [comment]
hello - it is a little difficult to understand the issue here, but problems with inputAccessoryView are beyond our control. 

You may need to ensure that your custom inputAccessoryView is being set successfully on each instance of a UIResponder subclass that requires one. Apple has some pretty good [sample code](https://developer.apple.com/library/archive/documentation/StringsTextFonts/Conceptual/TextAndWebiPhoneOS/InputViews/InputViews.html) and [documentation](https://developer.apple.com/documentation/uikit/uitextfield/1619627-inputaccessoryview) in this area.

**Comment by mahenrda1990** [comment]
@akitchen please check both link .
Demo code link : - https://www.dropbox.com/s/y0w1ikw345xoz4q/mapboxdemo.zip?dl=0
video link :- https://youtu.be/1fEKeDBGfaw
