### ISSUE TITLE
How to set a new route without triggering a reroute

### ISSUE THREAD

**Issue by marhas** [mapbox/mapbox-navigation-ios#1777]
This is a new problem that appeared after upgrading to mapbox-navigation-ios 0.22.1.

As part the custom rerouting logic in our app we pass Mapbox a new route from time to time.

With the old Mapbox-navigation (0.20.0) we called routeController.suspendLocationUpdates(), gave the routeController a new route and then called routeController.resumeLocationUpdates(). This worked well.

With the NavigationService that appeared in 0.22 we haven’t been quite as successful unfortunately. No matter how we try go give it a new route it always triggers a reroute (i.e. it calls the shouldRerouteFrom method), which is unwanted. We’ve tried setting the new route on the NavigationService in various NavigationServiceDelegate methods and also in combination with calling navigationService.stop()/start() and even navigationService.endNavigation()/startNavigation() but haven’t been able to avoid the reroute call. This was not how it worked in the 0.20.0 version and we’d appreciate if you could help us understand when would be a proper time to give the NavigationService a new route.

Best,
Marcel

**Comment by akitchen** [comment]
Hi @marhas -- We think this may be related to https://github.com/mapbox/mapbox-navigation-ios/issues/1776 -- it could help us get to the bottom of it if you could verify whether the identity of the object sending the shouldRerouteFrom messages remains the same or is different.

**Comment by marhas** [comment]
I've updated Mapbox Navigation to 0.22.3 which indeed solved the issue with multiple issues of the NavigationService hanging around. Unfortunately it doesn't solve this issue though.

I should mention that we had @frederoni over for a visit yesterday and showed him this issue and he promised to look into it.

Thanks,
Marcel

**Comment by evisoup** [comment]
@marhas  Any update regarding this issue? I'm also seeing this unexpected reroute being called in `shouldRerouteFrom `.

**Comment by marhas** [comment]
We still have it @evisoup . We're however stuck on version 0.22.3 at the moment due to another bug/feature (depending on how you look at it) and I was hoping it might have been fixed in a more recent version. You're seeing this on the latest version @evisoup ? In that case, maybe you could revisit this issue, @akitchen? 🙏

**Comment by evisoup** [comment]
If you dig into `shouldRerouteFrom` usage in their code base, you will find that this delegate call is getting called EVERY SINGLE TIME when CoreLocation's delegate method `didUpdateLocation` is triggered. Hence, it's NOT a good idea to do any logic check here. Due to the frequency that is method is getting called, it's safer & reasonable to just put only simple logic in there and return ASAP.

I also discovered that Mapbox will do validation on whether if a reroute should happen. In that sense, `willRerouteFrom` is when Mapbox's own validation is completed. I suggest you use willRerouteFrom to make use of their validation(no need to reinvent the wheel).

In the normal case, shouldRerouteFrom will get called lots of times(whenever CL didUpdateLocations happens, which is a lot and continuous), yet valid reroute happens much less frequent. And valid reroute means `willRerouteFrom` gets called.

search `if !userIsOnRoute(location) && delegate?.router?(self, shouldRerouteFrom: location) ?? DefaultBehavior.shouldRerouteFromLocation` for more details. The code is in RouteController.swift

This is very unfortunate that we have to dig into their code base to find a solution since Mapbox documentation is very poor.

**Comment by evisoup** [comment]
@marhas

**Comment by evisoup** [comment]
so yea, in your case, `willRerouteFrom` should be used as a trigger for your app to know "A reroute is needed to happen now", instead of using `shouldRerouteFrom`

**Comment by akitchen** [comment]
it sounds like a couple things might need some clarification here.

First off, regarding the original issue topic -- setting a new route triggers a reroute event

It is by design that a reroute delegate event is sent when a new route is set. The related code can be found [here](https://github.com/mapbox/mapbox-navigation-ios/blob/523a598c266cccf65de9858a41a256320fc69ce6/MapboxCoreNavigation/RouteController.swift#L73). This is intended to offer the opportunity to react to the new route being set in any application-specific way. However, in tracing through the code just now, I notice that when a new `Route` and `RouteProgress` object are set, we fire a `willReroute` event in addition to a `didRerouteAlong` event. While `didRerouteAlong` is correct, I don't believe `willReroute` is correct as we already got the new route -- this should be sent just *before* obtaining the new route. Is this the true heart of your issue? We'll open a separate ticket about this.

Now, regarding `shouldRerouteFrom`... the text in https://github.com/mapbox/mapbox-navigation-ios/issues/1777#issuecomment-453615789 isn't entirely correct. `shouldRerouteFrom` isn't called on every location update as asserted above (which would be roughly once per second), it is called when a location update has been received which is determined to be off route, in order to give the developer the opportunity to control whether the SDK should proceed in obtaining a new route. This is working as described in the header documentation, available [in the code](https://github.com/mapbox/mapbox-navigation-ios/blob/master/MapboxCoreNavigation/NavigationServiceDelegate.swift#L15) or on the [docs site](https://www.mapbox.com/ios-sdk/api/navigation/0.27.0/Protocols/NavigationServiceDelegate.html), which, I agree, could be improved. We've been working through some documentation tooling issues recently and have a very small team.

And just to wrap up, the other comment https://github.com/mapbox/mapbox-navigation-ios/issues/1777#issuecomment-453616581 is correct, `shouldRerouteFrom` is a question -- should we reroute? -- whereas `willRerouteFrom` is a notification that we are now in the process of rerouting. I hope that helps.

**Comment by akitchen** [comment]
Thank you @evisoup for clarifying. That sounds unexpected, I agree. Perhaps you are continuing to receive off-route gps updates while the re-route request is in progress. Looking at the code in `RouteController`'s `locationManager(_, didUpdateLocations)` I can see how this could happen, and I would agree it could be considered to be a bug. 

While we have a gate inside of `reroute(from:, along:)` to short-circuit if we are already rerouting, a similar gate is probably needed inside of `didUpdateLocations` in order to avoid over-messaging the delegate in the case where we're already processing the reroute / working to obtain a new route.

Does that sound like what's happening in your case?

**Comment by evisoup** [comment]
Definitely. Customized logic is better triggerd in shouldReroutFrom compared to willRerouteFrom. The latter one is a bit too late since the reroute is already happening, while customized logic could just stop auto-reroute from happening.

**Comment by marhas** [comment]
@evisoup Thanks a lot for sharing all your findings and thanks @akitchen for continuing the investigation. 

In our case, we have some custom rerouting logic implemented which means that in some cases we want to prevent the standard Mapbox rerouting logic from running and instead run our own. 

We prevent the Mapbox rerouting logic from kicking in by returning false from shouldRerouteFrom (which also means that the willReroute delegate method won't be called) - we then calculate a new route based on our custom logic and some additional Mapbox navigation calls and finally set the new route on the route controller. 

When we do that, shouldRerouteFrom is immediately called, even though the user _is_ on this newly set route.

When setting a new route, it makes perfect sense that the delegate method didContinueAlong is called, but to me it makes less sense that shouldRerouteFrom or willReroute is called.

**Comment by akitchen** [comment]
Thanks for the followup information @marhas , it helps clarify what might be going on.

> we have some custom rerouting logic implemented which means that in some cases we want to prevent the standard Mapbox rerouting logic from running and instead run our own

It sounds like you might benefit from being able to set a flag similar to our `internal var isRerouting` which would temporarily disable off-route detection while you are calculating your new route. This would need a different name to more appropriately signal the intent/behavior (/cc @JThramer for visibility). I think we need a new feature/implementation ticket here.

> we then calculate a new route based on our custom logic and some additional Mapbox navigation calls and finally set the new route on the route controller.
> When we do that, `shouldRerouteFrom` is immediately called, even though the user is on this newly set route.

Could you please check/verify that your new route includes the user's current location as the starting point for the new route? We need to dig in here to determine whether there might be a bug, or a small issue with the new route you have set.

> When setting a new route, it makes perfect sense that the delegate method `didContinueAlong` is called, but to me it makes less sense that `shouldRerouteFrom` or `willReroute` is called.

Please verify that your new route includes the user's current location as the starting point in order for us to understand what's going on with the call to `shouldRerouteFrom`. Regarding `willReroute`, we agree, and this will be removed in https://github.com/mapbox/mapbox-navigation-ios/issues/1927

Thanks again
