### ISSUE TITLE
CarPlay search support for 3rd party applications.

### ISSUE THREAD

**Issue by vincethecoder** [mapbox/mapbox-navigation-ios#1839]
**Mapbox Navigation SDK version: 0.24.0**

In lieu of ensuring that `CarPlay` can support 3rd party apps seamlessley. A few discoveries were made that merits a few modifications of the `CarPlayManager`.

* The static framework `MapboxGeocoder` isn't discoverable by the Navigation SDK conditional check `canImport(MapboxGeocoder)` when an app integrates the Navigation SDK into its project workspace using cocoapod `pod install` command. (Since the developer has the liberty to use their preferred `Geocoder`, this framework is intended to support search -- which is classified _optional_.)

* 3rd party apps are limited to use the default `geocoder` supplied in the SDK. Developers cannot provide their own if they preferred.

* `internal` functions such the `resetPanButtons` are not reusable by 3rd party apps.

**Suggested Solutions**:

* The `CarPlayManager` should be an `open` class so that it can be subclassable by other developers who would like to inject their very own `geocoder`.

* The fields and methods highlighted above should be `public`. 

* Lastly, investigate and implement an elegant solution to address the challenge with the integration of the `MapboxGeocoder` for apps that use cocoapods.

/cc @akitchen @frederoni @andrewychen @mapbox/navigation-ios

**Comment by 1ec5** [comment]
> The static framework `MapboxGeocoder` isn't discoverable by the Navigation SDK conditional check `canImport(MapboxGeocoder)` when an app integrates the Navigation SDK into their project workspace using cocoapod `pod install` command.

Issues around `canImport()` and CocoaPods have been reported in the past, such as in #1744. As far as I can tell, the reason `canImport()` fails with CocoaPods is that the `FRAMEWORK_SEARCH_PATHS` build setting precludes finding MapboxGeocoder.framework when building MapboxNavigation.framework:

* Standard application target template in Xcode: ```$(inherited) @executable_path/Frameworks```
* Application target set up for Carthage: ```$(inherited) $(PROJECT_DIR)/Carthage/Build/iOS```
* Application target set up for CocoaPods: ```$(inherited) "${PODS_CONFIGURATION_BUILD_DIR}/MapboxCoreNavigation" "${PODS_CONFIGURATION_BUILD_DIR}/MapboxDirections.swift" "${PODS_CONFIGURATION_BUILD_DIR}/MapboxMobileEvents" "${PODS_CONFIGURATION_BUILD_DIR}/MapboxSpeech" "${PODS_CONFIGURATION_BUILD_DIR}/Polyline" "${PODS_CONFIGURATION_BUILD_DIR}/Solar" "${PODS_CONFIGURATION_BUILD_DIR}/Turf" "${PODS_ROOT}/Mapbox-iOS-SDK/dynamic" "${PODS_ROOT}/MapboxNavigationNative"```

Most likely, CocoaPod’s more verbose search path is intended to reduce the likelihood of conflicts among the various pods that might be installed, since two pods might have different names but specify the same product name and module name.

CocoaPods has declined to add a mechanism for pods to explicitly declare that they may conditionally import other pods: CocoaPods/CocoaPods#5631. But if the issue is really just the framework search path, then one workaround might be to add `"${PODS_CONFIGURATION_BUILD_DIR}"` to the `FRAMEWORK_SEARCH_PATHS` build setting in `pod_target_xcconfig` in the podspec. There might be a similar workaround for Podfiles.

Regardless, if we can find a way to avoid the need for `canImport(MapboxGeocoder)` in this library, that would sidestep any issues around dependency management.

**Comment by vincethecoder** [comment]
@akitchen sounds good to me!

**Comment by vincethecoder** [comment]
@akitchen would we mainly groom the static framework efforts suggested by @1ec5? 

Just wanted to clarify... because I recall we were all on the same page in regards to making `CarPlayManager` an `open` class -- as this will certainly be a major breakthrough for developers considering dependency injection.

**Comment by akitchen** [comment]
There is not a direct dependency on the geocoder, but making the class open seems OK to me. I'm not on board with adding more `canImport()` statements etc.

Please move those concerns into separate efforts. The geocoder is wrapped by our search template example, which is only an example... and should be completely encapsulated therein. It should not need to leak into the CarPlayManager proper.

**Comment by akitchen** [comment]
@JThramer and I just had a good chat about moving all the `canImport()` filtered Geocoder/search-related code into a new class, perhaps a `CarPlaySearchManager`, which feels like a good step toward solving the root problem that this ticket is getting at.

I'd recommend we close or radically re-groom this ticket, and also close out https://github.com/mapbox/mapbox-navigation-ios/pull/1842 , in order to focus on a solution which solves the root problem(s) here:

 - As a developer, I want my CarPlay integration to include Mapbox's Geocoder and example search template
    - Great! Pass a `CarPlaySearchManager` (or some such) into the `CarPlayManager` at initialization time
 - As a developer, I want my CarPlay integration to include my own search template
    - Great! Return your own template button in the leading or trailing butting items returned to the `CarPlayManager` by implementing the [appropriate delegate method](https://github.com/mapbox/mapbox-navigation-ios/blob/a0e5dbc3ed63754a4311964d5c41ba4636d17988/MapboxNavigation/CarPlayManagerDelegate.swift#L32)

What's a bit tricky in the second case is how to manage the delegation of `CPSearchTemplateDelegate` methods currently in a [CarPlayManager extension](https://github.com/mapbox/mapbox-navigation-ios/blob/4053d1d1cf29e324045f51c745715baa1a20a9d5/MapboxNavigation/CarPlayManager%2BSearch.swift#L43), for example if building up a history of selected items. Perhaps all of this should be encapsulated on the `CarPlaySearchManager`; TBD. 

a good couple goals for this effort would be to remove all the `canImport(MapboxGeocoder)` statements, put that code where it ought to be, and solve the optional dependency problem in a more elegant way. Let's avoid using inheritance to glom more onto the `CarPlayManager`, and look for opportunities to solve these problems with composition and protocol orientation.

**Comment by vincethecoder** [comment]
@akitchen I have already implemented a similar pattern for the driver-app. We currently an independent class `CarPlaySearchManager` that orchestrates the search related pieces of CarPlay.

We don't have to pass the `CarPlaySearchManager` during initialization. Just like the `carPlayManager` instance in the `AppDelegate`, we can have a `carPlaySearchManager` that handles all the delegate calls in the `AppDelegate+CarPlay.swift`. This makes both managers loosely-coupled.
> As a developer, I want my CarPlay integration to include Mapbox's Geocoder and example search template
Great! Pass a CarPlaySearchManager (or some such) into the CarPlayManager at initialization time

**Comment by vincethecoder** [comment]
Based on an earlier conversation, we decided to call the search class, `CarPlaySearchController`. We would like to adhere to a naming convention identical to the Cocoa guidelines. @frederoni and I plan to 
pair/groom this story and document the plan of attack for this issue to the rest of the team.

**Comment by vincethecoder** [comment]
Upon further assessment, we can create a `CarPlaySearch.framework` to contain a sample search UI that inherits the `MapboxGeocoder.framework`. More details here: https://github.com/mapbox/mapbox-navigation-ios/issues/1923

**Comment by 1ec5** [comment]
Superseded by #2285.
