### ISSUE TITLE
Speech synthesizer skips road names in arabic

### ISSUE THREAD

**Issue by maliesa96** [mapbox/mapbox-navigation-ios#1911]
During turn by turn navigation road labels appear in the local language (arabic in my case, which isn't supported by Amazon Polly). As a result the synthesizer only reads the english part of the instruction. Is there a way to use AVSpeechSynthesizer for the arabic part and Amazon Polly for the rest? 

Alternatively, can I force road labels/names to be in english?

Thanks.
Mapbox Navigation SDK version: 0.25.0

**Comment by 1ec5** [comment]
> Alternatively, can I force road labels/names to be in english?

The road names in turn-by-turn instructions come from the Directions API, which currently only provides road names in the local language, even when OpenStreetMap has names in other languages: Project-OSRM/osrm-backend#4561.

The map labels match the Directions API’s use of local names by default, both for consistency and to match what’s on signage. However, you can force the labels to be in English by passing an `en` locale into `MGLStyle.localizeLabels(into:)` inside your implementation of `MGLMapViewDelegate.mapView(_:didFinishLoading:)`.

> Is there a way to use AVSpeechSynthesizer for the arabic part and Amazon Polly for the rest?

It is possible but not straightforward. You’d subclass MapboxVoiceController, separating out the Arabic parts of the road names, perhaps based on a regular expression that looks for a certain character range. Then you’d alternate between calling MapboxVoiceController’s audio-playing methods and `MapboxVoiceController.speakWithDefaultSpeechSynthesizer(_:error:)` (which uses AVSpeechSynthesizer). It’s especially tricky because both of those mechanisms are asynchronous without accepting completion handlers.

It would be a lot more straightforward to have AVSpeechSynthesizer speak the entire instruction string, though at the cost of English speech quality.

**Comment by maliesa96** [comment]
Extremely helpful response, thank you. Is there a way to avoid reading the road names all together? For example, instead of it saying "in 300m, turn right on to *arabic text* " it would just say "in 300m, turn right". My current solution for this is to modify `instruction` from within the `voiceController(_ voiceController: RouteVoiceController, willSpeak instruction: SpokenInstruction, routeProgress: RouteProgress)` delegate method and set it to the text before the " on". Is there a more robust solution? Or at least a way of ensuring all the different instruction formats are correctly modified?

**Comment by 1ec5** [comment]
The spoken instruction text is currently generated by closed-source code in the Directions API or MapboxNavigationNative (if using offline routing) that processes the routing engine’s `instructions` properties using strings from [OSRM Text Instructions](https://github.com/mapbox/osrm-text-instructions/). You could try generating your own instruction text based on the upcoming step’s `maneuverType` and `maneuverDirection` properties and `RouteStepProgress.userDistanceToManeuverLocation`, perhaps using strings from OSRMTI. It won’t be a one-for-one match with what the Directions API provides, but it might be a reasonable tradeoff considering what you’re getting with the Arabic street names right now.

**Comment by shadabmustaafa** [comment]
This thread is almost an year old and we are still facing the same issue. Any idea if this will be resolved anytime soon?

**Comment by 1ec5** [comment]
The posts above specifically ask for a couple approaches to fixing the issue that would be more complex on our end. However, depending on your needs, you could implement `VoiceControllerDelegate.voiceController(_:willSpeak:routeProgress:)` along these lines to at least ensure that something is pronounced rather than silence:

```swift
@objc(voiceController:willSpeakSpokenInstruction:routeProgress:)
optional func voiceController(_ voiceController: RouteVoiceController, willSpeak instruction: SpokenInstruction, routeProgress: RouteProgress) -> SpokenInstruction? {
    let text = (instruction.text as NSString).applyingTransform(.toLatin, reverse: false)
    let ssmlText = (instruction.ssmlText as NSString).applyingTransform(.toLatin, reverse: false)
    return SpokenInstruction(distanceAlongStep: 0, text: text, ssmlText: ssmlText)
}
```

**Comment by 1ec5** [comment]
By the way, Polly does support Arabic now, but the navigation SDK uses Polly through the Mapbox Voice API, which isn’t able to match the language code `ar` provided by iOS to Polly’s preferred language code for Arabic, `arb`: mapbox/locale-utils#9.

**Comment by osamaashraf2005** [comment]
I'm having the same problem in Android, I'm initializing the SpeechPlayerProvider like that:
SpeechPlayerProvider   speechPlayerProvider   = new SpeechPlayerProvider(getContext(), "ar", true, voiceInstructionLoader);
and not able to get the speech player speak the arabic road name.
Can anyone help? what is the suitable way to let speech player speak road name in Arabic on Android.

**Comment by 1ec5** [comment]
This is the iOS navigation SDK’s repository; if you’re encountering problems with an Arabic speech player on Android, the [Android navigation SDK](https://github.com/mapbox/mapbox-navigation-android/) repository may be a better place to get an answer.

**Comment by 1ec5** [comment]
mapbox/mapbox-navigation-android#2511 tracks the corresponding problem on Android.

**Comment by 1ec5** [comment]
To be clear, this is about reading the voice instructions _entirely_ in Arabic. If you request instructions in English, for instance, but travel in an Arabic-speaking country, chances are you’ll hear something like “Turn left onto _[pause]_ then turn right”. That pause is because Polly’s English voice is unable to make sense of the Arabic script. To address this issue, either the Directions API (and OSRM or Valhalla underneath it) would need to expose a localized name tag from OpenStreetMap like `name:en`, or we would need to transliterate the road name to Latin on the client side. On iOS, we could use StringTransform to automatically transliterate Arabic to Latin, as the map SDK does for VoiceOver:

https://github.com/mapbox/mapbox-gl-native-ios/blob/aa3f3875628a7bbda67bf687b6b2dcbcde55e9ad/platform/darwin/src/NSString%2BMGLAdditions.m#L43-L62

/ref Project-OSRM/osrm-backend#4561 valhalla/valhalla#2254 mapbox/mapbox-gl-native#10881
