### ISSUE TITLE
Route progress classes should be codable

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#1940]
RouteProgress, RouteLegProgress, and RouteStepProgress should conform to NSSecureCoding or Codable. MapboxDirections.swift classes such as Route are already NSSecureCoding-conformant.

/cc @mapbox/navigation-ios

**Comment by 1ec5** [comment]
Once we move the progress classes off NSObject (#2294), it’ll be straightforward to implement Codable conformance in these classes. This will make it much easier for developers to implement state restoration.

**Comment by Udumft** [comment]
`RouteLegProgress` already conforms to `Encodable` here:
https://github.com/mapbox/mapbox-navigation-ios/blob/134af2282ab876d6b76dca13cbf9e0ae7c8c73af/MapboxCoreNavigation/EventDetails.swift#L298-L329

But this implementation does not seem to be exactly what is expected, because it does not directly encodes it's variables and instead encodes sub-sub properties. I thought that it is intended to be used for passing as context info for some Events, but I could not find any real usage.
What is this implementation for?

**Comment by JThramer** [comment]
Blocked by https://github.com/mapbox/mapbox-navigation-ios/pull/2352

**Comment by JThramer** [comment]
Posterity: Regarding [this comment](https://github.com/mapbox/mapbox-navigation-ios/issues/1940#issuecomment-603794310), as long as route-step is encodable, `RouteLegProgress` should just encode `RouteStep` directly. Needs investigation.

**Comment by zugaldia** [comment]
Closing per sprint planning convo.

**Comment by 1ec5** [comment]
Sorry, I got some wires crossed in sprint planning. This change is still relevant but doesn’t need to happen for v1.0.0.

> But this implementation does not seem to be exactly what is expected, because it does not directly encodes it's variables and instead encodes sub-sub properties. I thought that it is intended to be used for passing as context info for some Events, but I could not find any real usage.
> What is this implementation for?

Looks like this implementation was introduced in mapbox/mapbox-navigation-ios@66cb213e417f00d3c13d4df9edcadf80686ced6e for mapbox/mapbox-navigation-ios#1533 but ended up being unused after mapbox/mapbox-navigation-ios@982a94c8e8ba880c6030240a97bf148dc017218e in the same PR. We can safely remove that implementation and replace it with a more standard one that directly encodes its members.
