### ISSUE TITLE
Remove the ETA Timer

### ISSUE THREAD

**Issue by JThramer** [mapbox/mapbox-navigation-ios#1948]
What benefit does it bring anyway?

This resides in `RouteMapViewController` in master, [was moved](https://github.com/mapbox/mapbox-navigation-ios/pull/1912/files#diff-d558e36a8c6824d7a5c4c0d065e55d1bR119) to the `BottomBannerView` in #1912. 

Barring any objection, We should remove this.

/cc @mapbox/navigation-ios

**Comment by 1ec5** [comment]
This timer was introduced in #595. It’s intended to fire only [every 30&nbsp;seconds](https://github.com/mapbox/mapbox-navigation-ios/pull/1912/files#diff-292af689ce88d5b5aa06966456abc0e9L911). I don’t think it’s intentional that it gets reset every second. At one point, progress change notifications only occurred when transitioning between alert levels, which would happen at most three times per step, so it’s possible that the resetting code was added under that assumption.

**Comment by JThramer** [comment]
Closing as stale.
