### ISSUE TITLE
The navigation route disappears if you toggle the mapView's styleURL several times.

### ISSUE THREAD

**Issue by joshpuente** [mapbox/mapbox-navigation-ios#2008]
Mapbox Navigation SDK version: v0.28.0

During the turn-by-turn navigation mode we give our users the ability to toggle the mapView's styleURL. We've noticed that after doing this a few times, the blue polyline of the route disappears. However, if you continue toggling the mapView's styleUrl then eventually the blue polyline will reappear. 

Steps to reproduce:
1. Start the turn-by-turn navigation mode with a particular route.
2. Change the mapView's styleURL several times during navigation
3. Notice that the route's polyline disappears

**Comment by 1ec5** [comment]
We recommend specifying one or more instances of `Style` subclasses when initializing a NavigationViewController rather than setting `styleURL` directly. You can set its `mapStyleURL` property to the map style you want when that Style is active. The sources and style layers added by `NavigationMapView.showRoutes(_:legIndex:)` get blown away whenever the style URL changes, due to mapbox/mapbox-gl-native#6180, so you’d need to call `NavigationMapView.showRoutes(_:legIndex:)` after setting the style URL. But the `Style` mechanism is preferable because StyleManager already knows how to do that.
