### ISSUE TITLE
0.30 building fails because Xcode tries to build it with Swift 4.2

### ISSUE THREAD

**Issue by flashspys** [mapbox/mapbox-navigation-ios#2060]
With the update from 0.30.0-alpha to 0.30.0 we noticed that Xcode is not able to build MapBox Navigation and MapBox CoreNavigation anymore. The reason is that Xcode want to build these two frameworks with Swift 4.2. Unfortunately, I can't say _why_ Xcode wants to build this with 4.2. I saw in your podspec that you were specifying 4.0 explicitly but somewhere on the way via cocoapods this seems to get lost. I'm not quite sure if this is maybe our fault, but in case some other user experienced this issue: Easily fixable by just setting the Swift version in the Pods.xcworkspace to "Swift 4". #2059 should fix this anyway.

**Mapbox Navigation SDK version:** 0.30.0

**Comment by 1ec5** [comment]
This was fixed in #2058, which hasn’t been released yet, but #2059 ensures that Xcode doesn’t try to build the code that’s been migrated to Swift 4.2 as Swift 4.0.

**Comment by 1ec5** [comment]
I wonder if it has to do with `swift_version` getting replaced with `swift_versions` in the JSON podspec on CocoaPods trunk. Compare the podspec between v0.29.1 and v0.30.0:

https://github.com/CocoaPods/Specs/blob/45845936f7b72931b9ff83aab35a4762de29cd09/Specs/5/8/b/MapboxNavigation/0.29.1/MapboxNavigation.podspec.json#L47
https://github.com/CocoaPods/Specs/blob/45845936f7b72931b9ff83aab35a4762de29cd09/Specs/5/8/b/MapboxNavigation/0.30.0/MapboxNavigation.podspec.json#L44

(v0.30.0-beta.1 was unaffected because it wasn’t pushed to CocoaPods trunk.)

CocoaPods/trunk.cocoapods.org#256 upgraded CocoaPods trunk from CocoaPods v1.6.0 to v1.7.0-beta.2 a couple hours before we pushed to trunk using v1.7.0-beta.2 for the first time. (Previous releases had been pushed using v1.6.1.) v1.7.0-beta.1 is the first version that includes CocoaPods/CocoaPods#8192, which introduced a new `swift_versions` (plural) command. Per https://github.com/CocoaPods/CocoaPods/issues/8191#issuecomment-463894090, v1.7.0 is backwards-compatible with the `swift_version` command in existing podspecs, but I’m not sure v1.6.0 is forwards-compatible with the `swift_versions` command in newly uploaded podspecs.

**Comment by 1ec5** [comment]
@flashspys, for now, as a workaround, please upgrade to CocoaPods v1.7.0-beta.1. Sorry for the inconvenience!

**Comment by 1ec5** [comment]
I’ve re-pushed the MapboxCoreNavigation and MapboxNavigation pods to CocoaPods trunk using CocoaPods v1.6.1. If you’re still on CocoaPods v1.6.1, run `pod update` to get the corrected podspec; the errors should go away at that point.

**Comment by 1ec5** [comment]
CocoaPods/CocoaPods#8637 tracks the upstream issue. Until it’s fixed, we’ll push navigation SDK releases using CocoaPods v1.6.1 to avoid the issue.
