### ISSUE TITLE
Will Mapbox navigation keep the compatibility with OSRM?

### ISSUE THREAD

**Issue by seanphoenix** [mapbox/mapbox-navigation-ios#2072]
**Mapbox Navigation SDK version:**
v0.30.0

Hi guys,

I am now working with Mapbox navigation, and I'd like to try it with OSRM as backend. However, I could not make it work. Seems like lacking of voiceInstructions and displayInstructions will cause some exception inside MapboxNaviationNative. I am not able to trace into it.
Then I try to use *LegacyRouteController* and it works.
But the LegacyRouteController is marked as deprecated, so I'd like to know if the compatibility with OSRM is in the roadmap, or it is planned to be removed? 

Thanks,
Sean Chiu

**Comment by mikumi** [comment]
I am interested in this as well and very much would like to keep using Mapbox with a custom OSRM backend.

**Comment by 1ec5** [comment]
We don’t have immediate plans to remove LegacyRouteController, but the MapboxNavigationNative-powered RouteController is the focus of development going forward; that’s what the deprecation refers to. LegacyRouteController has some basic fallbacks in place for when the Route object lacks data about spoken and visual instructions, but the user experience hasn’t been good for some time now (since before #614 and especially before #767).

In general, whether you use LegacyRouteController or RouteController, the navigation SDK is primarily designed to work with the Mapbox Directions API or Map Matching API. If you plan to use the SDK with a custom OSRM instance or any other routing engine, you’ll need to fashion a Route object that contains all the information the navigation SDK expects, like spoken and visual instructions. Since the SDK automatically requests a new route when the user needs to be rerouted, you could ensure consistency by having your server endpoint produce [a response similar to the Mapbox Directions API](https://docs.mapbox.com/api/navigation/#route-object). Alternatively, your application can [send the route geometry to the Mapbox Map Matching API](https://docs.mapbox.com/ios/navigation/examples/custom-server/) to [get a compatible response](https://blog.mapbox.com/take-the-scenic-route-with-our-new-bring-your-own-route-feature-d3500a6a91c3).

**Comment by 1ec5** [comment]
The specific crash you were seeing when spoken instructions are missing is being tracked in #2073.

**Comment by seanphoenix** [comment]
@1ec5 Hi, just wondering, if there is any plan to add more hook for the case? For example, add a hook (delegate-ish) in **MBDirections** so we can have the opportunity to alter the json file?

**Comment by 1ec5** [comment]
Directions calls `RouteOptions.response(from:)` to transform the API’s JSON-formatted response into Route objects. You can subclass NavigationRouteOptions to massage the response further, then use an instance of your subclass to calculate the initial route. The SDK persists this options object even after rerouting.

**Comment by seanphoenix** [comment]
@1ec5 that sounds a good idea. Thanks.

**Comment by seanphoenix** [comment]
@1ec5 just figured out, I tried it earlier, since the func is declared with **public** instead of **open**, I am not able to override it in my project. Also, same thing happened with **internal var path** and **internal var abridgedPath**.

**Comment by 1ec5** [comment]
Closing this issue, as the original question has been answered in https://github.com/mapbox/mapbox-navigation-ios/issues/2072#issuecomment-479582553.

Please feel free to open more specific issues in the MapboxDirections.swift repository as you encounter access control or other bugs in the library. Thank you!
