### ISSUE TITLE
destination and voice navigation in kilometers - need miles

### ISSUE THREAD

**Issue by TCOA** [mapbox/mapbox-navigation-ios#211]
How do we change the displayed and spoken distance to feet/miles instead of meters/kilometers?

**Comment by 1ec5** [comment]
I’m pretty sure it’s currently based on the user’s system locale, specifically the behavior of `Locale.usesMetricSystem`. In order to support the metric/U.S. setting that Maps and other applications have, which overrides the locale’s default, we’d need to expose an option in the SDK that we keep in sync with the various distance formatters’ locales.

**Comment by TCOA** [comment]
It certainly is - sorry for the question......  I bought a new phone in the US and came to Ecuador - hadn't realized it was set up for local settings (not sure when that happened, but certainly it was...)

Changing the setting to US changed to feet/miles (though the British accent female voice certainly doesn't know how to pronounce the local street names here!)

Other than having to sign up for another service, is there another way to change that voice?

**Comment by bsudekum** [comment]
> Other than having to sign up for another service, is there another way to change that voice?

@TCOA this should be fixed in https://github.com/mapbox/mapbox-navigation-ios/pull/187, currently not in a release yet.

If you're looking for a more robust speech synthesizer you should look into using the Polly integration. This will require an aws token. ref example: https://github.com/mapbox/mapbox-navigation-ios/blob/943b007199377d646cd33812e25e19961d50e4bc/Examples/Swift/ViewController.swift#L141-L144

**Comment by TCOA** [comment]
Yeah, saw about signing up to Polly - just getting soooooo many sign-ups for things lately, getting hard to keep them all straight (on top of all the new stuff I'm learning just to put this app together - 5 weeks ago, I didn't even know how to spell Xcode - now, I'm closing in on getting a pretty extensive app out to Apple for approval.....) 

This library has been a lifesaver for me, filling in a load of blanks that I was going to have to build, though I am seeing I may have to go back to building it myself from the components to access the 'bits' (trying very hard not to as this is really great!) - until you guys can get more documentation on how to get to things (one of the more 'asked for' items still on my 'can we do?' list is setting the compassView - I've tried all sorts of things and nothing so far and can't seem to get to it (though it is not a deal killer, I still have other 'how to access' questions - partly because I'm new to Xcode, partly just having difficulty with the flow of this coding {I've been doing php and javascript for 20-some years, just getting into mobile....})  

Thanks for your fast turn-around on answers, it is really helping.

**Comment by bsudekum** [comment]
@TCOA let us know when it's in the app store!

**Comment by andrey-str** [comment]
UK uses miles for distance but officially it uses metric system, thus Locale.usesMetricSystem returns true. How to display miles in with UK region selected? :-)

**Comment by 1ec5** [comment]
Good point – let’s track that in #242.
