### ISSUE TITLE
Can't change user's current location annotation view

### ISSUE THREAD

**Issue by Jauzee** [mapbox/mapbox-navigation-ios#213]
Is it possible to change user's location tracking annotation view (circle with arrow shape inside)?

**Comment by 1ec5** [comment]
RouteMapViewController is the NavigationMapView’s delegate (conforming to MGLMapViewDelegate). Since a map view can’t have multiple delegates, we need to plumb some additional MGLMapViewDelegate methods through RouteMapViewControllerDelegate, NavigationViewController, and NavigationViewControllerDelegate.

In particular, `MGLMapViewDelegate.mapView(_:viewFor:)` needs to be exposed as `NavigationViewControllerDelegate.navigationViewController(_:mapView:viewFor:)` so that the developer can implement their annotation view to replace the default. (We have an example of that implementation coming in mapbox/ios-sdk-examples#50.)

**Comment by Jauzee** [comment]
@1ec5 will it also support changing user location annotation in `navigation` mode?

**Comment by Jauzee** [comment]
Can you please guide me where in the code default shape for this annotation was set. Is this part of `mapbox-navigation-ios` or ir is a part of `MapboxDirections`?

**Comment by 1ec5** [comment]
> will it also support changing user location annotation in navigation mode?

Yes.

> Can you please guide me where in the code the default shape for this annotation was set.

The navigation SDK is currently using the default annotation image provided by the iOS map SDK (mapbox-gl-native).

**Comment by 1ec5** [comment]
#498 would expose the delegate method for customizing the user location annotation view.

**Comment by bsudekum** [comment]
This has been implemented.
