### ISSUE TITLE
Remove workarounds adding content inset when setting map camera

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#2145]
Once mapbox/mapbox-gl-native#14813 lands and we upgrade to map SDK v5.1.0, `NavigationMapView.userAnchorPoint` and possibly other methods need to be updated to stop adding the map view’s `contentInset` to the edge padding when setting the map’s camera.

/ref https://github.com/mapbox/mapbox-navigation-ios/issues/1651#issuecomment-418675194
/cc @mapbox/navigation-ios @fabian-guerra @d-prukop

**Comment by 1ec5** [comment]
In rudimentary testing, `NavigationMapView.userAnchorPoint` and `NavigationMapView.updateCourseTracking(location:camera:animated:)` seem to be behaving fine after upgrading to map SDK v5.1.0. That’s a bit of a surprising outcome, given that there was obviously a bug in the map SDK previously and it got fixed in v5.1.0.

**Comment by 1ec5** [comment]
Fixed in #2134.

**Comment by 1ec5** [comment]
I must not’ve been paying close enough attention, but `NavigationMapView.updateCourseTracking(location:camera:animated:)` is not quite correct. Upgrading from map SDK v5.0.0 to v5.1.0 causes the map to pivot around the center-bottom of the map instead of the puck’s center.

**Comment by 1ec5** [comment]
Possibly related to mapbox/mapbox-gl-native#15232.

**Comment by 1ec5** [comment]
> I must not’ve been paying close enough attention, but `NavigationMapView.updateCourseTracking(location:camera:animated:)` is not quite correct. Upgrading from map SDK v5.0.0 to v5.1.0 causes the map to pivot around the center-bottom of the map instead of the puck’s center.

This is probably mapbox/mapbox-gl-native#15233.

**Comment by astojilj** [comment]
> Once [mapbox/mapbox-gl-native#14813](https://github.com/mapbox/mapbox-gl-native/pull/14813) lands and we upgrade to map SDK v5.1.0, `NavigationMapView.userAnchorPoint` and possibly other methods need to be updated to stop adding the map view’s `contentInset` to the edge padding when setting the map’s camera.
> 
> /ref [#1651 (comment)](https://github.com/mapbox/mapbox-navigation-ios/issues/1651#issuecomment-418675194)
> /cc @mapbox/navigation-ios @fabian-guerra @d-prukop

@1ec5, @fabian-guerra 

Since https://github.com/mapbox/mapbox-gl-native/commit/402645109f8d0535cac132d824d39f38a4f1c558 is already in 5.1, it requires described update.

As padding is added to content inset, current anchor point calculation is out of sync with mapbox/mapbox-gl-native#14813 and effectively adds content insets twice: once in [anchor point calculation](https://github.com/mapbox/mapbox-navigation-ios/blob/0949bcfca5f5350a90b773a869c1e1cb3a5d04d5/MapboxNavigation/NavigationMapView.swift#L158) and once in [setCamera](https://github.com/mapbox/mapbox-navigation-ios/blob/0949bcfca5f5350a90b773a869c1e1cb3a5d04d5/MapboxNavigation/NavigationMapView.swift#L342) - defined in https://github.com/mapbox/mapbox-gl-native/issues/12818. This is a cause of having the puck jumping down - working on fix for this in https://github.com/mapbox/mapbox-navigation-ios/pull/2211.

**Comment by noway** [comment]
In my experience, the puck is detaches from the route while jumping up, although when it's down it's too low as well, so the puck sort of either being too low (which is not too bad cause I can offset that myself I think) or too high and detached. 

Either way, is there any immediate workaround for puck jumping up/down? I'm using `"mapbox/mapbox-navigation-ios" "v0.37.0"` and `"https://www.mapbox.com/ios-sdk/Mapbox-iOS-SDK.json" "5.4.0"` via Cathage. I set my bound using:
```objective
self->_navigationViewController.view.frame = CGRectMake(0, 0, self.bounds.size.width, self.bounds.size.height);
```

**Comment by 1ec5** [comment]
Once #2211 lands, #2248 will supersede the original problem tracked in this issue.
