### ISSUE TITLE
Yoruba localization

### ISSUE THREAD

**Issue by toblinkz** [mapbox/mapbox-navigation-ios#2158]
**Mapbox Navigation SDK version:**

Please am done translating for yoruba with transifex. Can my localization be pulled

**Comment by 1ec5** [comment]
Thanks for your help translating the SDK into Yoruba! #2159 will add the translations, but it looks like there are a few syntax errors in the translation that need to be fixed in Transifex first.

By the way, your [OSRM Text Instructions](https://github.com/Project-OSRM/osrm-text-instructions/) localization in Yoruba will need to be added to that repository too.
