### ISSUE TITLE
Exit colors do not update when day/night style changes

### ISSUE THREAD

**Issue by johnnewman** [mapbox/mapbox-navigation-ios#2161]
**Mapbox Navigation SDK version: 0.34.0**

When the system time causes a day/night style change while navigating, exits in the instruction banner view don't change color. This is the `ExitView.appearance().foregroundColor` within `DayStyle.swift`.

It happens while transitioning from day into night as well as night into day:

<img src="https://user-images.githubusercontent.com/1591735/60050824-8eb98480-969f-11e9-95de-98898e832852.jpg" width="250" /> <img src="https://user-images.githubusercontent.com/1591735/60050853-a133be00-969f-11e9-8aff-606e3dec00bb.jpg" width="250" />

**Comment by 1ec5** [comment]
The wrong-colored generic shields in CarPlay (#2191) are probably related.

**Comment by avi-c** [comment]
I believe the issue here is that the generated ExitView & GenericShieldView images are cached and reused, but the cache is not invalidated when the style changes. When the cached images are used in the new style, they will most likely not be the correct colors.

Probably the easiest fix is to invalidate the cache whenever the style changes, and when the appearance trait collection changes (so that Dark/Light mode changes work too).

**Comment by avi-c** [comment]
Scratch that. No need to invalidate the cache. The issue is that the foreground color is not being set before the views are snapshotted. This means that the same image is retrieved from the cache regardless of what the UIAppearance proxy foregroundColor is set to.

A PR with a fix is coming shortly.

**Comment by johnnewman** [comment]
I am still seeing this issue in Mapbox Navigation SDK 0.39.0.

**Comment by 1ec5** [comment]
Looks like the issue was reported again in #2938 and fixed in #2977 by invalidating the cache, as originally proposed in https://github.com/mapbox/mapbox-navigation-ios/issues/2161#issuecomment-560933324.
