### ISSUE TITLE
RouteProgress Fatal error: Can't form Range with upperBound < lowerBound

### ISSUE THREAD

**Issue by Icy1337** [mapbox/mapbox-navigation-ios#2167]
Happens when I try to **walk** navigate from this coordinate `let origin = Waypoint(coordinate: CLLocationCoordinate2D(latitude: 31.90709, longitude: 34.81171))` to this one `let destination = Waypoint(coordinate: CLLocationCoordinate2D(latitude: 31.9045, longitude: 34.80971))` not sure why.
<img width="1228" alt="Screen Shot 2019-06-28 at 7 54 41" src="https://user-images.githubusercontent.com/10535208/60318015-03c7db00-997a-11e9-87d2-e02454bf6928.png">

**Comment by 1ec5** [comment]
Thank you for this bug report. The example you’ve provided corresponds roughly to the following request URL:

`https://api.mapbox.com/directions/v5/mapbox/walking/34.81171,31.90709;34.80971,31.9045.json?geometries=geojson&overview=full&steps=true&alternatives=false&continue_straight=true&roundabout_exits=true&annotations=congestion&access_token=`

`nextManeuverCoordinateIndex` is less than `maneuverCoordinateIndex`, so `stepCoordinateCount` would have to be 0, which means a particular non-arrival step has less than two coordinates. We could probably surface this error in a more informative way.

Indeed, for this route, the Directions API returns a step just before the arrival step that has only a single coordinate in its LineString geometry, which is invalid. It’s a sharp left [at this node](https://www.openstreetmap.org/node/5368153522), which is unexpected, since there are no sharp left turns on these walkways and the route goes straight along [a single way](https://www.openstreetmap.org/way/556484120) towards the destination.

**Comment by Icy1337** [comment]
Alright thank you very much, so should I assume this will be fixed in the next update?

**Comment by 1ec5** [comment]
As far as I can tell, you’ll have to wait for a server-side fix. We could patch this particular bit of client-side code to be more defensive and avoid crashing, but the route data itself is malformed, so there’s bound to be cascading failures. Even if not, it’s the wrong directions. But let us know if you’re seeing the issue beyond this one footpath.

**Comment by 1ec5** [comment]
The issue was fixed in valhalla/valhalla#1876 and the fix has been deployed. Let us know if you still see this issue on other routes.
