### ISSUE TITLE
Error installing with CocoaPods due to missing SWIFT_VERSION in dependencies

### ISSUE THREAD

**Issue by MobileDev1234** [mapbox/mapbox-navigation-ios#2169]
I am facing issues when installing map box navigation on my iOS objective c project.I am facing issues when install am facing issues when installing map box navigation on my iOS objective c project.

![123](https://user-images.githubusercontent.com/39965071/60390900-60f79400-9b14-11e9-999e-c9b3be4ad263.png)

**Comment by frederoni** [comment]
Transferred this issue from [mapbox-gl-native](https://github.com/mapbox/mapbox-gl-native) to [mapbox-navigation-ios](https://github.com/mapbox/mapbox-navigation-ios).

Can you try specifying a `SWIFT_VERSION`, preferably 5.0, on your application’s target? It's called `Swift Language Version` in Xcode’s `Build Settings` editor.

**Comment by billyking991** [comment]
I was having this issue as well, but I solved it by adding:

ENV['SWIFT_VERSION'] = '4.2' at the top of my podfile, right below platform :iOS, '10.0'.  Otherwise your entire podfile gets hosed.  Hope it helps!  

Can I update that line to Swift 5.0 safely?  From your previous comment I should be able to, correct?  Do Turf, Solar, and Polyline conform to Swift 5.0 standards?

Thank you!

**Comment by 1ec5** [comment]
Yes, all three can be interpreted as Swift 5. No code changed in raphaelmor/Polyline#57, and the only code change in mapbox/turf-swift#83 was to fix a benign warning.
