### ISSUE TITLE
Better versioning of dependencies

### ISSUE THREAD

**Issue by kozyr** [mapbox/mapbox-navigation-ios#2189]
**Mapbox Navigation SDK version:**
0.35

I've tried running my project today with 0.35, and it downloaded Mapbox-iOS-SDK v.5.2, and failed to compile. Before 5.2 release, it worked just fine with 5.1.1. This all comes from the fact that the dependency on Mapbox-iOS-SDK is ~> 5.1 within Mapbox Navigation, not ~> 5.1.0, which allows for 5.2, 5.3 etc. to be downloaded even though that might break the code that relied on original Mapbox Navigation 0.35 and Mapbox-iOS-SDK 5.1.x

**Comment by 1ec5** [comment]
Did it fail to compile because of warnings about deprecated methods? If so, I’m tracking that issue in https://github.com/mapbox/mapbox-navigation-ios/pull/2188#issuecomment-515376801 and we expect to have a fix out today. However, note that Mapbox libraries do not consider deprecations to be backwards-incompatible changes. If you enable the warnings-as-errors build setting, you may at times encounter deprecation warnings that we will address in short order but are not considered in the context of semantic versioning.

**Comment by 1ec5** [comment]
#2208 made the requirement for v5.2.0 and above more explicit.
