### ISSUE TITLE
Prevent abrupt re-routing / immediate u-turns

### ISSUE THREAD

**Issue by ericrwolfe** [mapbox/mapbox-navigation-ios#221]
iOS version of https://github.com/mapbox/mapbox-navigation-android/issues/34

> Occasionally during rerouting, the SDK will return a maneuver that's too close to the user's current location and can lead to a missed turn and frequent + repeated re-routing.

**Comment by 1ec5** [comment]
On the client side, we should incorporate dead reckoning into the Directions API request: when we determine that rerouting is needed, we should create a request based on the predicted location x seconds in the future. This will increase the likelihood that the response is suitable for the user at the time the client receives it. This approach would require us to make some assumptions about the combined latency of the connection and API, but we can start with the knowledge that location updates never come more than once a second on iOS.

**Comment by ericrwolfe** [comment]
This issue seems to be fixed with the current user bearing added to the directions requests.

**Comment by 1ec5** [comment]
Are you sure? We haven’t changed anything that would affect the abruptness of a new route since this issue was filed. Note that the issue wasn’t only about U-turns but any turn at all.

Incidentally, we ran into a similar consideration in https://github.com/mapbox/mapbox-navigation-ios/pull/346#discussion_r126294608.
