### ISSUE TITLE
iOS 13 keyboard issue

### ISSUE THREAD

**Issue by daniel-ioan-suia** [mapbox/mapbox-navigation-ios#2227]
**Mapbox Navigation SDK version: 0.34.0**
After we display MBNavigationViewController something happens with the keyboard. It will not display anymore properly but only animate weirdly for 1 sec from top of screen down (~300points) and up again offscreen. Our UITextViews remain first responders but can't be used anymore.

Tried with latest release, 0.37.0.
Also I removed other 3rd party libs to isolate the issue.
This happens only on iOS 13 betas.

**Comment by daniel-ioan-suia** [comment]
<img width="574" alt="Screenshot 2019-09-09 at 10 38 57" src="https://user-images.githubusercontent.com/28481489/64516073-18b3d980-d2ee-11e9-8e16-c0b7265940f0.png">

**Comment by daniel-ioan-suia** [comment]
> any update on this issue ??

In my case I tried with IQKeyboard removed from project... but no luck

**Comment by hactar** [comment]
Seeing the same issue in our project.

**Comment by hactar** [comment]
Did some further investigation and once you add the RouteMapViewController to the view hierarchy, the keyboard breaks - even if you remove the controller from the view hierarchy again, which is especially weird and annoying - once a user navs, his keyboard is broken within the app.

The view debugger also gets a new entry once a RouteMapViewController as part of the hierarchy:

<img width="446" alt="Screenshot 2019-09-19 at 13 49 28" src="https://user-images.githubusercontent.com/645674/65241814-d73cde80-dae4-11e9-9f33-e4e05e313e34.png">

Still have no idea how to fix it - removing RouteMapViewController's keyboard code does not help. Maybe the other layout issues (also in the RouteMapViewController) are causing this?

Tested on Xcode iPhone Simulator (iPhone Xr, 13.0)

**Comment by mobileappdeveloper2019** [comment]
Yes I am facing the same issue kindly let me know when you guys fix this issue

**Comment by hactar** [comment]
Alright this one is a weird one, but I've found a workaround for it.

The issue is being caused by the StyleManager - why I don't exactly know, we have a release to ship and I can't investigate further. Interestingly even if you just init a NavigationViewController and never add it to the view hierarchy the issue still occurs.

If you change the StyleManagerDelegate in the NavigationViewController 
https://github.com/mapbox/mapbox-navigation-ios/blob/4e2197ad98e3e89a82366368355692c895a2ca78/MapboxNavigation/NavigationViewController.swift#L597

to always return nil, the problem goes away. You will probably lose automatic style switching at night, but we don't need that anyway.

The reason persists even if you completely remove the NavigationViewController from the view hierarchy because of a second bug: The style manager self retains itself here: https://github.com/mapbox/mapbox-navigation-ios/blob/0fcaf83b1e5b2dbfba739ba23986bbcecb111914/MapboxNavigation/StyleManager.swift#L115 
The cancel that would release the retain is in the deinit method itself here https://github.com/mapbox/mapbox-navigation-ios/blob/0fcaf83b1e5b2dbfba739ba23986bbcecb111914/MapboxNavigation/StyleManager.swift#L85

and so is never called.

Hope this provides the clever people at mapbox to properly fix the issue - hope you other devs can use the workaround for now...

**Comment by daniel-ioan-suia** [comment]
Solved in my case by updating everything (XCode 11 and MapBox libs) and by removing IQKeyboard from proj :)

**Comment by farismhmd1** [comment]
i had the same issue with mapbox. i fixed it.
 Thanks @hactar

**Comment by dawidvdh** [comment]
Currently have the same issue but only when presenting another modal, specifically presenting the intercom interface after presenting the NavigationView. Is there any solution or work around for this? I have tried:

```
extension MapboxNavigation: StyleManagerDelegate {
    func location(for styleManager: StyleManager) -> CLLocation? {
        return nil
    }
}
```

As suggested above with no luck.
