### ISSUE TITLE
Navigation user puck arrow is incorrect when we zoom in to map and resume

### ISSUE THREAD

**Issue by ThiyagarajanShivSankaran** [mapbox/mapbox-navigation-ios#2242]
We have noticed that the user puck arrow keeps jumping around and it does not move consistently while traveling from one place to another. 

Also, If we zoom in to map and click on resume then the arrow anchor is at incorrect location.

Please refer the attached video for more. 

[https://www.dropbox.com/s/177xz3ek3ikjxw7/Navigation%20Arrow%20Issue.mov?dl=0](url)

**Mapbox Navigation SDK version:** v0.37.0
**Device/simulator models:** iPhone, iPad
**Xcode version:** 10.2

**Comment by noway** [comment]
We've got the same issue!! I think it started happening after this got released:

```
Setting MGLMapView.contentInset now moves the map’s focal point to the center of the content frame after insetting. (#14664)
```

see https://github.com/mapbox/mapbox-gl-native/releases/tag/ios-v5.1.0

Any word around

**Comment by noway** [comment]
This is how the puck looks most of the time:

![63000144-1db17480-be79-11e9-95ec-e6b9e57c695b](https://user-images.githubusercontent.com/2031472/65685235-a7c63d00-e0b5-11e9-943a-5d6b67f0f7c1.png)

This is a pretty major issue for our app. We used to stick to mapbox ios sdk 5.0.0 to avoid the issue alltogether, but unable to do so anymore because it doesn't compile with Xcode 11.0

**Comment by 1ec5** [comment]
Tracking this issue in #2145 and #2211.
