### ISSUE TITLE
Permitted background task scheduler identifiers missing

### ISSUE THREAD

**Issue by HoereeBauke** [mapbox/mapbox-navigation-ios#2261]
Hi,
Today I wanted to submit my application builded on Mapbox Core, Mapbox Maps, Mapbox Directions, Mapbox Navigation, etc. . Sadly enough App Store Connect denies my upload every time becouse of the following error:

![image](https://user-images.githubusercontent.com/29101208/67496223-5ee5b200-f67c-11e9-80ff-00db16037b09.png)

To make the SDK work, the documents said to enable the following background modes:
- App plays audio or streams audio/video using AirPlay
- App registers for location updates
- App downloads content in response to push notifications

From now on in IOS13 Apple expects you to provide the identifiers for those modes. Only problem, I can't find them anywhere.

Can someone help me with this?

### Steps to reproduce

 1. Implement Mapbox SDK, Directions SDK, Navigation SDK, ...
 2. Enable the background modes: App plays audio or streams audio/video using AirPlay, App registers for location updates, App downloads content in response to push notifications
 3. Try to archive and publish the app to App Store Connect

### Expected behavior

Completed the identifiers for the backgroundtask in info.plist that the app can archive and build to App Store Connect without any problem

### Actual behavior

Localy the app runs without it, but when you want to upload it to App Store Connect, it requests those identifiers. Without those identifiers in info.plist it won't upload.

### Configuration

**Mapbox SDK versions: pod 'MapboxNavigation', '~> 0.38.0' ** 
**iOS/macOS versions: iOS 13.1.3 (17A878) ** 
**Device/simulator models: Iphone XS Max iOS 13.1.3 (17A878) **
**Xcode version: Version 11.0 (11A420a) **

**Comment by 1ec5** [comment]
> From now on in IOS13 Apple expects you to provide the identifiers for those modes. Only problem, I can't find them anywhere.

This is what the navigation SDK documentation refers to:

1. In the left sidebar of Xcode, go to the 📁 Project navigator (first tab) and click on the roaded.xcodeproj item at the top to open the project editor.
1. At the top of the project editor, switch to the target to “roaded” (see “Example” in the screenshot below) and the Signing & Capabilities tab.
   <img width="446" alt="capabilities" src="https://user-images.githubusercontent.com/1231218/67532522-593b9c80-f67b-11e9-9e33-0a9c0383269f.png">
1. Check the “Audio, AirPlay, and Picture in Picture” and “Location updates” boxes. These capabilities are required by the navigation SDK. If you use certain other functionality in your application, such as background fetch, you may need to check additional boxes.

It sounds like you’ve already performed these steps the more manual way by editing the Info.plist file. The error you’re seeing refers to the `processing` value, which corresponds to “Background processing” in the Signing & Capabilities tab or to “App processes data in the background” in Info.plist. This capability would only be required if you’re using background tasks in your application, but none of the libraries you’ve listed above require background tasks, so it may be due to your own code or another third-party library. [This guide](https://developer.apple.com/documentation/backgroundtasks/bgtaskscheduler) shows how to set the required background task identifiers for your application.
