### ISSUE TITLE
Replace voice controller inheritance with SpeechController registry

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#2268]
MapboxVoiceController and RouteVoiceController have an awkward relationship. RouteVoiceController handles AVSpeechSynthesizer, while MapboxVoiceController handles the Voice API and falls back to AVSpeechSynthesizer by calling superclass method implementations.

We’re encountering a lot of awkwardness in #2230 trying to formalize error states. If a developer wants to integrate with a third-party text-to-speech engine or supply their own audio assets, they have to subclass one of these classes, and error handling gets even weirder.

This functionality should rely on composition rather than inheritance. A single SpeechController class should take the place of these voice controllers. It should own a registry of speech synthesizers. A SpeechSynthesizing protocol would specify methods like `prefetch`, `play`, `duck`, etc.

Supersedes #2131.

/cc @mapbox/navigation-ios

**Comment by 1ec5** [comment]
Per #2131, we should make sure every SpeechSynthesizing implementation respects `NavigationSettings.voiceVolume`.

**Comment by Udumft** [comment]
Hey.
Can somebody shed some light on this method?
https://github.com/mapbox/mapbox-navigation-ios/blob/9d78861e818e5769e4ea4ff13ec4d568d3605652/MapboxNavigation/RouteVoiceController.swift#L26-L47

I don't quite understand it's purpose. As I see, it's result is used for `AVSpeechUtterance` initialization, but actual text is equal it's `SpokenInstruction.text` (except the type, of course). So, what is this method for? Are there any corner cases when these texts are not equal?

**Comment by 1ec5** [comment]
The return value of `SpokenInstruction.attributedText(for:)` generally contains the same text as the receiver, except when the associated step has a `phoneticNames` property. In that case, any occurrence of the road name in the text is attributed with the `phoneticNames` value.

`phoneticNames` contains an [IPA phonetic transcription](https://wiki.openstreetmap.org/wiki/Key:name:pronunciation) of the road name, for cases where the road’s pronunciation is unintuitive. Normally, the SSML text is marked up with the IPA transcription and the Voice API (powered by Amazon Polly) can pronounce that transcription. However, AVSpeechSynthesizer doesn’t support SSML, so we rely on this attribute instead.

**Comment by Udumft** [comment]
In this case there is a problem.
https://github.com/mapbox/mapbox-navigation-ios/blob/9d78861e818e5769e4ea4ff13ec4d568d3605652/MapboxNavigation/RouteVoiceController.swift#L326-L332
This method is designed to allow user to manipulate instruction contents before it is vocalized, but since `SpokenInstruction. attributedText` uses data from instruction itself + `RouteLegProgress`, user may edit instruction so that it becomes inappropriate for AVSpeechSynthesizer.
The problem here is that part of the vocalized text is stored in `RouteLegProgress` and another part comes from `SpokenInstruction`, while only latter  one is customizable by User

**Comment by 1ec5** [comment]
Fixed in #2348.
