### ISSUE TITLE
Mapbox stop navigating(re-routing) when we add it as subview.

### ISSUE THREAD

**Issue by Priyanka-Vispute** [mapbox/mapbox-navigation-ios#2292]
Hello,

I want to add NavigationViewController(Mapbox) as subview in my ViewController, but when i add it using below code snippet its navigation stop working and the arrow does not move:

**let navigationVC = NavigationViewController(for: route, options: nil)
  navigationVC.delegate = self as? NavigationViewControllerDelegate
  navigationVC.view.frame = CGRect(x: 0, y: 0, width: self.mapView.frame.width, height: 
  self.mapView.frame.height)
  self.mapView.addSubview(navigationVC.view)**
          
Whereas if i presentNavigationViewController(Mapbox) as fullscreen the navigation works smoothly with the navigation arrow moving Following is the snippet:

  **let navigationVC = NavigationViewController(for: route, options: nil)
  navigationVC.delegate = self as? NavigationViewControllerDelegate
  self.present(navigationVC, animated: false, completion: nil)**
           
  

Could you please advice me on how to add the mapbox as a "subview" to my ViewController with navigation arrow navigating(moving) properly.

Thanks,

Priyanka

**Comment by 1ec5** [comment]
Adding NavigationViewController’s view to the view hierarchy isn’t enough, because most of the functionality lives in the controller, which needs to be added to the view controller responder chain. [This example](https://docs.mapbox.com/ios/navigation/examples/embedded-navigation/) calls `didMove(to:)` to accomplish that.

But just checking: `mapView` is just a container view, right? There’s no need to add NavigationViewController’s view to an MGLMapView or NavigationMapView, because it already comes with one inside.
