### ISSUE TITLE
Multiple commands produce 

### ISSUE THREAD

**Issue by Jackyaung** [mapbox/mapbox-navigation-ios#2309]
I am facing a problem, it looks like there is something wrong with use_framework.

error is : 

Multiple commands produce '/Users/yang/Library/Developer/Xcode/DerivedData/testProject-entzzxkbyxurfndalekjkdnhuojm/Build/Products/Debug-iphonesimulator/testProject.app/Assets.car':
1) Target 'testProject' (project 'testProject') has compile command with input '/Users/yang/Desktop/test/testProject/ios/testProject/Images.xcassets'
2) That command depends on command in Target 'testProject' (project 'testProject'): script phase “[CP] Copy Pods Resources”

my react navtive version is 0.61.5
MapboxNavigation version : 0.38.1

![image](https://user-images.githubusercontent.com/16591529/72274600-cb919c80-362c-11ea-93b7-1a2a6d333c85.png)

I tried to add use_frameworks in the cocoapod, with use_frameworks, the mapbox is fine, but my other frameworks are messed up with using it. Any workaround?

**Comment by 1ec5** [comment]
The navigation SDK does require `use_frameworks!` (as does the map SDK as of v5.6.0). I don’t know of a workaround specific to the navigation SDK. However, the inability to use static libraries and dynamic frameworks in the same application is a known limitation of CocoaPods: CocoaPods/CocoaPods#3839. Since it seems to be React Native libraries that are requiring your application to avoid frameworks, perhaps there’s a workaround out there to package React Native dependencies differently somehow?

**Comment by 1ec5** [comment]
#1017 tracks making this SDK available as a static framework via CocoaPods and/or Carthage. However, there are many blockers to doing so, particularly the map SDK dependency.

**Comment by deanag412** [comment]
this is being used to hack my phone, i will turn u in for code of conduct, local law enforcment invoved

**Comment by 1ec5** [comment]
@deanag412, please contact [Mapbox Support](https://support.mapbox.com/) with any concerns you have. Thank you.

**Comment by sk92129** [comment]
Please re-open this issue.  I just created a new RN project with the intentions to integrate mapbox navigation.
As soon as I add the mapbox npm, run pod install, then when I try to build via command line or xcode, I see this issue.
