### ISSUE TITLE
MapBox direction API issue: Returns invalid route for 'traffic' profile

### ISSUE THREAD

**Issue by arshadtp** [mapbox/mapbox-navigation-ios#2334]
**Data issue:**

***Source***: -117.752849,34.373231
***Destination***: -118.2484,34.1423

Try traffic, driving profile with playground https://docs.mapbox.com/playground/directions/ and see the routes plotted. If traffic is selected it returns a route that stops Miles away from the actual destination and it has more travel time and distance than the route with driving profile.

Assume in this area Mapbox data is not accurate. Please see the issue I raised https://github.com/mapbox/mapbox-navigation-ios/issues/2333 also.

**Comment by 1ec5** [comment]
Hi, thanks for your report! This repository is specific to the iOS navigation SDK. In general, if there’s an issue with the Directions API regardless of the platform, you’re more likely to receive a prompt and knowledgeable response by contacting [Mapbox’s technical support team](https://support.mapbox.com/hc/en-us). I’ll give it a shot though.

If I plug the source and destination above into the Directions API, the mapbox/driving and mapbox/driving-traffic profiles both return routes that end [in this parking lot along East Colorado Street](https://www.openstreetmap.org/way/580716341) in Glendale. However, as you’ve discovered, the two profiles start out at very different locations. I think the issue is in one of the routing engines that power the Directions API, rather than the OpenStreetMap data that the API uses.

The source waypoint you’ve provided appears to be _every so slightly_ to the east of [this swing gate](https://www.openstreetmap.org/node/123267014) along Highway&nbsp;2. The swing gate lacks an `access` tag, so routers are supposed to assume it’s passable. The driving profile correctly routes right past the gate. However, the OSRM-powered driving-traffic profile is snapping the waypoint all the way to [this unpaved forest service road](https://www.openstreetmap.org/way/300062347). It only snaps that far when the source and destination straddle this gate.

At first I thought the issue is that the car Lua profile [doesn’t whitelist `barrier=swing_gate`](https://github.com/Project-OSRM/osrm-backend/blob/15f0ca8ddaa35c5b4d93c25afa72e81e1fb40c3e/profiles/car.lua#L54-L65), as described in Project-OSRM/osrm-backend#4689. However, I noticed that the OSRM-powered [FOSSGIS Routing Service](https://www.openstreetmap.org/directions?engine=fossgis_osrm_foot&route=34.37339%2C-117.75208%3B34.37343%2C-117.75443#map=17/34.37364/-117.75330) has no problem routing past that gate, and I don’t see any differences in [its car profile](https://github.com/mapbox/directions-processing/blob/222889e2e5969bbed1718a9912d088eb107d0c0b/profiles/car.lua#L58-L68).

<img src="https://user-images.githubusercontent.com/1231218/73900547-f4c8d580-4844-11ea-81a6-8e6d6acb6415.png" alt="fossgis" width="433">

If this issue is blocking your project, I’d still suggest writing into support so the team can potentially keep you posted on any fixes that happen on the backend.

/cc @mapbox/directions-traffic-and-data
