### ISSUE TITLE
Custom map style makes current road name label too tall, route shield too big

### ISSUE THREAD

**Issue by JThramer** [mapbox/mapbox-navigation-ios#2355]
When using a custom style, the way name can apparently become enlarged, which is undesirable.

Investigate and fix.

/cc @mapbox/navigation-ios

**Comment by 1ec5** [comment]
There’s an issue with the navigation SDK’s integration with custom styles built using style components in Studio.

## Background

Here’s how the current road name feature works: in response to each user location update, the navigation SDK queries the currently visible vector tiles for the features at the coordinate at the current user location. It figures out which of the returned features is the road corresponding to the road that the user is on, then fashions a label with a name and shield image based on that feature’s properties.

The name comes from the feature’s `{name}` property, while the shield image is the style image (sprite) with a name in the format `{shield}-{reflen}`, based on the `{shield}` and `{reflen}` properties. The image and name are placed into an attributed string, then that attributed string goes into a UILabel for display.

## Diagnosis

Shield icons in the Navigation Guidance Day v4 style’s sprite sheet are sized for display:

<img src="https://user-images.githubusercontent.com/1231218/78821841-f6229580-798e-11ea-9f4f-3bc51fa6f6ee.png" width="471" alt="navigation-guidance-day-v4">

By contrast, shield icons in a custom style’s sprite sheet are much larger:

<img src="https://user-images.githubusercontent.com/1231218/78821895-0cc8ec80-798f-11ea-93c4-70a459f55e97.png" width="986" alt="custom">

At the original scale, the icons in the custom style’s sprite sheet would be too large to comfortably display in the label. On the map, however, the icons appear roughly the same size because of the `icon-size` property in the style JSON:

* In the custom style, the `road-number-shield-navigation` layer has `icon-size` set to an exponential interpolation expression with stops at 0.5 at z13 and at 1 at z22.
* In Navigation Guidance Day v4, the `road-shields-white` and `road-shields-black` layers have `icon-size` set to a function (interpreted as a linear interpolation expression) with stops at 0.75 at z6 and 1 at z11.

#1576 assumes the style image is at full size and can be displayed without any downscaling. This is apparently no longer the case when it comes to styles created in Studio, now that style components have landed.

## Affected customers

Any customer who creates a custom map style in Studio is affected. More likely than not, a customer who develops against the iOS navigation SDK will choose the Navigation template, which comes with these jumbo sprites by default.

Customers who are content with the v4 navigation styles are unaffected, because the sprites are the right size to begin with.

## Next steps

As a failsafe, [`RoadNameLabelAttachment.getter:compositeImage`](https://github.com/mapbox/mapbox-navigation-ios/blob/441ffc334e6a17b213914600b9705e5ebe8c70d9/MapboxNavigation/InstructionPresenter.swift#L274) should constrain the image size when calling `UIImage.insert(text:color:font:atPoint:scale:)` to something more reasonable, perhaps 1.2 times the attributed string’s paragraph style’s line height.
