### ISSUE TITLE
Optimization route in ios

### ISSUE THREAD

**Issue by andfs** [mapbox/mapbox-navigation-ios#2367]
How is the right way to use optimization api to generate navigation routes in ios? Can someone provide an example?

**Comment by emilefleming** [comment]
First make a separate call to the optimization API to retrieve the optimized order, then pass those in order as waypoints to the navigation service when requesting directions.

**Comment by andfs** [comment]
@emilefleming I tried that but the waypoins in response are in the same order that I sent to the API. The route come in trip object, but it's an array of several points or a polyline

**Comment by 1ec5** [comment]
Given the similarities in the request format between the Directions and Optimization APIs, you can most likely make a successful request by subclassing the `Directions` class and overriding `url(forCalculating:httpMethod:)` to replace `/directions/v5` with `/optimized-trips/v1` in the URL. (Ideally it would be even easier, but the `abridgedPath` property is internal for some reason and not overrideable.) If you need to specify any Optimization API–specific parameters, you can subclass `RouteOptions`, overriding the `urlQueryItems` property to add those parameters.

Where it gets trickier is parsing the response. The response is designed to look quite like a Directions API response, but instead of a `routes` array of Route objects, there’s a `trips` array of Trip objects. This library doesn’t know how to parse Trip objects, even though they have the same structure as Route objects.

Ideally, you’d be able to take the waypoints and pass them to `Directions.calculate(_:completionHandler:)`, as suggested above. But since the waypoints wind up in the same order as the request – which might be a faulty assumption on the part of this library – a rather roundabout workaround would be to manually perform some of the steps that this library normally performs for you:

1. Call `url(forCalculating:)` to get the request URL.
1. Make the request to this URL yourself using URLSession.
1. Use JSONSerialization to decode the JSON into a Dictionary structure.
1. Rename the `trips` key to `routes` in the dictionary.
1. Use JSONSerialization to reencode the JSON as data.
1. [Make a new JSONDecoder](https://github.com/mapbox/mapbox-directions-swift/blob/c91d3ba051fa67759b905299dad85a163697efcf/Sources/MapboxDirections/Directions.swift#L157-L159) and have it [decode the data](https://github.com/mapbox/mapbox-directions-swift/blob/c91d3ba051fa67759b905299dad85a163697efcf/Sources/MapboxDirections/Directions.swift#L178).

Built-in support for the Optimization API is tracked in mapbox/mapbox-directions-swift#107.

**Comment by andfs** [comment]
@1ec5 thanks for the response. I'll try it at the weekend :)

**Comment by abouroubi** [comment]
Hi @andfs, did you found the solution to this ?

**Comment by andersonfaria-hotmart** [comment]
@abouroubi, unfortunately, no :/

**Comment by 1ec5** [comment]
Closing in favor of mapbox/mapbox-directions-swift#107..
