### ISSUE TITLE
Feature request : Pause in side by side navigation.

### ISSUE THREAD

**Issue by vishal-iosdeveloper** [mapbox/mapbox-navigation-ios#2388]
It'll be great if we can pause side by side navigation & resume when we need.

**Comment by Udumft** [comment]
Hello, @vishal-iosdeveloper ! 
During turn-by-turn navigation user may stop at any time and then resume walking/driving whenever he wants, that is allowed with current implementation. 
If user closes the app mid-route and then re-opens it, we cannot guarantee to resume where he left off because user location or route conditions could change during the "pause", which may result in changing the route too. At this use case it is preferred to just request a new route.
Did you mean something else? Could you please provide more details or an example of what you mean by "pause navigation"?

**Comment by vishal-iosdeveloper** [comment]
I want to give Pause button in side by side navigation.
Here is a real time scenario :
- If any user wants to go from city A to city B.
- In Between his journey,  He went to petrol pump.
- User wants to "Pause" side by side navigation during fuel fill up.
- After fuel fill up, user will press "Resume" button as he will continue his journey.

I hope you will get from this context.
I don't want to resume activity after app close.
I just want to "Pause" side by side navigation in such scenarios.

**Comment by Udumft** [comment]
To see if I get it right: user want's to pause the navigation in order to stop updating his location and thus avoid re-routings, voice instructions, and save extra bit of battery while navigation updates are not needed?

Indeed, such feature is not implemented at the moment and is not planned, but in the meantime you can take a look at these [start/stop](https://github.com/mapbox/mapbox-navigation-ios/blob/master/MapboxCoreNavigation/NavigationService.swift#L309-L340) methods as a starting point to implement your own `NavigationService` to pause/resume.

Anyway, thank you for the suggestion!
