### ISSUE TITLE
Route selection while callout view is open - bug

### ISSUE THREAD

**Issue by MarcoCarnevali** [mapbox/mapbox-navigation-ios#2392]
Mapbox Navigation SDK version: 0.39.1
Mapbox Navigation Native SDK version: 6.2.1

I have a NavigationMapView where I display multiple route choices at once. I also have a marker with a callout always displayed and not dismissible while panning. When I tap to select an alternative route, the callout dismiss without selecting the route. With the callout dismissed I can now select the route. 

I have `dismissesAutomatically: Bool = false` on the custom callout view. The right behavior would be to keep the callout visible and select the route at the same time.

**Comment by Udumft** [comment]
Hello, @MarcoCarnevali ! The doc for `MGLCalloutView.dismissesAutomatically` is next:
```
/**
 A Boolean value indicating whether the callout view should be dismissed automatically
 when the map view’s viewport changes. Note that a single tap on the map view
 still dismisses the callout view regardless of the value of this property.
 The callout view will be dismissed if this optional property is unimplemented.
 */
@property (nonatomic, readonly, assign) BOOL dismissesAutomatically;
```
In other words - this property controls if the callout will be closed when map is panned/zoomed/etc. but tap on a map view will always be captured by a callout and close it.
And this is what happens in your case: while callout is open, tapping on alternative route will not select it, but instead, the tap will be handled by a callout and close it. This is correct behavior.

Maybe [Annotation View](https://docs.mapbox.com/ios/maps/examples/annotation-views/) is something that will fit your use case instead of callouts?
