### ISSUE TITLE
Updating Carthage libraries fails on binary-only MapboxAccounts

### ISSUE THREAD

**Issue by kohlab** [mapbox/mapbox-navigation-ios#2467]
**Mapbox Navigation SDK version:** 0.40.0

As per the README, I downloaded a fresh .zip of the project.
The carthage update failed as follows:

```
dylan@Moe mapbox-navigation-ios-master % carthage update --platform ios
*** Cloning SnappyShrimp
*** Cloning turf-swift
*** Cloning OHHTTPStubs
*** Downloading binary-only framework Mapbox-iOS-SDK at "https://www.mapbox.com/ios-sdk/Mapbox-iOS-SDK.json"
*** Cloning MapboxGeocoder.swift
*** Cloning Quick
*** Cloning Cedar
*** Downloading binary-only framework MapboxAccounts at "https://www.mapbox.com/ios-sdk/MapboxAccounts.json"
No available version for binary "https://www.mapbox.com/ios-sdk/MapboxAccounts.json" satisfies the requirement: ~> 2.3.0

```

**Comment by kohlab** [comment]
1. Changing the first line of the Cartfile to: 

`binary "https://www.mapbox.com/ios-sdk/MapboxAccounts.json" ~> 2.2`

makes the error go away. 

2. The README should probably also call for running:

`carthage update --platform ios --no-use-binaries`

because without the last flag, one may encounter this error:

`	"Incompatible Swift version - framework was built with 4.2.1 (swiftlang-1000.11.42 clang-1000.11.45.1) and the local version is 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53)."`

With these two changes, the Example app builds fine as per the README.

One extra note... It's a bit confusing that anytime one builds the example, the URL `https://account.mapbox.com/access-tokens/` is launched, even when the token is already set in Info.plist.

**Comment by Udumft** [comment]
Hello!

> No available version for binary "https://www.mapbox.com/ios-sdk/MapboxAccounts.json" satisfies the requirement: ~> 2.3.0

This error message usually means that `Carthage` could not find the specified dependency version. This could happen if such version does not yet exists or, in this case, that `Carthage` might not have updated it's repo. To resolve that I suggest to clean it's cache by deleting folders:
```
rm -rf ~/Library/Caches/carthage ~/Library/Caches/org.carthage.CarthageKit
```
About binary errors mentioned in a comment:  this is the compatibility issue, that happens because sub-dependencies versions are not meant to be updated.

About `Example` build: that is weird. I'd suggest to double check `Examples` section from [README](https://github.com/mapbox/mapbox-navigation-ios/blob/master/README.md). Ensure that `key` is correct, and that you are modifying the correct `Info.plist` file.

**Comment by mattrobmattrob** [comment]
> This error message usually means that Carthage could not find the specified dependency version. This could happen if such version does not yet exists or, in this case, that Carthage might not have updated it's repo. To resolve that I suggest to clean it's cache by deleting folders:

Clearing the Carthage caches fixed my issue with `carthage bootstrap` on `MapboxAccounts` (`2.3.0`). 👍

**Comment by kohlab** [comment]
Thanks, it was indeed a cache clearing and redundancy issue. More detaiil here: https://github.com/mapbox/mapbox-directions-swift/issues/438#issuecomment-660027758
