### ISSUE TITLE
More lenient arrival zones

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-navigation-ios#247]
Problem:  A user is navigating to the mall. They arrive at the mall and begin to park their car in the parking lot. However, since the user did not reach the destination marker (due to it being in the middle of the mall), we reroute them.

Ideas on how to fix:
* If the users uses the geocoder to find a destination, use it's bounding box if available to see if the user is inside the bounding box.
* Use run time styling to see if user is less then x meters away from destination and in inside a parking lot.
* Ask the user `Have you arrived at the mall?` before rerouting when near the destination.

/cc @mapbox/navigation

**Comment by 1ec5** [comment]
> If the users uses the geocoder to find a destination, use it's bounding box if available to see if the user is inside the bounding box.

Using a geofence of some sort would be wonderful, but a bounding box is the crudest kind of geofence. Consider trying to navigate to D.C., which is rotated 45°, so that its bounding box covers much more area than the district itself. (Of course, we’d probably only apply this heuristic to points of interest, not entire cities, but the same consideration applies to smaller features too.)

> Use run time styling to see if user is less then x meters away from destination and in inside a parking lot.

Maybe we should always avoid rerouting while inside a parking lot. This could improve scenarios where the user has to wend their way out of a parking lot to get onto the route line in first place.

**Comment by bsudekum** [comment]
> Maybe we should always avoid rerouting while inside a parking lot. This could improve scenarios where the user has to wend their way out of a parking lot to get onto the route line in first place.

👍, this sounds like a great first move.

**Comment by 1ec5** [comment]
After toying around with #248, I think a better solution would be to continue to reroute while in a parking lot but silence the voice announcements. That addresses the annoyance of hearing instructions when you no longer want them as you find a parking spot. If we’re concerned about omitting meaningful instructions during departure, then we can use a heuristic that only announces the instruction if the first named way along the route has a different name than the old route.

**Comment by ericrwolfe** [comment]
Ticketed out @1ec5's alternative solution to suppress voice announcements after reroutes: #374

**Comment by 1ec5** [comment]
#374 is distinct from what I proposed above, which was to suppress the voice announcements only while inside a parking lot. #382, for example, treads lightly by only suppressing the voice announcements when the resulting first step is over a kilometer long. But that isn’t necessarily the case inside a parking lot. I think #248 gets most of the way toward a solution to this problem, except that it suppresses rerouting entirely instead of only the voice announcements.

**Comment by bsudekum** [comment]
These are good now.
