### ISSUE TITLE
Route and highlighted building are removed after changing style.

### ISSUE THREAD

**Issue by MaximAlien** [mapbox/mapbox-navigation-ios#2545]
After dynamically changing style in `NavigationMapView` current route and highlighted building are getting removed. It is expected that current route and highlighted building remain on `NavigationMapView`. Example:
![output](https://user-images.githubusercontent.com/1496498/90454140-3fa29000-e0a7-11ea-896d-b5c87b2a9dbd.gif)

**Comment by 1ec5** [comment]
> It is expected that current route and highlighted building remain on `NavigationMapView`.

By design, changing the map style blows away any map style customizations, including the route line and highlighted building style layers. RouteMapViewController is currently responsible for restoring the route line and intermediate waypoint layers by calling `show(_:legIndex:)`. We should ensure that it also restores the building layer.

By coincidence, this issue doesn’t affect the final destination waypoint, which is marked by a point annotation, because annotations do persist across style changes. mapbox/mapbox-gl-native#6180 tracks enabling style layers to persist across style changes like annotations do.

**Comment by MaximAlien** [comment]
In scope of this fix I've added style observation for `NavigationMapView` as well. Since `NavigationMapView` can be used independently from `NavigationViewController` fix inside `RouteMapViewController` will not cover all cases. Even though in case if style changes several times all subsequent calls to `highlightBuildings(at:in3D:)` will not perform any further work if layer is already present. Please let me know if you have better ideas or see other edge cases here.

**Comment by 1ec5** [comment]
> Since `NavigationMapView` can be used independently from `NavigationViewController` fix inside `RouteMapViewController` will not cover all cases.

This is also true of the route line and runtime styling in general. I think it would actually be confusing for some runtime styling to persist but not this specific runtime styling customizations. Better for runtime styling to behave consistently, so that the developer knows to call all the relevant runtime styling methods, including `highlightBuildings(at:in3D:)`, in their `MGLMapViewDelegate.mapView(_:didFinishLoading:)`.
