### ISSUE TITLE
Expose current way name during active navigation

### ISSUE THREAD

**Issue by avi-c** [mapbox/mapbox-navigation-ios#2548]
The Nav SDK Example app has client side code in RouteMapViewController that utilizes map feature querying to deduce the current road name that the user is driving on. At present any Nav SDK customer needs to duplicate this code or invent another approach in order to calculate the current road name.

This should be something the SDK provides through the delegate pattern used for other nav updates.

Providing this as an abstraction through the SDK also allows us to swap out the implementation if we want to use a new feature of Nav Native or find a more performant way to calculate the road name.

**Comment by avi-c** [comment]
The newly implemented PassiveLocationManager provides this feature during free drive but we still don't have it during active nav.

**Comment by 1ec5** [comment]
> The Nav SDK Example app has client side code in RouteMapViewController that utilizes map feature querying to deduce the current road name that the user is driving on.

Here’s the implementation. It’s pretty involved.

https://github.com/mapbox/mapbox-navigation-ios/blob/8687f332ab21c7d6c7471a635f11800838c0bb8b/MapboxNavigation/RouteMapViewController.swift#L641-L751

Because it’s part of RouteMapViewController, an application that implements a custom UI is unable to take advantage of this implementation.

This implementation is basically a giant workaround for the lack of reliable road name information in the Directions API response. (The response tells us the name of the road at the beginning of each step but doesn’t reflect any name changes between steps.) Even so, we should be able to expose a generic enough interface that we could swap in a more reliable source of road names in the future without breaking backwards compatibility.

> This should be something the SDK provides through the delegate pattern used for other nav updates.

There is already a `NavigationViewControllerDelegate.navigationViewController(_:roadNameAt:)` method for the application to _provide_ a road name to label, but not one to tell the application what we think is the current road name. In any case, I think this piece of information would fit better in RouteStepProgress. PassiveLocationDataSource exposes it as part of a notification because there isn’t an analogous structure as part of passive navigation.

> The newly implemented PassiveLocationManager provides this feature during free drive but we still don't have it during active nav.

This reflects the fact that, unfortunately, MapboxNavigationNative only provides this information during free driving. If the navigator were to provide this information when a route is set, then we could stash the road name in RouteStepProgress and there would be no need for feature querying.

/cc @mapbox/navnative

**Comment by 1ec5** [comment]
>> The newly implemented PassiveLocationManager provides this feature during free drive but we still don't have it during active nav.
> 
> This reflects the fact that, unfortunately, MapboxNavigationNative only provides this information during free driving. If the navigator were to provide this information when a route is set, then we could stash the road name in RouteStepProgress and there would be no need for feature querying.

If this is still the case, we can fall back to the electronic horizon feature added in #2834, which posts a notification on each location update that contains the current road name and ref, among other information. This would be a shoe-in replacement for feature querying, except that the e-horizon notification does not include enough information to choose a route shield. So we probably would need to retain the feature querying step but use the e-horizon information to more reliably choose from among the feature querying results. That would allow us to remove the gangliest part of the feature querying code.

**Comment by 1ec5** [comment]
#1440 tracks reimplementing the current road name label atop the information provided by PassiveLocationManager and electronic horizon notifications. That work is somewhat orthogonal to making the feature querying logic more reusable, but the two tasks would probably happen in tandem.

**Comment by 1ec5** [comment]
@MaximAlien @ShanMa1991, do we need to expose anything additional so that custom UIs can populate a current road name view as easily as NavigationViewController does?

**Comment by ShanMa1991** [comment]
I think we need to expose the shield related information. Because if we switch to use the Mapbox designed shield, we would deprecate the use of map feature query. If we don't provide the shield information, there won't be useful shield for the road labeling. 
And also right now we have already exposed the road name through Notification in `RouteController` and `PassiveLocationManger`, we'd better also add the road shield to it as well to support the road labeling under passive and active navigation.
