### ISSUE TITLE
Strange abbreviation

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-navigation-ios#256]
![simulator screen shot may 31 2017 11 27 31 am](https://cloud.githubusercontent.com/assets/1058624/26653572/54d3a1f4-4608-11e7-8802-7431deafa22c.png)

/cc @frederoni

**Comment by frederoni** [comment]
This is what I get when trying to reproduce on master:

![test](https://cloud.githubusercontent.com/assets/764476/26678736/4011dc70-46d2-11e7-9ab2-bd8220fe87c2.gif)

We try to set the text to `"SR-1 South\nPacifica\nMission Street"` which would draw it on three lines but we only allow for one line since the distance is set (two lines in your case).

What would the correct string be?
Would replacing [this line](https://github.com/mapbox/mapbox-navigation-ios/blob/master/MapboxNavigation/RouteManeuverViewController.swift#L104) with `step?.destination?.last` be an appropriate fix or do we want the maneuver instruction?

There's a lot of available space, perhaps we could show two lines if we show distance and three lines if we don't show distance?

**Comment by 1ec5** [comment]
The first destination should be shown at least, but it would be nice to show more than one if we can.

@bsudekum's screenshot above also shows `+ Optional("us") 280` – no idea how that happened.

**Comment by bsudekum** [comment]
> @bsudekum's screenshot above also shows + Optional("us") 280 – no idea how that happened.

Disregard, was working on https://github.com/mapbox/mapbox-navigation-ios/issues/193

**Comment by frederoni** [comment]
Join destinations by comma or space instead of line break should be sufficient?

**Comment by 1ec5** [comment]
Either works. A line break is probably easier, right?
