### ISSUE TITLE
Reduced FPS when device is plugged-in

### ISSUE THREAD

**Issue by nsteffens** [mapbox/mapbox-navigation-ios#2609]
https://github.com/mapbox/mapbox-navigation-ios/blob/0fd7fc9d1c084250564f161a806f583291e63ba3/MapboxNavigation/NavigationMapView.swift#L19

This doesn't make sense to me. Can you elaborate why we switch to a low-power mode although we are charging the battery?

**Comment by 1ec5** [comment]
This constant is used here:

https://github.com/mapbox/mapbox-navigation-ios/blob/0fd7fc9d1c084250564f161a806f583291e63ba3/MapboxNavigation/NavigationMapView.swift#L316-L326

To summarize:

* When plugged in, NavigationMapView always caps the frame rate at 30 fps via `FrameIntervalOptions.pluggedInFramesPerSecond`.
* When on battery power, NavigationMapView caps the frame rate at:
   * 60 fps if animating between overview and turn-by-turn modes or near a maneuver via `FrameIntervalOptions.defaultFramesPerSecond`
   * 20 fps otherwise, configurable via `NavigationMapView.minimumFramesPerSecond`

It doesn’t make a whole lot of sense that the frame rate would be variable only on battery power. I think the intent was for the plugged-in behavior to align with the battery behavior except for using 30 fps instead of 20 fps generally. But #935 switched from time intervals to frame rates without inverting the logic.
