### ISSUE TITLE
Cocoapods cannot find MapboxNavigation version 1.0

### ISSUE THREAD

**Issue by ehmjaysee** [mapbox/mapbox-navigation-ios#2654]
Cocoapods install instructions say:

pod 'MapboxNavigation', '~> 1.0'

However running 'pod install' returns this error:

[!] CocoaPods could not find compatible versions for pod "MapboxNavigation":
  In Podfile:
    MapboxNavigation (~> 1.0)

None of your spec sources contain a spec satisfying the dependency: `MapboxNavigation (~> 1.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Updating the repo did not help.

**Comment by 1ec5** [comment]
Unfortunately we ran into a roadblock uploading v1.0.0 to CocoaPods trunk: https://github.com/mapbox/mapbox-navigation-ios/pull/2646#issuecomment-699028278. Until we find a fix and release v1.0.0, please try [the latest release candidate](https://github.com/mapbox/mapbox-navigation-ios/tree/v1.0.0-rc.5#using-cocoapods-1). Thanks for your patience!

**Comment by pacomacman** [comment]
I'm having the same issue wuth the pod repo update failing to locate MapboxNavigation (~> 1.0).

You mention using the release candidate, but this cannot be uploaded to the App Store can it?

**Comment by 1ec5** [comment]
> You mention using the release candidate, but this cannot be uploaded to the App Store can it?

We’re working on getting the release back up early this week. If you plan to upload to the App Store before then, you can use v0.40.0, which has been available for some time and is stable. Otherwise, use the release candidate so you don’t have to make any changes once v1.0.0 comes out. Thanks for your patience!

**Comment by pacomacman** [comment]
> > You mention using the release candidate, but this cannot be uploaded to the App Store can it?
> 
> We’re working on getting the release back up early this week. If you plan to upload to the App Store before then, you can use v0.40.0, which has been available for some time and is stable. Otherwise, use the release candidate so you don’t have to make any changes once v1.0.0 comes out. Thanks for your patience!

Sadly version v0.40.0 does not work alongside MapBox v6.2.0 which is requires to fix the iOS14 stuttering bug. Currently my app is running the new MapBox SDK to fix the stutter, and I've had to disable the navigation options until this is fixed.

**Comment by 1ec5** [comment]
> Sadly version v0.40.0 does not work alongside MapBox v6.2.0 which is requires to fix the iOS14 stuttering bug.

Are you referring to the fix for mapbox/mapbox-gl-native-ios#350 in mapbox/mapbox-gl-native-ios#411? That’s unfortunate, but we’ll have v1.0.0 ready later this week after some additional testing on iOS 14. Between v1.0.0-rc.5 and v1.0.0, there will be no API changes but a few bug fixes:

* Fixed a linker error in Xcode 12 when using CocoaPods: #2662
* Fixed stuttering in the puck on iOS 14 (for a different reason): #2659
* Fixed an issue where the route line overlapped labels and shields if shape annotations had been added to the map view beforehand: #2661

**Comment by pacomacman** [comment]
We did publish a version of our app to the App Store with a link we forgot to remove, when we went anywhere near the directions API  in a release version out app threw an exception. Due to this we had to ensure all links to these rc versions was removed.

**Comment by 1ec5** [comment]
v1.0.0 is now available: https://github.com/mapbox/mapbox-navigation-ios/pull/2646#issuecomment-702469201

**Comment by ehmjaysee** [comment]
Progress. I can now install v1.0.0 without error. However I cannot build for any iOS target other than simulator. I get the error: 

`ld: building for iOS, but linking in dylib file (/Users/mjc/Library/Developer/Xcode/DerivedData/test-eogwsxynjracdvgsbxwkmhvsrfzy/Build/Products/Debug-iphoneos/SciChart.framework/SciChart) built for iOS Simulator, file '/Users/mjc/Library/Developer/Xcode/DerivedData/test-eogwsxynjracdvgsbxwkmhvsrfzy/Build/Products/Debug-iphoneos/SciChart.framework/SciChart' for architecture arm64
`

I will open a separate issue to track this.

**Comment by 1ec5** [comment]
Thanks, following up in #2674.
