### ISSUE TITLE
CarPlay crash on iOS 14 after a navigation session

### ISSUE THREAD

**Issue by bamx23** [mapbox/mapbox-navigation-ios#2655]
**Mapbox Navigation SDK version:** `v1.0.0-rc.5`

https://github.com/mapbox/mapbox-navigation-ios/blob/e810a461d571083ed9682a8d6302bf27815c9415/MapboxNavigation/CarPlayManager.swift#L685

This method is deprecated in iOS 14 in favor of `popToRootTemplate(animated: Bool, completion: ((Bool, Error?) -> Void)? = nil)`.
Without this callback, this and similar template methods might crash with an exception like this: `An error was encountered during a template operation, but no completion block was specified`. This crash happens only if the template method fails and don't a completion block to handle an error. Providing empty completion block for iOS14 will solve crashing, but also will hide the root problem: an error at the line mention above, that happens after navigation session is finished: `No templates were available to be popped`.

**Comment by IodaMikeMapbox** [comment]
The encountered error is "No templates were available to be popped", it can be easily prevented, it might be a hot-fix for a while, because to use those right methods with callbacks we need to restrict minimal xcode version to its beta.
And this hot-fix won't guarantee that there are no other scenarios when the error can occur because of another reason.

**Comment by IodaMikeMapbox** [comment]
The issue can also be reproduced by starting a navigation session from the phone.
