### ISSUE TITLE
UserCourseView is not following route progress on CarPlay on iOS 14.0.

### ISSUE THREAD

**Issue by MaximAlien** [mapbox/mapbox-navigation-ios#2671]
On CarPlay shipped with `iOS 14` UserCourseView is not following route progress correctly during location simulation. 

CarPlay iOS 14 behavior:
![1](https://user-images.githubusercontent.com/1496498/94842133-df09b100-03cf-11eb-8685-d224df4dff1e.gif)

CarPlay iOS 13 behavior:
![2](https://user-images.githubusercontent.com/1496498/94842151-e6c95580-03cf-11eb-8b12-1b20bb7ee08f.gif)

**Comment by 1ec5** [comment]
If I remember correctly, there’s supposed to be a sweeping zooming-in animation at the beginning of either the browsing or navigation activity. It looks as if that zooming animation is occurring but at only 1&nbsp;frame per second, with the frames backing up instead of skipping.

@zugaldia pointed out that mapbox/mapbox-gl-native-ios#411 landed recently. That change is good overall, but I suppose there’s a risk that something exotic like CarPlay could regress as a result.
