### ISSUE TITLE
Outdated link to v0.40.0 API reference

### ISSUE THREAD

**Issue by ShanMa1991** [mapbox/mapbox-navigation-ios#2675]
The [Documentation](https://docs.mapbox.com/archive/ios/navigation/api/0.40.0/) for the Mapbox Navigation SDK iOS is on version 0.40.0, and lacks the PassiveLocationManager. We should update the documentation and add the PassiveLocationManager to it.

/cc @mapbox/navigation-ios

**Comment by 1ec5** [comment]
> The [Documentation](https://docs.mapbox.com/archive/ios/navigation/api/0.40.0/) for the Mapbox Navigation SDK iOS is on version 0.40.0

v0.40.0 doesn’t have PassiveLocationManager; that class was introduced in mapbox/mapbox-navigation-ios#2410 for v1.0.0.

The bug is that https://docs.mapbox.com/ios/api/navigation/ redirects to https://docs.mapbox.com/archive/ios/navigation/api/ and https://docs.mapbox.com/archive/ios/navigation/api/0.40.0/ rather than to https://docs.mapbox.com/ios/navigation/api/1.0.0/.

/cc @mapbox/docs

**Comment by ShanMa1991** [comment]
I see. Thanks for the giving the new link. I found the PassiveLocationManager part here. Should we update the link to the API reference because we've released the v1.0.0 already??

**Comment by 1ec5** [comment]
Yes, the documentation team is working on it.

**Comment by 1ec5** [comment]
https://docs.mapbox.com/ios/api/navigation/ now redirects to https://docs.mapbox.com/ios/navigation/api-reference/, which links to https://docs.mapbox.com/ios/navigation/api/1.0.0/.
