### ISSUE TITLE
Carthage build failed on Catalina 10.15.7 / Xcode 12 (12A709)

### ISSUE THREAD

**Issue by mighty-nyaina** [mapbox/mapbox-navigation-ios#2676]
I am not able to build mapbox-navigation-ios using carthage since I've update my mac. When I try to run carthage update iOS --use-netrc, it show me the following error. I've already try to use --no-use-binaries but nothing changes.

...
*** Building scheme "MapboxSpeech iOS" in MapboxSpeech.xcodeproj
Build Failed
	Task failed with exit code 1:
	/usr/bin/xcrun lipo -create /Users/nyaina/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A7209/mapbox-speech-swift/v1.0.0/Build/Intermediates.noindex/ArchiveIntermediates/MapboxSpeech\ iOS/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/MapboxSpeech.framework/MapboxSpeech /Users/nyaina/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A7209/mapbox-speech-swift/v1.0.0/Build/Products/Release-iphonesimulator/MapboxSpeech.framework/MapboxSpeech -output /Volumes/Macintosh\ Data/WORK/TEST/AndranaTest/Carthage/Build/iOS/MapboxSpeech.framework/MapboxSpeech

**Mapbox Navigation SDK version: v1.0.0**

Please help
Thanks

**Comment by 1ec5** [comment]
This is a known issue with Carthage itself: Carthage/Carthage#3019. As a workaround, use the script in https://github.com/Carthage/Carthage/issues/3019#issuecomment-665136323 instead of invoking `carthage` directly. There’s a copy of the script in https://github.com/mapbox/mapbox-navigation-ios/blob/master/scripts/wcarthage.sh that should also work in Xcode 12.0.1. You’ll need to manually copy that script to your Mac; it isn’t part of the package that Carthage manages.

**Comment by mighty-nyaina** [comment]
@1ec5  After weeks I was able to solve this issue thanks to you. I really appreciate sir, thank you very much

**Comment by 1ec5** [comment]
Glad to hear it helped!
