### ISSUE TITLE
Positioning icon is not highlighted on CarPlay.

### ISSUE THREAD

**Issue by MaximAlien** [mapbox/mapbox-navigation-ios#2681]
**Mapbox Navigation SDK version:** `1.0.0`

Positioning icon is not correctly highlighted on CarPlay. See example:
<img width="971" alt="Screen Shot 2020-10-06 at 12 50 06 PM" src="https://user-images.githubusercontent.com/1496498/95253536-5d50c380-07d3-11eb-8970-34ebb1fdb687.png">

**Comment by ShanMa1991** [comment]
The iOS version prior to 14 display the icon correctly and with the right functionality as below.

![ios12 4](https://user-images.githubusercontent.com/48976398/96193965-33e41600-0efe-11eb-8e05-cbc9d3b50e1a.png)
![ios13 4](https://user-images.githubusercontent.com/48976398/96193968-36467000-0efe-11eb-8229-980cec654c1a.png)

For the iOS 14 version, the icon could not be highlighted. When clicked, it could not send feedback either. This is caused by the icon resolution. Because the ` FeddbackSubtypeViewController.swift`  and `FeddbackSubtypeCollectionViewCell.swift`  has defined the fixed constants of the button view. 

After replace this icon with a smaller one, or simply cropped it. It fixed as below

![croped_ios14](https://user-images.githubusercontent.com/48976398/96194164-a228d880-0efe-11eb-9f51-bc7c0b495757.png)

It could be solved with replacing the .pdf icon with a smaller resolution one.

**Comment by MaximAlien** [comment]
@ShanMa1991, I think it's acceptable to create icon with lower resolution. It might also make sense to talk to original creator of it to understand what's the best way to do that.
