### ISSUE TITLE
Custom turn by turn navigation

### ISSUE THREAD

**Issue by samuelail** [mapbox/mapbox-navigation-ios#2731]
Hello, this isn't really a bug but more like a question. How can I use the turn by turn navigation as a subclass of a uiview, like the way it's done with the MGLMapView .  There are a lot of UI customizations that I need to do that are not possible when using the NavigationViewController.

**Comment by 1ec5** [comment]
If you can’t use NavigationViewController because of extensive customizations, you can use various components such as NavigationMapView, MapboxNavigationService, and SpeechSynthesizer to build your own replacement for it. [CustomViewController](https://github.com/mapbox/mapbox-navigation-ios/blob/6e2f5c91864df723ddc34532a882448e5da0237e/Example/CustomViewController.swift) is not quite polished but hopefully offers some starting points for your research. If you have any further questions, please reach out to the [Mapbox Support](https://support.mapbox.com/) team for more guidance. Thanks for choosing Mapbox, and best of luck with your application!
