### ISSUE TITLE
Update to Swift 4

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-navigation-ios#277]
Probably can keep this on a branch until the fall. Just need to keep it up to date with master.

/cc @frederoni

**Comment by 1ec5** [comment]
We don’t need to undertake the same branching strategy as we did last year in the Swift service libraries. Swift 4 is source-compatible with Swift 3, and there are also `#if` macros for selecting Swift versions (since Swift 3.2).

Are there any UIKit or Core Location changes in iOS 11 that we should account for?

**Comment by bsudekum** [comment]
We did this.
