### ISSUE TITLE
Camera starts out at Null Island and animates to the user's location when starting navigation

### ISSUE THREAD

**Issue by irtemed88** [mapbox/mapbox-navigation-ios#2982]
**Mapbox Navigation SDK version:** 2.0.0-beta.7

Video attached:

### Steps to reproduce

 1. Launch app with user location already acquired
 2. Present instance of `NavigationViewController`
 3. Observe initial animation from Null Island to current location

### Expected behavior
Map initially renders at user's location

### Actual behavior
Map renders at Null Island and animates to current location

https://user-images.githubusercontent.com/630204/117195860-6c204880-adab-11eb-95b1-0cd8a83d3220.mov

**Comment by ShanMa1991** [comment]
After stop a navigation session by closing a simulator, and then  build the Example app again, the center of the map will locate in the sea near Cuba.

**Comment by MaximAlien** [comment]
> Still seen in v2.0.0-beta.15 during initial camera set and when exiting active guidance. The camera will center either at Null Island before correcting to the user or somewhere closer to the user (like 50 miles away).

It's expected that camera is set to Null island right after `MapView` creation. As I mentioned in this [comment](https://github.com/mapbox/mapbox-navigation-ios/issues/2982#issuecomment-848805698), we provide a method in `NavigationViewController`, which will set initial coordinate at the beginning of active-guidance navigation session.

Right after receiving new coordinate update `NavigationCamera` will update camera to that coordinate, but due to Mapbox Maps issue camera animation abruptly ended from time to time. Such issue was fixed in Mapbox Maps `v10.0.0-rc.4`. Here's current behavior:

https://user-images.githubusercontent.com/1496498/127053363-477a11c9-38ce-40cb-bb80-b4967371df08.mp4

@irtemed88, feel free to re-open this ticket if you still experience this issue. Closing this for now.
