### ISSUE TITLE
Route duration annotation styling should use Expressions, not JSON

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#2996]
#2873 implemented runtime styling of route duration annotations by hard-coding JSON-formatted strings, deserializing them as JSON-formatted dictionaries, and using a private map SDK API to pass these raw dictionaries into the style. Instead, we should initialize the map SDK’s type-safe `Expression` type, which is analogous to NSExpression in map SDK v6._x_ but more consistent with the style specification.

https://github.com/mapbox/mapbox-navigation-ios/blob/62b1622b8290b7a974ca9a0a7f39b5f986e5ae8d/Sources/MapboxNavigation/NavigationMapView.swift#L1054-L1064

/cc @mapbox/navigation-ios @avi-c

**Comment by avi-c** [comment]
Agree completely. The issue is that currently there are some properties, such as 'symbol-sort-key', 'icon-anchor', 'text-anchor' and a few more where the iOS expression implementation doesn't support data driven styling, only some fixed constant values that it provides.

Once that is addressed then we should remove any use of private styling in favor of the suggested and officially supported methods.

**Comment by zugaldia** [comment]
> The issue is that currently there are some properties, such as 'symbol-sort-key', 'icon-anchor', 'text-anchor' and a few more where the iOS expression implementation doesn't support data driven styling, only some fixed constant values that it provides.

Is there a Maps SDK ticket tracking this work?

**Comment by 1ec5** [comment]
> The issue is that currently there are some properties, such as 'symbol-sort-key', 'icon-anchor', 'text-anchor' and a few more where the iOS expression implementation doesn't support data driven styling, only some fixed constant values that it provides.

That was mapbox/mapbox-maps-ios#172, which was fixed by mapbox/mapbox-maps-ios#185 in v10.0.0-beta.16. This issue is unblocked.
