### ISSUE TITLE
Slow NavigationView Init Time

### ISSUE THREAD

**Issue by dmiluski** [mapbox/mapbox-navigation-ios#3003]
**Mapbox Navigation SDK version:**

SPM: MapboxNavigation-SDK 2.0.0-beta.8 (Although this was also reproducing in pre 2.xx builds)

### Steps to reproduce

 1. Given button tap, Initialize NavigationViewController, Present
 2. Added before/after date stamps to subtract time difference to see how long init took
 
 Notice lengthy delay between button tap and presentation. Attempted to provide a measure

I attempted to include a measure {} test, but wasn't able to find an easily available route to test init with locally

Ideally this could be included as part of the test infrastructure to ensure quick init times via:

```
/// Break out the route options
let waypoints: [Waypoint] = [
     Placemark.Mocks.appleHQ,
     Placemark.Mocks.mapboxHQ,
     Placemark.Mocks.transamericaBuilding,
]
.map { $0.coordinate }
.compactMap { Waypoint(coordinate: $0) }
        
let routeOptions = NavigationRouteOptions(
     waypoints: waypoints,
     profileIdentifier: .automobileAvoidingTraffic
)

let route = try makeRoute() // Struggled here

measure {
    _ = NavigationViewController(
        for: route,
        routeIndex: 0,
        routeOptions: routeOptions
    )
}
```

Unfortunately I wasn't sure how to mock up route well enough to add the test.

### Comparable SDK Init Performance

Init Performance
NavigationView init Time: 0.768409013748169 (On Simulator)
NavigationView init Time: 1.5921640396118164 (On iPhone 11 Pro)
SafariViewController init Time: 0.0021469593048095703
Apple MKMapView init Time: 0.11390101909637451

### Expected behavior

Init should be very quick, ideally loading resources after init time for fast/responsive UI

### Actual behavior

Interaction delays of > 0.7 seconds due to lengthy init times.

**Comment by jill-cardamon** [comment]
Follow-up to wrap up this ticket:

Initial slow initialization times were fixed with an upgrade to a newer version of the v2 NavSDK. Dane tested this issue on his side as well to ensure NavigationViewController was initialized quickly.

- With NavSDK v2-beta.12, initialization times averaged less than 0.0003 seconds at start-up across devices using iOS 14 and averaged around than 0.000054 seconds after start-up. I did not see initialization times close to the magnitude of 0.7 seconds when using beta12.
- Presenting the NavigationViewController was much slower than initializing it. At start-up, presenting the view controller could be as slow as 0.5 seconds with post-startup times averaging around 0.065 seconds. This step including setting up NavigationService, NavigationCamera, and the VoiceController with setup for NavigationService and VoiceController taking the most time. These processes are run on different threads, so this slow time makes sense. The time gain from putting their execution on the same thread is not worth the instability it might cause.
- When running time performance profiles, the heaviest stack traces were coming from rendering the map. However, no actions were as slow as reported when using beta12. 

_Note: I tested our SDK using our Example app and the examples in our example repo using NavSDK beta.12, and iPhone 8 Plus and iPhone 11 device simulators running iOS 13 and 14._
