### ISSUE TITLE
[Bug] RouterDelegate.router(_:shouldDiscard:) handled incorrectly

### ISSUE THREAD

**Issue by S2Ler** [mapbox/mapbox-navigation-ios#3056]
**Mapbox Navigation SDK version:** "release-v2.0 branch"
https://github.com/mapbox/mapbox-navigation-ios/blob/bb6c0c1d3e69b765aa986a18eb8fa98a775802eb/Sources/MapboxCoreNavigation/RouteController.swift#L247-L252

This code seems to have inverted logic. If `shouldDiscard` returns true, then the discard won't happen. And visa versa.

**Comment by S2Ler** [comment]
I'm having some issues with `RouteControllerTests.testRouteSnappingOvershooting()` test case. If I override the delegate, expected locations become different from the actual.

**Comment by S2Ler** [comment]
The issue is presented in v1.4.0 as well.

**Comment by S2Ler** [comment]
@mapbox/navigation-ios We will need to mention this issue in the beta release notes with emphasis. Not sure if we need a migration guide update, because the fix needs to be deployed to v1 release as well.

**Comment by S2Ler** [comment]
> The issue is presented in v1.4.0 as well.

@1ec5 Given that this is a breaking change. We should probably skip the deploy to v1 version. What do you think?

**Comment by 1ec5** [comment]
Semantic Versioning [allows](https://semver.org/#spec-item-6) a blatant bug to be fixed in a minor or patch release. In some cases, extra care is warranted because someone may be coding around the bug. But in this case, inverting true and false in a “should” method would result in such a dissonant workaround that I think it would be acceptable to fix the bug and document the fix in the release notes. That doesn’t necessarily mean the fix is urgent enough to expedite a patch of v1._x_, but we can include the fix in the next minor or patch release whenever that happens.
