### ISSUE TITLE
When the NavigationMapView updateCourseTracking is called and tracksUserCourse is active the camera does edgePadding not use 

### ISSUE THREAD

**Issue by doozMen** [mapbox/mapbox-navigation-ios#3086]
So when you have a custom bottom banner then whey navigation is active with tracksUserCourse the bottom banners height is not tacking into account, so the users puck can end up behind the bottom banner

I attempted an earlier to fix issue #2923 by using the `NavigationMapView.userAnchorPoint` but that failed. 

### Expected behavior
When the course tracking is update the camera should take edgePadding into account. Like it does in the overview where it does take the bottom banner into account.

### Actual behavior

It does take bottom banner height into account. The user location puck can end up below custom bottom banner then.

**Comment by MaximAlien** [comment]
@doozMen, we do not actively support Navigation SDK for iOS `v1.x` at this point, and since functionality you're using was re-designed in `v2.0.x` we encourage you to upgrade. There is also such Navigation Camera guide for `v2.0.x`: https://docs.mapbox.com/ios/navigation/guides/map-and-camera/navigation-camera/.
