### ISSUE TITLE
Improve idle time management

### ISSUE THREAD

**Issue by S2Ler** [mapbox/mapbox-navigation-ios#3227]
# Problem 

Currently, `NavigationViewController` and `CarPlayManager` changes `UIApplication.shared.isIdleTimerDisabled` in a way that if there are two instances of `NavigationViewController` or `CarPlayManager` disconnects, the actual state of `UIApplication.shared.isIdleTimerDisabled` might end up in inconsistent state. 

Also, `CarPlayManager`s `isIdleTimerDisabled` usage should be revisit so that it doesn't enable idle timer on connect/disconnect. 

# Solution

Use singleton idle timer manager of some kind which will track how many requests to disable/enable timer of various kinds were send and send appropriate values to `UIApplication.shared.isIdleTimerDisabled`. 

Possible places for this management code: 
- `NavigationSettings`
- New `IdleTimerManager` type: the favourable choice, because the case with CarPlay is more complex. 
- Your option. 

cc @mapbox/navigation-ios @1ec5

**Comment by 1ec5** [comment]
A separate singleton would be fine, assuming it’s something internal that the developer wouldn’t need to know about. I think we should also revisit `CarPlayManagerDelegate.carPlayManagerShouldDisableIdleTimer(_:)` and `NavigationViewController.shouldManageApplicationIdleTimer`, because NavigationViewController would have no control over whether that singleton disables the idle time at CarPlayManager’s behest. At a glance, it seems like NavigationSettings would be a natural place to put that feature flag, but it’s in MapboxCoreNavigation. I suppose MapboxNavigation could extend NavigationSettings and use internal global variables to store that singleton class’s UI-related property values.

**Comment by S2Ler** [comment]
Changing to RC due to the fact that it might require a breaking change.

**Comment by S2Ler** [comment]
Drafted POC, please take a look. 

Changed to GA as it seems that we can omit a breaking change.
