### ISSUE TITLE
Allow updating location puck bottom offset

### ISSUE THREAD

**Issue by ericrwolfe** [mapbox/mapbox-navigation-ios#323]
This is an upstream issue in mapbox-gl-native (@1ec5 I can't recall the ticket), but based on the release cycles of mapbox-gl-native, we should consider adding a workaround to the navigation SDK that allows developers to customize the bottom location puck offset while in course tracking. 

This is a big hurdle for implementing custom navigation apps from scratch.

cc @bsudekum

**Comment by 1ec5** [comment]
The map SDK currently provides an option, [`userLocationVerticalAlignment`](https://www.mapbox.com/ios-sdk/api/3.6.0/Classes/MGLMapView.html#/c:objc%28cs%29MGLMapView%28py%29userLocationVerticalAlignment), with [three options](https://www.mapbox.com/ios-sdk/api/3.6.0/Enums/MGLAnnotationVerticalAlignment.html): center (the default), top, and bottom (what the navigation SDK currently uses). It suited our needs at the time, but these days it feels like either the options result in poor placement or that there are too few options.

One fix would be to publicly expose the MGLMapView method that positions the user puck (and thus the point on the screen around which the camera is fixed), allowing a subclass to override the logic, with mapbox/mapbox-gl-native#5302 as a design precedent. This is tracked in https://github.com/mapbox/mapbox-gl-native/issues/6867#issuecomment-310477143.

Before we go down that route, however, is there an opportunity to improve the existing “bottom” vertical alignment? As I understand it, the problem is that the puck positioning code doesn’t account for the map view’s content insets. Is it possible that #6566 exacerbated this problem?

/cc @boundsj

**Comment by 1ec5** [comment]
Once #213 is fixed, it would also be possible to adjust the offset by building some padding into the user location annotation view’s frame.

**Comment by 1ec5** [comment]
> Once #213 is fixed, it would also be possible to adjust the offset by building some padding into the user location annotation view’s frame.

#498 made it possible to customize the user location annotation view. This made it possible to pad the view’s frame to force the view to appear at a different position on screen.

#402, which is close to landing, overhauls the user puck implementation, disabling the solution in #498 but making it much easier to implement the feature proposed here. There are a couple possible designs, either of which can be implemented in short order:

* We could make `NavigationMapView.userCourseViewCenter` public so that the developer can override it with a custom CGPoint. This approach is simple and enables the developer to reposition the puck between location updates, but it assumes the puck’s location is based on fixed values, unlike for instance Apple Maps’s puck, which shifts to either side based on route data.
* We could add a delegate method, `NavigationViewControllerDelegate.navigationViewController(_:mapView:userPointForRouteProgress:)` that polls the delegate for the position upon each location update, providing the route progress as context. This approach requires slightly more application code but enables a more dynamic puck.

**Comment by 1ec5** [comment]
> We could add a delegate method, `NavigationViewControllerDelegate.navigationViewController(_:mapView:userPointForRouteProgress:)` that polls the delegate for the position upon each location update, providing the route progress as context. This approach requires slightly more application code but enables a more dynamic puck.

I wound up implementing a delegate method along these lines as part of #402. It doesn’t have the route progress as an argument, but it’s pretty straightforward to get ahold of the route progress via `navigationViewController.routeController.routeProgress`.
