### ISSUE TITLE
Allow overriding the location puck's location

### ISSUE THREAD

**Issue by ericrwolfe** [mapbox/mapbox-navigation-ios#324]
This is an upstream issue in mapbox-gl-native (@1ec5 I can't recall the ticket), but based on the release cycles of mapbox-gl-native, we should consider adding a workaround to the navigation SDK that allows developers to customize the location used to display the maps location puck while in course tracking mode.

The example app's `CustomViewController` gets around this by disabling the mapView's location and heading updates and overriding it's internal locationManager delegate callback 😬:

```swift
mapView.locationManager(routeController.locationManager, didUpdateLocations: [location])
```

cc @bsudekum

**Comment by 1ec5** [comment]
This is being tracked upstream in mapbox/mapbox-gl-native#6867.

/ref #57 #172

**Comment by ericrwolfe** [comment]
Currently, it's not possible to set up location simulation to override the puck's location like in the example app using just Core Navigation, as the example app makes use of this category on MGLMapView (https://github.com/mapbox/mapbox-navigation-ios/blob/master/MapboxNavigation/MGLMapView%2BMGLNavigationAdditions.h).

**Comment by 1ec5** [comment]
#402 moves that category to the example application proper, since it will no longer be used by the navigation SDK. Even now, we could eliminate the category in favor of `-respondsToSelector:` and `-performSelector:withObject:withObject:`, which would be safer than forward declaration albeit less aesthetically pleasing.

**Comment by 1ec5** [comment]
https://github.com/mapbox/mapbox-navigation-ios/issues/323#issuecomment-322725942 describes a way to precisely customize the location of the user puck on screen that should tide us over until #402 lands.

**Comment by 1ec5** [comment]
#402, which is close to landing, will reimplement course tracking without hackily overriding `-locationManager:didUpdateLocations:`; however, there’s still an MGLMapView+MGLNavigationAdditions.h that hackily overrides `-mapViewDidFinishRenderingFrameFullyRendered:` and redeclares `displayLink` in order to mitigate the power consumption issue in #370.

Note that this ticket only covers the navigation SDK’s own ability to control the geographic location of the user puck. It has no direct impact on developers using this SDK. #323 is about allowing the developer to control the puck’s position on screen.

**Comment by bsudekum** [comment]
Closing now that https://github.com/mapbox/mapbox-navigation-ios/pull/402 is in.
