### ISSUE TITLE
Replace maneuver arrows along the route line

### ISSUE THREAD

**Issue by ericrwolfe** [mapbox/mapbox-navigation-ios#326]
The turn arrows currently implemented in the SDK are both amateur looking and the code is somewhat complex.

Notes from another thread:
> Let's get rid of the line based arrowhead altogether and replace the draw arrowhead with a symbol layer that's just a triangle image that's rotated based on the end bearing of the maneuver. 

> <img width="318" alt="screen shot 2017-06-26 at 9 31 30 am" src="https://user-images.githubusercontent.com/664805/27549877-6225cee6-5a52-11e7-9c2f-9730fa7b6f5f.png">

> For casing, you can have the same triangle image tinted to the casing color, and scaled up slightly.

> Since the arrow extends beyond the maneuver by some distance, possibly curving, the arrow will need `iconRotation` to be set according to the direction of the road at the tip of the arrow’s shaft, not necessarily the maneuver’s heading.

cc @bsudekum @1ec5

**Comment by 1ec5** [comment]
Another benefit of implementing the arrowhead as a point-placed symbol is that it can scale better as the user zooms in and out, since its size is expressed in screen units rather than a physical distance (which GL is currently unable to vary according to zoom level). However, the arrow’s shaft will still appear to contract and expand for the same reason as the current arrowhead.

**Comment by 1ec5** [comment]
Retitled to distinguish the maneuver arrows along the route line from the maneuver icon in the turn banner, which also looks like an arrow most of the time.

**Comment by ericrwolfe** [comment]
Fixed with https://github.com/mapbox/mapbox-navigation-ios/issues/397
