### ISSUE TITLE
[Bug]: localization/internationalization not working?

### ISSUE THREAD

**Issue by DiegoResnik** [mapbox/mapbox-navigation-ios#3445]
### Mapbox Navigation SDK version

2.0 rc4

### Steps to reproduce

following: https://docs.mapbox.com/ios/navigation/guides/localization-and-internationalization/

tried to allow the user to set a locale different than the system.

```
let nav = NavViewController()
let rOptions = NavigationRouteOptions(waypoints: [origin,destination])
.
.
rOptions.locale = Locale(identifier:"he")
.
.
nav.routeOptions = rOptions
```

### Expected behavior

spoken instruction should have been in Hebrew.

### Actual behavior

The instruction were only the name of the streets without any Hebrew.

### Is this a one-time issue or a repeatable issue?

repeatable

**Comment by S2Ler** [comment]
Hello @DiegoResnik,

Unfortunately, the "he" language [isn't supported by Amazon Polly](https://docs.aws.amazon.com/polly/latest/dg/SupportedLanguage.html), that's why localization doesn't work. But, you can use `SystemSpeechSynthesizer` by providing custom `RouteVoiceController` to `NavigationOptions`:

```swift
RouteVoiceController(navigationService: navigationService, speechSynthesizer: SystemSpeechSynthesizer(), accessToken: nil, host: nil)
```
