### ISSUE TITLE
2.0.0-rc.6 CocoaPods integration crash

### ISSUE THREAD

**Issue by azarovalex** [mapbox/mapbox-navigation-ios#3498]
2.0.0-rc.6 CocoaPods podspec pins NavSDK to the specific version of Maps SDK – 10.0.0: [link](https://github.com/mapbox/mapbox-navigation-ios/blob/v2.0.0-rc.6/MapboxNavigation.podspec#L47).

Maps SDK 10.0.0 in turn pins it to the specific version of Events SDK – 1.0.5: [link](https://github.com/mapbox/mapbox-maps-ios/blob/v10.0.0/MapboxMaps.podspec#L26)

Events SDK 1.0.5 has a crash that was fixed only in 1.0.6 release: [link](https://github.com/mapbox/mapbox-events-ios/issues/321)

This means that rc.6 integrated through CocoaPods won't use fixed version of Events SDK.
Ways to solve the problem: 
1. Release a new version of NavSDK
2. Force push rc.6 tag

In the future we don't need to pin our dependencies to specific patch versions to avoid similar problems.

**Comment by JanTG1** [comment]
@azarovalex I am having this exact issue right now. Had to update quickly because iOS 15 broke the SearchUI, this was fixed but in a newer version for which I need the 2.0.0-rc.6 Nav. You say "force pushing rc.6 tag" would solve the issue, but I don't see how / how to force push something. I am already giving cocoa pods the exact tag, however, the installation throws me the exact same errors you describe.

**Comment by MaximAlien** [comment]
Navigation SDK for iOS `v2.0.0 GA` was released, so this ticket can be closed.
