### ISSUE TITLE
[Bug]: SlightLeft-SlightRight lanes doesn't render

### ISSUE THREAD

**Issue by S2Ler** [mapbox/mapbox-navigation-ios#3530]
### Mapbox Navigation SDK version

v2.0.0

### Steps to reproduce

Set route from 1.3054251688045753;103.88307997278685 to 1.309264205529388;103.87483300071494 and start guidance cards Example navigation. One of the guidance cards will have a non-rendered lane. 

### Expected behavior

`LaneIndication.Ranking`
```
▿ Ranking
  ▿ primary : slight left
    - rawValue : 32
  ▿ secondary : Optional<LaneIndication>
    ▿ some : right
      - rawValue : 4
  - tertiary : nil
```

can be rendered

### Actual behavior

Empty lane view

### Is this a one-time issue or a repeatable issue?

repeatable

**Comment by 1ec5** [comment]
> For reference, [this way](https://www.openstreetmap.org/way/746988839) tagged `slight_left;slight_right` is what’s triggering the blank lane.

I believe this was a tagging mistake in OpenStreetMap. In the foreground of the photo below, you can see the intended lane indications ahead of the lane splits. One of the middle lanes has a dual through–right indication. In the background, just past the lane split, there’s an additional row of lane indications, but instead of through and right, the new lanes are marked with arrows pointing slightly to the left and right. The mapper mistook these arrows to be turn lane markings, but in fact the arrows are intended to emphasize the lane split and subsequent fork in the road. After all, if it were actually a dual slight left–slight right lane, the arrows would be conjoined as they are in the foreground. (Please correct me if I’m wrong; I’ve never driven in Singapore, which seems to use pavement markings similar to those in the Vienna Convention.)

[![mountbatten](https://scontent-sjc3-1.xx.fbcdn.net/m1/v/t6/An8JRHmCExLLlTIah_BO0ICIw2lHyrq82r2xY6Vh02IKK8dRz0cuiDdg8QiPf1irmXpGPnAqui_E50vyKx5uAOaaGKbKipNnnEmJWiRgjBhW_pBUhQbSHE0LDOjidmwS7ibqzwy52tuCGZo3EwioC0U?stp=s2048x1152&ccb=10-5&oh=894b3bcfe84e3ae1b52b6c9d35b10f92&oe=618F2DFB&_nc_sid=122ab1)](https://www.mapillary.com/app/?pKey=802802847050020)

In [changeset 113,534,817](https://www.openstreetmap.org/changeset/113534817), I corrected the lane indications to be consistent with those of the preceding and following ways and also split the lanes, since there’s a dashed line down the middle for approximately the length of the way. For good measure, I added `placement` tags and [`connectivity`](https://wiki.openstreetmap.org/wiki/Relation:connectivity) relations, though Valhalla doesn’t currently use those tags for anything.

Even though this particular case turned out to be a tagging mistake, it did uncover a latent bug in the navigation SDK as explained in https://github.com/mapbox/mapbox-navigation-ios/issues/3530#issuecomment-954073684. The SDK should’ve at least fallen back to a left–right icon when encountering a slight left–slight right configuration, which is common on freeways.
