### ISSUE TITLE
Maneuver arrow too short at “pencil tip” segregated intersection

### ISSUE THREAD

**Issue by S2Ler** [mapbox/mapbox-navigation-ios#3589]
### Mapbox Navigation SDK version

v2.0.0

### Steps to reproduce

Go to https://www.openstreetmap.org/#map=19/53.89580/27.55074 location and navigate to "Проспект независимости". Check the turn arrow:
![photo](https://user-images.githubusercontent.com/413986/141458329-11bf569f-4edf-4d68-bbe7-4e156291aa5d.jpg)

### Expected behavior

Arrow steps aside from the line. 

### Actual behavior

The arrow overlaps with the line. 

### Is this a one-time issue or a repeatable issue?

repeatable

**Comment by 1ec5** [comment]
First of all, both улица Свердлова and проспект Независимости are incorrectly mapped as dual carriageways, even though they appear to have no physical separation in the median, just a painted line.

Ignoring that issue, the routing engine considers the maneuver location to be at [the first intersection node](https://www.openstreetmap.org/node/275070064) it encounters. NavigationMapView is designed to extend the arrow 30&nbsp;points before and after the maneuver location (converted to meters based on the current zoom level):

https://github.com/mapbox/mapbox-navigation-ios/blob/6917e3bb281ad70c52f819c85e6af20a61f8c4d4/Sources/MapboxNavigation/NavigationMapView.swift#L233-L238

Ideally, NavigationMapView would extend the arrowhead a little further ahead in this case to ensure that it clears the intersection, but the SDK has no idea that it’s a segregated intersection with a relatively wide median. The Directions API doesn’t provide the coordinates of each of the `highway=traffic_signals` nodes along the route, after all. I suppose we could introduce some heuristic that would extend the arrow even further if it encounters a turn, but this intersection is mapped as a “pencil tip”, dulling the turn angles enough that such a heuristic would have no effect anyways.

/cc @Andygol

**Comment by Andygol** [comment]
> both улица Свердлова and проспект Независимости are incorrectly mapped as dual carriageways, even though they appear to have no physical separation in the median, just a painted line.

The local OSM community has its own vision of how to map roads to travel in every direction, and a physical divider is not always required. For wide roads, the number of lanes on which for traffic in both directions is greater than or equal to 6, in the presence of double continuous markings or a dividing strip, which is indicated by markings and treated as divider, it is allowed to plot each direction of movement on the map in the form of separate ways.

**Comment by 1ec5** [comment]
If you’re aware of a more detailed discussion or description of this local exception, it should be linked somewhere more accessible to software developers, like on [this wiki page](https://wiki.openstreetmap.org/wiki/Dual_carriageway#Exceptions), so that it doesn’t come as a surprise in bug reports. An exception is already mentioned there for super-twos in the U.S., but that’s a situation where there is a median, but it’s paved over.

I’m not sure what the next step would be for this issue. The client doesn’t have a lot of information to go off here.

**Comment by Andygol** [comment]
It is worth noting here that the [mentioned page in wiki OSM](https://wiki.openstreetmap.org/wiki/Dual_carriageway#Exceptions) was created not so long ago (in early 2021) while the community has been adding roads with separate carriageways for a long time. In addition, the examples and recommendations provided are purely US-specific and should be extended by examples and rules from other countries.

**Comment by 1ec5** [comment]
Yes, I think that page is meant to expand on [this longstanding guidance](https://wiki.openstreetmap.org/wiki/Editing_Standards_and_Conventions#Divided_highways), which has been around [since 2015](https://wiki.openstreetmap.org/wiki/Special:Diff/1212577), and probably similar guidance elsewhere. It should definitely be globalized.

**Comment by ve1oxby** [comment]
Just wanted to drop here the solution we've used in TME CN 
![image](https://user-images.githubusercontent.com/51075160/146535762-3d3220d6-6ecc-4256-88d5-e56b36082717.png)
