### ISSUE TITLE
[Bug]: Route line blinks when refresh and reroute

### ISSUE THREAD

**Issue by ShanMa1991** [mapbox/mapbox-navigation-ios#3621]
### Mapbox Navigation SDK version

v2.1.0-rc.2

### Steps to reproduce

1. Set the `RouteControllerProactiveReroutingInterval` to `5` or smaller `3` in Example
2. Start navigation in `basic` mode.

### Expected behavior

The route line doesn't blink

### Actual behavior

The route line blinks.
![refresh](https://user-images.githubusercontent.com/48976398/143946311-97d0b367-f6a1-475c-945f-2eb7a6629893.gif)

This issue is observed after the merge of #3261

### Is this a one-time issue or a repeatable issue?

repeatable

**Comment by ShanMa1991** [comment]
Hi @Udumft would you take a look at this issue ?

**Comment by Udumft** [comment]
Looks like this blink is caused by [overwriting route](https://github.com/mapbox/mapbox-navigation-ios/blob/main/Sources/MapboxCoreNavigation/RouteProgress.swift#L137) during refreshing. Before introducing HybridRouter, it just [updated leg's annotations](https://github.com/mapbox/mapbox-navigation-ios/blob/main/Sources/MapboxCoreNavigation/RouteProgress.swift#L154) but HybridRouter does not return `RefreshedRoute` anymore, so we'll have to allow another way to update it. This will require [such API](https://github.com/mapbox/mapbox-directions-swift/pull/634) on Directions.swift.
