### ISSUE TITLE
Extract text instruction generation from voice controllers

### ISSUE THREAD

**Issue by ericrwolfe** [mapbox/mapbox-navigation-ios#367]
The generation and timing of text instructions for voice announcements should be available in CoreNavigation.

cc @bsudekum @frederoni

**Comment by 1ec5** [comment]
#385 got backed out in #367.

**Comment by 1ec5** [comment]
If understand correctly, this issue tracks moving everything unrelated to speech synthesis to Core Navigation, as #385 attempted to do. It should be unnecessary to go further than that, because the generation of text instructions themselves largely happens in OSRM Text Instructions via RouteStepFormatter, independent of the MapboxNavigation module.

**Comment by ericrwolfe** [comment]
Closed with https://github.com/mapbox/mapbox-navigation-ios/pull/456.
