### ISSUE TITLE
[Bug]: NavigationView fails to correctly display Map and Route

### ISSUE THREAD

**Issue by JanTG1** [mapbox/mapbox-navigation-ios#3787]
### Mapbox Navigation SDK version

2.0.0

### Steps to reproduce

I don't know how to reproduce the problem.

### Expected behavior

When Starting Navigation, not only should the Navigation UI appear, the user should be at the correct location on the map and the route should be correctly displayed.

### Actual behavior

The Route is displayed somewhere in the water (I assume at Long&Lat 1,1). Sometimes it won't correct at all, sometimes it will "redirect" after a few minutes and then start acting correctly (updating user position and displaying the route correctly).

Console keeps printing 
2022-03-12 15:43:18.037201+0100 App[17590:4961328] Failed to convert UIImage
2022-03-12 15:43:18.037321+0100 App[17590:4961328] Location Error when creating location indicator layer: unexpectedType

after printing many other things

See Screenshot as an example (Ignore the black box). The ui being messed up is another issue.

![IMG_AF13E5298965-1](https://user-images.githubusercontent.com/92864392/158022995-b2bf6b6d-f099-4ff8-afc3-e0e6a1eb353f.png)
.

### Is this a one-time issue or a repeatable issue?

repeatable

**Comment by jill-cardamon** [comment]
Thank you for your report! Is this behavior happening during simulation only?

**Comment by MaximAlien** [comment]
@JanTG1, can you share your code snippet that starts `NavigationViewController`? It seems that this issue might be caused by `RouteOptions` usage while creating an instance of `NavigationViewController`. If you can switch to `NavigationRouteOptions` usage instead it might solve your issue. Basic example can be found here: https://github.com/mapbox/mapbox-navigation-ios-examples/blob/main/Navigation-Examples/Examples/Basic.swift.

Also make sure that you're using `RouteOptions.routeShapeFormat = .polyline6`. `polyline5` usage might cause this problem.

**Comment by JanTG1** [comment]
@MaximAlien sorry for forgetting about this issue. It has not happend since, I have since started using NavigationRouteOptions, might have fixed it that way. Closing the issue!
