### ISSUE TITLE
[Bug]: Cannot assign to property: 'route' is a get-only property to NavigationViewController

### ISSUE THREAD

**Issue by nastasiupta** [mapbox/mapbox-navigation-ios#3991]
### Mapbox Navigation SDK version

2.5.1

### Steps to reproduce

1. Trigger rerouting function
`func navigationViewController(_ navigationViewController: NavigationViewController, shouldRerouteFrom location: CLLocation) -> Bool {`

2. Generate a new Route object, using your custom algorithm to (locations from current user location to destination)
3. Assign the new Route object to NavigationViewController
`navigationViewController.navigationService.route = route
Cannot assign to property: 'route' is a get-only property`
On older SDK versions it worked just to assign the new Route object to existing NavigationViewController NavigationService, but with the new SDK version is not working anymore. How can this behavior be achieved again?

### Expected behavior

Just assign the new Route object to NavigationViewController and the SDK is doing it's job. It worked like that before.

### Actual behavior

I get this error right now: Cannot assign to property: 'route' is a get-only property

### Is this a one-time issue or a repeatable issue?

repeatable

**Comment by Udumft** [comment]
Hi! `route` is now a readonly property due to updates to the use an indexed route response as a source of routing information. Route can now be updated by a method call on a router or navigation service as [shown here](https://github.com/mapbox/mapbox-navigation-ios/blob/main/Sources/MapboxNavigation/NavigationViewController.swift#L158-L178).
Also, if you are implementing your own reroute generation method, consider implementing it as a custom `RoutingProvider` as a designed way to do so. You can see [this short example](https://github.com/mapbox/mapbox-navigation-ios-examples/blob/main/Navigation-Examples/Examples/Custom-RoutingProvider.swift) on how to do it.

**Comment by nastasiupta** [comment]
@Udumft As I saw in the exemple you don't use `func navigationViewController(_ navigationViewController: NavigationViewController, shouldRerouteFrom location: CLLocation) -> Bool {`  method. Also, you don't set the delegate for NavigationViewController.
I noticed that the functions from the custom object are not called. Is this because I use the delegate?
In my case I still need the delegate method to update the custom bottom view, using this method `func navigationViewController(_ navigationViewController: NavigationViewController, didUpdate progress: RouteProgress, with location: CLLocation, rawLocation: CLLocation) {`

**Comment by Udumft** [comment]
Linked example illustrates a different approach in case you are looking for overriding a reroute calculation. If you are not - using `updateRoute` will do what you are trying to achieve by attempting to update `route` property.

**Comment by nastasiupta** [comment]
@Udumft 
```
let indexedRouteResponse = IndexedRouteResponse(routeResponse: routingResponse, routeIndex: 0)
navigationViewController.navigationService.router.updateRoute(with: indexedRouteResponse, routeOptions: routeOptions, completion: nil)
```

This should do the trick?
