### ISSUE TITLE
[Bug]: Mapbox designed shield changes its style on both iOS and CarPlay at the same time.

### ISSUE THREAD

**Issue by MaximAlien** [mapbox/mapbox-navigation-ios#4001]
### Mapbox Navigation SDK version

v2.7.0-alpha.1

### Steps to reproduce

1. Open example application on iOS and CarPlay.
2. Request route that contains `GenericRouteShield`s. 
3. Start active navigation.
4. Change appearance in CarPlay settings. 
5. Observe behavior.

### Expected behavior

`GenericRouteShield` style should be changed only on CarPlay.

### Actual behavior

`GenericRouteShield` changes its style on both iOS and CarPlay.

### Is this a one-time issue or a repeatable issue?

repeatable

**Comment by ShanMa1991** [comment]
when CarPlay changes appearance, the `CPSessionConfiguration.contentStyle` changes to trigger CarPlay apply different style type. It will call the `wayNameView.label.updateStyle(styleURI:)` . Because `WayNameLabel` and `InstructionPresenter` are using the `singleton` of `SpriteRepository`. When the `styleURI` is updated, previous style cache will be cleared out, including the Mapbox designed shields. The `InstructionPresenter` need to find new shield image due to the loss, and it could only find the new style one (used by CarPlay).

But because the `SpriteRepository.legacyCache` won’t be cleared which stores generic shields and exit views So they won't be affected if the CarPlay changes appearance.

To fix this issue, `SpriteRepository` should handle different platforms, such as mobile/iPad and CarPlay. So that different platforms won't affect each other on style related cache.
