### ISSUE TITLE
[Bug]:  The latitude and longitude information of the return location of the simulated navigation data is 0, and normal simulation cannot be performed.

### ISSUE THREAD

**Issue by xiaoxin3838438** [mapbox/mapbox-navigation-ios#4174]
### Mapbox Navigation SDK version

2.5.1

### Steps to reproduce

Hello developers:
We re-tested the simulated navigation route in Osaka, Japan, and found that the MapBox simulated navigation did not return data, which caused the navigation to drift, and the interface was abnormal. You can test the address in Osaka, Japan for a simulated test.
There will be no simulated navigation problem with version 1.0, and 2.5.2->2.7.2 will have simulated navigation return data problems.
Thanks!

### Expected behavior

Expect to simulate navigation normally.

### Actual behavior

I uploaded the problem demonstration through video, and the demonstration video is at the following link address.
Demonstration video is what happens

[https://thinkerride.oss-cn-zhangjiakou.aliyuncs.com/10001/20220921/D070E101-D49D-4732-857C-8D5E130B11B3.MP4]（url）
[https://thinkerride.oss-cn-zhangjiakou.aliyuncs.com/10001/20220921/A822306A-6CA7-4F3C-871C-6F23C6388584.MP4]（url）

### Is this a one-time issue or a repeatable issue?

repeatable

**Comment by Udumft** [comment]
Hi @xiaoxin3838438 ! Could you please provide some more details so that we can reproduce and debug this issue?
* What is the last version you are able to reproduce this on?
* How do you run the simulation? Is it a default Example app or you can provide your custom code snippet?
* Is it a MapMatching response you are attempting to drive?
* Is it possible to share the history file or at least Origin and Destination coordinates you use for the request?
* Can you run successful simulation on some other route/conditions, or all of the attempts do not work for you? If you can, what are you doing different on your side?

This would help investigating a lot, thanks!

**Comment by xiaoxin3838438** [comment]
Hello, for the moment, we have avoided this problem by refreshing the navigation progress route. We have banned the official automatic planning agent method and manually implemented the refreshing route in the navigation agent progress method. I will contact you if there is any need in the future
Thank you very much for your reply!
