### ISSUE TITLE
[Bug]: `localizeLabels` doesn't apply without translations

### ISSUE THREAD

**Issue by alahwa** [mapbox/mapbox-navigation-ios#4190]
### Mapbox Navigation SDK version

2.6.0

### Steps to reproduce

Implement localization according to the [documentation](https://docs.mapbox.com/ios/navigation/guides/system-integration/localization-and-internationalization/):
```
navigationMapView.mapView.mapboxMap.onNext(.styleLoaded, handler: { [weak self] _ in
    self?.navigationMapView?.localizeLabels()
})
```

### Expected behavior

Localization should apply according to system language preferences.

### Actual behavior

Localization does not properly apply unless the current system language is also configured in Xcode with a stub localization file. This isn't a feasible solution for our use case, as we have a translation pipeline with several supported languages, and introducing a localization file for every language Mapbox supports isn't possible.

Instead, is there an option to enable language support broadly based on the system language preferences? Why does our app need to be localized for a particular language in order for Mapbox to support it?

### Is this a one-time issue or a repeatable issue?

repeatable

**Comment by 1ec5** [comment]
> Localization should apply according to system language preferences.

Agreed. Specifically, map label localization should respect the Preferred Language Order setting in Settings ‣ General ‣ Language & Region. The issue is that `NavigationMapView.localizeLabels()` is consulting `Locale.nationalizedCurrent`, which is based on the locales into which the application is localized:

https://github.com/mapbox/mapbox-navigation-ios/blob/c0b782925355db1a1406037102632882cbfce21d/Sources/MapboxNavigation/NavigationMapView.swift#L1760-L1761 https://github.com/mapbox/mapbox-navigation-ios/blob/c0b782925355db1a1406037102632882cbfce21d/Sources/MapboxCoreNavigation/Locale.swift#L4-L25

This behavior is appropriate for `Locale.nationalizedCurrent`, which is designed to ensure consistency between the navigation SDK’s UI “chrome” and the rest of the application’s UI. However, it’s inappropriate for “content” displayed within the application that comes from other sources. In the case of a navigation application, map labels would probably be considered content.

This regression was introduced in #3330. The older implementation in #1111 (itself based on [a map SDK implementation](https://github.com/mapbox/mapbox-gl-native-ios/blob/ddf8e35970d1a8a46171bd798bcfa8f22d2760e0/platform/darwin/src/NSExpression%2BMGLAdditions.mm#L1563)) solely relied on `Locale.preferredLanguages`, which corresponds to the user setting (modulo [Mapbox Streets source support](https://docs.mapbox.com/data/tilesets/reference/mapbox-streets-v8/#name-text-and-name_lang-code-text)):

https://github.com/mapbox/mapbox-navigation-ios/blob/c0b782925355db1a1406037102632882cbfce21d/Sources/MapboxNavigation/VectorSource.swift#L59-L67

It should be straightforward to switch over to `Locale.preferredLanguages`. I don’t think it would be considered a backwards-incompatible change, as it would fix unexpected behavior in languages unsupported by the application but leave the behavior unchanged in supported languages.

As a temporary workaround, you can call the map SDK’s `Style.localizeLabels(into:forLayerIds:)` method directly. You can use `Locale.preferredLanguages`, but note that this method throws an error that you’ll need to catch if the Mapbox Streets source doesn’t support the user’s preferred language. The other caveat is that it localizes everything on the map, not only places and POIs but also road names.

Incidentally, `Locale.nationalizedCurrent` is also being used by NavigationRouteOptions to request spoken and visual guidance instructions in the same language as the UI:

https://github.com/mapbox/mapbox-navigation-ios/blob/c0b782925355db1a1406037102632882cbfce21d/Sources/MapboxCoreNavigation/NavigationRouteOptions.swift#L145

This is a tougher call; whether guidance instructions are considered “chrome” or “content” probably depends on the application’s UI design.
