### ISSUE TITLE
[Bug]: Fatal error: Failed to create LayerType from model

### ISSUE THREAD

**Issue by engelzero** [mapbox/mapbox-navigation-ios#4198]
### Mapbox Navigation SDK version

2.7

### Steps to reproduce

Add a 3D navigation puck model and when clicking the alternative route - crashes. 
Throws: Thread 1: Fatal error: Failed to create LayerType from model

### Expected behavior

Should not crash

### Actual behavior

Thread 1: Fatal error: Failed to create LayerType from model

```
    public var allLayerIdentifiers: [LayerInfo] {
        return _styleManager.getStyleLayers().compactMap { info in
            guard let layerType = LayerType(rawValue: info.type) else {
                assertionFailure("Failed to create LayerType from \(info.type)")
                return nil
            }
            return LayerInfo(id: info.id, type: layerType)
        }
    }
```

### Is this a one-time issue or a repeatable issue?

repeatable

**Comment by engelzero** [comment]
@ShanMa1991 @1ec5 - I need the Mapbox senpais

**Comment by engelzero** [comment]
Route switching works fine when 3D model not added - no crash. 
https://user-images.githubusercontent.com/16312538/195530552-cd8787ad-661f-4bad-8856-43d0b4bc05bf.mp4

**Comment by 1ec5** [comment]
Fixed in mapbox/mapbox-maps-ios#1650. Once the fix makes its way into a release, we’ll integrate it into the navigation SDK.

**Comment by engelzero** [comment]
@1ec5 rough eta?

**Comment by 1ec5** [comment]
Hi @engelzero, that fix is upstream in MapboxMaps. Unfortunately I don’t have an ETA for a MapboxMaps release with that fix, but it’s being discussed. In the meantime, you can modify your project to explicitly depend on mapbox/mapbox-maps-ios@b67e0859278ee92b29e4a3aadf0210762b9dfb8d for MapboxMaps as well as MapboxNavigation v2.9.0-beta.4. Once a new MapboxMaps release comes out, remember to remove that redundant MapboxMaps dependency or point it to the new release instead of this commit. The next release of MapboxNavigation will do the same.

**Comment by ShanMa1991** [comment]
@engelzero This issue should already be fixed in NavSDK in iOS right now. Would you try to test it with the `main` branch or the latest release? And please feel free to close this ticket if your issue is solved. Thanks!
