### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ytx0574** [mapbox/mapbox-navigation-ios#4552]
### Mapbox Navigation SDK version

2.16

### Steps to reproduce

I used iPhoneSE3 to test simulated navigation, with 5x turned on by default, and the cpu usage was around 40% when I selected a near destination and 80% when I selected more than 1000km

### Expected behavior

I think the range of cpu and memory usage should be constant when simulating navigation over short and long distances

### Actual behavior

Long distance, cpu memory power consumption is very high, the end distance from the cpu is slightly lower

### Is this a one-time issue or a repeatable issue?

repeatable

**Comment by Udumft** [comment]
Hi, @ytx0574, and thank you for reaching out!
CPU and memory usage for route simulation is a known issue. It increases depending on the route distance since algorithm has to generate a set of coordinates for each 'tick' (1 second), so longer routes require more data to be processed.
We do have plans to rework this mechanism, but since simulation is usually used for debugging or demo purposes this is a lower priority task.
I am going to close the ticket because this request is already tracked internally. Feel free to reopen/append or create new tickets if you need any assistance!
