### ISSUE TITLE
[Bug]: Carplay while travelling underpass , driving instruction says keep right at the fork - there is no fork in the road

### ISSUE THREAD

**Issue by santoso8118** [mapbox/mapbox-navigation-ios#4704]
### Mapbox Navigation SDK version

2.17.0

### Steps to reproduce

I am travelling from Funan to Vivo

The issue happen at this coordinate: 1.272467, 103.841842

Please check this below photo in the left side is Carplay screen, and in the right side is Android phone in navigation
Driving instruction says keep right at the fork in Carplay but there is no fork in the road. We dont know why there are different between Carplay and Android showing the route on map.
![RT-Navigation](https://github.com/user-attachments/assets/50686828-c4d8-4844-a79e-9d0c46c169d8)

I captured the route and the street road at the location as below:
![keppel road 1](https://github.com/user-attachments/assets/97112c90-61c4-474d-8ac3-a7d00c654377)
![keppel road 2](https://github.com/user-attachments/assets/bd36553b-d08a-4c1e-9911-89f14602be5a)

Please help to check the issue wrong instruction and why the route and instructions are different between iOS Carplay and Android?

### Expected behavior

Driving instruction should not says keep right at the fork as Android phone and the route is straight on Keppel Road

### Actual behavior

Driving instruction on Carplay says keep right at the fork - there is no fork in the road

### Is this a one-time issue or a repeatable issue?

one-time

**Comment by santoso8118** [comment]
Can anyone help to check this issue ?

**Comment by kried** [comment]
Hi @santoso8118

Unfortunately, we were not able to reproduce the issue.
The CarPlay shows the same instructions as iPhone and Android devices.

![1](https://github.com/user-attachments/assets/134c5521-9377-44d0-8c19-5464a79d3f1b)

Please try this scenario with the Nav SDK v2.18.4. If the issue is still actual, please, record a history file. You can use the [History-Recording](https://github.com/mapbox/mapbox-navigation-ios-examples/blob/0fc4d3774d795619c6781115c9cbc0cec0884966/Navigation-Examples/Examples/History-Recording.swift#L216) example to see how to record this file.

**Comment by santoso8118** [comment]
Thanks @kried 

We already upgraded Mapbox navigation to version 2.18.4.
We will verify it in the next road test and update to you.
