### ISSUE TITLE
[Bug]: Conflict Between WebRTC Audio and Mapbox Navigation Audio Playback

### ISSUE THREAD

**Issue by ProgrammerFaraz** [mapbox/mapbox-navigation-ios#4736]
### Mapbox Navigation SDK version

2.0.1

I'm facing an issue while integrating WebRTC audio streaming and Mapbox Navigation audio in the same iOS application. When the Mapbox Navigation SDK plays audio (e.g., turn-by-turn instructions), it interrupts and stops the audio and mic of the ongoing WebRTC audio stream that uses AVAudioSession. This behavior negatively impacts the user experience, especially in scenarios where continuous communication via WebRTC is crucial alongside navigation.

### Steps to reproduce

- Integrate WebRTC audio streaming using WebRTC's RTCAudioSession.
- Add Mapbox Navigation SDK to the project.
- Start a WebRTC audio stream.
- Trigger a navigation session that plays audio instructions (e.g., "Turn left in 100 meters").

### Expected behavior

Mapbox Navigation audio should coexist with WebRTC audio:

- Both audio streams should play simultaneously without interruption.
- Navigation audio should not interfere with WebRTC audio streams.

### Actual behavior

- Mapbox Navigation audio interrupts and stops the volume and mic of the WebRTC audio stream.
- After navigation audio finishes, WebRTC audio does not fully recover and it stops entirely.

### Is this a one-time issue or a repeatable issue?

repeatable

**Comment by kried** [comment]
Hi @ProgrammerFaraz 

You described the expected behavior of the SDK. The navigation instruction interrupts other audio sessions on device. This is the default SDK behavior.
If you want to change this, feel free to write your custom [SpeechSynthesizing](https://docs.mapbox.com/ios/navigation/api/2.19.0/Protocols/SpeechSynthesizing.html#/SpeechSynthesizing) implementation. Take a look at [the sample](https://github.com/mapbox/mapbox-navigation-ios-examples/blob/61f6afc21e67d7f3dfdabac273baa043eaa582cc/Navigation-Examples/Examples/Custom-Voice-Controller.swift#L65C30-L65C53).
