### ISSUE TITLE
Errors after I updated to Mapbox 3.6.1

### ISSUE THREAD

**Issue by xiafangmo** [mapbox/mapbox-navigation-ios#484]
I have updated to Mapbox 3.6.1 and these errors are stopping my app from compiling. Can anyone please explain what the issue is? I was using 0.4.0 and updated to 0.6.0 but the errors persist.

<img width="270" alt="screen shot 2017-08-13 at 8 01 35 pm" src="https://user-images.githubusercontent.com/6510543/29254395-bc64999c-8062-11e7-92a9-7289ae9d060e.png">

**Comment by Ahmeddben** [comment]
Just posted about this also. I am having the same issue!

**Comment by frederoni** [comment]
Thank you for your report.
This happened because of a breaking change in an underlying dependency.
If you are using Carthage, this issue was fixed in https://github.com/mapbox/mapbox-navigation-ios/pull/487
and for CocoaPods in https://github.com/mapbox/mapbox-navigation-ios/pull/480

Unfortunately, you have to use the master branch of MapboxNavigation until the next release.

CocoaPods:
```ruby
pod 'MapboxNavigation', :git => 'https://github.com/mapbox/mapbox-navigation-ios.git', :branch => 'master'
```

Carthage:
```
github "mapbox/mapbox-navigation-ios" "master"
```

**Comment by xiafangmo** [comment]
Thank you for solving the issue so promptly.

**Comment by Ahmeddben** [comment]
Thanks @frederoni !
