### ISSUE TITLE
Running the example project produces "No such module 'MapboxDirections'" on multiple files

### ISSUE THREAD

**Issue by TCOA** [mapbox/mapbox-navigation-ios#583]
Following the instructions as best as possible (seems steps are missed - or, at least could be clearer?) produces an error "No such module 'MapboxDirections'"

1. create a podfile (text) file on your computer and add the pod dependency (pod 'MapboxNavigation', '~> 0.7.0')

2. download the .[zip](https://github.com/mapbox/mapbox-navigation-ios/archive/master.zip) file and unzip to the same folder.

3. Run `pod install` and open the Xcode workspace.

4. paste your Mapbox Access Token into MGLMapboxAccessToken in Info.plist (this step is not important to generate the error)

5. click the project name in Xcode and under the General tab, complete the "Signing" section with your Team information.  Do this for ALL folders in the project - otherwise, you get an error that says you are not part of the project team.

6. Attempt to build the project and get "No such module 'MapboxDirections' on RouteStep.swift

**Comment by frederoni** [comment]
The SDK supports installation via CocoaPods or Carthage but the example project relies on Carthage.
Follow these steps https://github.com/mapbox/mapbox-navigation-ios#running-the-example-project to try out the examples.

**Comment by TCOA** [comment]
I have followed the Carthage installation and am now seeing a map.

However, no matter what point I select, in the Debug area of Xcode, I see the following:

>The operation couldn’t be completed. Coordinate is invalid: 3.40282346638529e+38,3.40282346638529e+38

I can click on "Clear Map" (when it appears) and "Simulate Location" (changes from a blue surrounded button to a 'link'), zoom in/out on the map, etc., but nothing 'significant' happens. (I presumed this might be used along with the Xcode location simulator, though no locations work - in any fashion...)

Are there additional steps/instructions?

**Comment by frederoni** [comment]
You can use Xcode’s built-in location simulation _or_ enable the "Simulate locations".
However, in your case, it seems that your origin or destination is incorrect and you're not getting a route.

Is there any location marker on the map view showing your current location when you long press for adding a destination?

**Comment by TCOA** [comment]
there was no marker showing when I had these issues.

I restarted the app and then was asked about Location (which I allowed) and then my location (Ecuador) showed up.  I thought I was asked about Location the first time, but seems maybe it as a Notifications approval (sorry, didn't really pay attention as it was an 'Allow' and this is only a test)

I was getting a message about "can't do this in the background" (had other tasks I had to do and didn't get that text...) - restarted the app and now things seem to work (now getting audio directions on simulation, can switch views, etc.)

So, it seems that restarting the app multiple times has 'cleared' this (and, the app looks great, as expected!)

**Comment by TCOA** [comment]
The example app works smoothly (after restarting a few times, which worries me in trying to use it in my apps....).

Now I am trying to integrate the new SDK into my app and running into problems.  I started several months ago with the examples given (in 0.3 I think it was) and that worked ok, but there were some bugs, so I updated (via pod install) to the latest (0.7.0) a few days ago (due to problems there, I wanted to try the example so I could know what it should be doing).

With the 0.7.0 (installed from pod install), the maps show up, but:
- I don't get any spoken words
- simulated locations do not work
- the 'show all route' and 'resume' buttons 'sort of' work, but not like they do in the example app (which works in a logical fashion).

I have tried using the example code to find the issue, but @frederoni stated "The SDK supports installation via CocoaPods or Carthage but the example project relies on Carthage."

So, two questions:

1. if I install through Carthage into my existing app, will it all work?  (do I need to then remove Mapbox from the podfile and install Mapbox through Carthage going forward?)  

2. If not (or not recommended) to install through Carthage, then what can someone that is only using pod install do for an example file to work with the new SDK?

As you can imagine, I'm really stuck right now as the app was nearly ready for release - until the upgrade, which was only done expecting a bug fix.... - and, I'm terrified of what might happen when installing through Carthage after doing the pod install!

**Comment by frederoni** [comment]
> I don't get any spoken words

The voice controller changed quite a lot since v0.3 but the default voice controller should work as before. If you want to give Polly a try, you can:
```swift
navigationViewController.voiceController = PollyVoiceController(identityPoolId: "your-pool-id")
```
However, let us know if you don't get any voice instructions at all.

> simulated locations do not work

Compared to v0.3, you now have to pass a `SimulatedLocationManager` to the `NavigationViewController`
```swift
let locationManager = SimulatedLocationManager(route: route)
let navigationViewController = NavigationViewController(for: route, directions: directions, locationManager: locationManager)
```

> if I install through Carthage into my existing app, will it all work? (do I need to then remove Mapbox from the podfile and install Mapbox through Carthage going forward?)

You would have to move off of CocoaPods completely by: `pod deintegrate`
See [Carthage](https://github.com/Carthage/Carthage) for more information about how Carthage works and how to use it in your workflow.

> If not (or not recommended) to install through Carthage, then what can someone that is only using pod install do for an example file to work with the new SDK?

Both Carthage and CocoaPods have their pro’s and con’s, we don't recommend one or the other. You run `carthage bootstrap --platform ios` in order to install all dependencies.
The example app is not included in the SDK, it's just a target that makes it more convenient to work on the SDK. It will be excluded no matter if you decide to integrate with CocoaPods or Carthage.

**Comment by TCOA** [comment]
The locationManager/navigationViewController bit did the trick!  

I got voice and simulated directions when I removed (for now) the "directions: directions" bit, which was not part of the 0.3 stuff (I'll have to look up more on that - I'm expecting it to give me the possibility to pass in the start/end lat/lng in some fashion and simulate my exact path {which will be perfect for my testing - making those GPX files then matching them up has not been fun and if I can pass in variable data to test against the rest of the app would be really great}) 

But, for now, I'm back on 'the road' (pun intended!) and this put all my app back working again (map-side anyway) - with everything falling into place (and very little change needed from the 0.3 version - yeah!).

**Comment by addzo** [comment]
I am having the same problem with the build not finding MapboxDirections - because the MapboxDirections framework is not present.
I have followed the Carthage instruction and it still is not pulled down or generated.
Any ideas where we are supposed to get the MapboxDirection.framework? 
It doesn't seem to be generated from any of the subprojects.

**Comment by addzo** [comment]
I'm still having this issue but with a new project.
I'm wondering if there is an issue with how Xcode 9 deals with frameworks/pods.
Xcode 9
Swift 4
Command Line Tools: Xcode 9.0 (9A235)
<img width="810" alt="screen shot 2017-10-04 at 7 44 43 am" src="https://user-images.githubusercontent.com/168576/31179043-0bf50382-a8d8-11e7-9f53-a506d66e9cc4.png">

1.  build a brand new project
2. pod init
3. add "pod 'MapboxNavigation', '~> 0.8.0'" to Podfile
4. pod repo update
5. pod install
install complete but got:
 Automatically assigning platform ios with version 11.0 on target TurnByTurn because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

[!] The `TurnByTurn [Debug]` target overrides the `SWIFT_VERSION` build setting defined in `Pods/Target Support Files/Pods-TurnByTurn/Pods-TurnByTurn.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `TurnByTurn [Release]` target overrides the `SWIFT_VERSION` build setting defined in `Pods/Target Support Files/Pods-TurnByTurn/Pods-TurnByTurn.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

6. In view controller I can import Mapbox but *CoreNavigation, *Navigation and *Directions are not found
7. building results in the expected "MapboxCoreNavigation" not being found compiler error.  BUT
8. I am still getting the "'subscript' was obsoleted in Swift 4 error that I thought was fixed.
<img width="277" alt="screen shot 2017-10-04 at 7 51 51 am" src="https://user-images.githubusercontent.com/168576/31179322-eafe40e8-a8d8-11e7-85af-4105d5e53c1d.png">


I realize that this is a lot in one thread.  I'm not to this project so please tell me if I need to re-organize or repost in any way.  
Thank you for your help.

**Comment by frederoni** [comment]
@addzo MapboxNavigation and its underlying dependencies currently don't build for Swift 4 but there's a PR in the works #663

**Comment by addzo** [comment]
Understood - now.  Sorry to be thick.  Appreciate the attention.  From reading #663 it looks like there is not workaround currently, correct?

**Comment by frederoni** [comment]
You can configure your project to use Swift Language Version 3.2 and it should build just fine.
![screenshot 2017-10-04 16 45 44](https://user-images.githubusercontent.com/764476/31182224-8f1e6f46-a923-11e7-96a5-597b6687622d.png)

**Comment by addzo** [comment]
Hrmm.  What am I missing:
<img width="821" alt="screen shot 2017-10-04 at 9 02 12 am" src="https://user-images.githubusercontent.com/168576/31183068-c91cf69a-a8e2-11e7-9c06-2c71504174fc.png">

**Comment by frederoni** [comment]
There's another "Swift Language Version" in your "Pods" project that's being used when compiling the "Polyline" framework.

**Comment by addzo** [comment]
OK.  That works.  Thanks
But I had to modify PulleyViewController:
dimmingViewTapRecognizer = UITapGestureRecognizer(target: self, action: #selector(PulleyViewController.dimmingViewTapRecognizerAction(gestureRecognizer:)))

Which in turn lead to:
<img width="254" alt="screen shot 2017-10-04 at 9 13 10 am" src="https://user-images.githubusercontent.com/168576/31183605-489be970-a8e4-11e7-83be-86896acceccc.png">

Not seeing a post on fixing all that.  Ideas?

**Comment by addzo** [comment]
Apologies.
I changed all of the pods to 3.2 and it builds now.  Fingers crossed for the rest.
<img width="440" alt="screen shot 2017-10-04 at 9 17 45 am" src="https://user-images.githubusercontent.com/168576/31183816-e9417e44-a8e4-11e7-86bb-1a9cdcc865bd.png">
