### ISSUE TITLE
Way name label should use current route step

### ISSUE THREAD

**Issue by ericrwolfe** [mapbox/mapbox-navigation-ios#590]
The way name label should use the information in the current route step from the direction's API's route response, rather than querying for rendered features in the map.

This will allow us to be consistent with our turn banner and remove the "ceremonial" highway names from the way name label (replacing them with the proper ref codes). If the user goes off route, we shouldn't be showing the way name label at all.

cc @bsudekum @frederoni

**Comment by bsudekum** [comment]
@1ec5 I know you had your reasons against this, mind reminding me?

I think as long as the user is snapped to the route line, it should be fine to show the current step name.

**Comment by 1ec5** [comment]
There’s no guarantee that the way name of the current step applies to the entire step, only that it applies to the first intersection on the step:

* OSRM removes any trace of name changes like “North Main Street” to “South Main Street” that would be too insignificant for a voice instruction but still significant enough for wayfinding via the map. (Knowing you’ve gone all the way to the south quadrant of the city could be useful information.)
* OSRM suppresses temporary name changes (Project-OSRM/osrm-backend#2744).
* OSRM suppresses “obvious” turns onto differently named streets.
* The Directions API recently began suppressing all `new name` instructions.

Given all these processing steps, it’s highly likely that we’d leave a misleading road name in a prominent location on screen. Ultimately, the purpose of the current road name label is different than most of the other UI provided by the navigation SDK: it’s meant to amplify information that’s already labeled on the map, rather than supplementing the map with additional information.

> This will allow us to be consistent with our turn banner and remove the "ceremonial" highway names from the way name label (replacing them with the proper ref codes).

Removing freeway names is the easy part. Replacing them with fully qualified textual route numbers is more difficult. But we do have enough information to display a graphical route shield that’s consistent with the map.

/ref mapbox/mapbox-navigation-ios#193

**Comment by ericrwolfe** [comment]
All of the above can and should be added as annotations within our directions API. cc @willwhite @miccolis @hdaymon

Using the map style to display the current way name is an elaborate hack that is buggy and prone to error. For the majority of time spent on most of my drives (read: highways), the way name either displays the wrong name or none at all.

Let's plan to move forward and switch to the current route step, as this will simplify our logic, provide consistency across platforms and languages, and cover the vast majority of way name use cases. 

The remaining issues that you've brought up can be addressed as tail work in concert with the API team.

**Comment by 1ec5** [comment]
> simplify our logic, provide consistency across platforms and languages, and cover the vast majority of way name use cases

Hiding the current road name label on freeways would take care of this, wouldn’t it? It would also avoid the pitfalls of displaying a misleading road name, which would be a regression compared to the current behavior. If you’re concerned that we’d display no route number while on a highway, consider that the map SDK currently displays too many route shields along the road: mapbox/mapbox-gl-js#5086.

**Comment by 1ec5** [comment]
> Using the map style to display the current way name is an elaborate hack that is buggy and prone to error.

It may sound that way at first glance, but querying the vector tiles is necessary anyways for things like displaying navigation-centric cross-street labels on the map and switching to the night style while in a tunnel (#559).

**Comment by 1ec5** [comment]
Thank you for these bug reports. Can you provide some coordinates to help diagnose these issues? Regardless of how we source the current road name label, some of these bugs may be relevant to other components (especially feature querying in the map SDK), so we should get a handle on them.

In the meantime, can we stop the bleeding by hiding the current road label on freeways? Even in the last example above, I think that would be an improvement over seeing “James Lick Fwy”.

**Comment by akitchen** [comment]
Closing this as the plan is to deliver a solution as a part of https://github.com/mapbox/mapbox-navigation-ios/issues/1269

**Comment by 1ec5** [comment]
Following up with other ideas for improvement in #1440.
