### ISSUE TITLE
Possible to moving annotation with animation ?

### ISSUE THREAD

**Issue by MiteshiOS** [mapbox/mapbox-navigation-ios#623]
I added one annotation on map using this class **MGLPointAnnotation**. Now i need to move this annotation as location change. Please let me know how can i do this ? I tried with by setting new coordinates to annotation but it is not working. 
Also I need to animate that annotation while it is moving so it will look like smooth movement. Any idea or suggestion please ?

**Comment by frederoni** [comment]
Closing because this issue is not related to the Navigation SDK but the [iOS Maps SDK](https://github.com/mapbox/mapbox-gl-native).

Anyway, here's some cursory guidance:
#### Option 1:
Use [`MGLAnnotationView`](https://www.mapbox.com/ios-sdk/examples/annotation-views/) to be able to use regular UIView animations.
```swift
// Location updates are delivered one time per second so 1 second duration with a linear curve will make it look smooth.
UIView.animate(withDuration: 1, delay: 0, options: [.curveLinear, .beginFromCurrentState], animations: {
    self.myAnnotationView.frame = // Calculate new frame
}, completion: nil)
```

#### Option 2:
Use [UIViewPropertyAnimator](https://developer.apple.com/documentation/uikit/uiviewpropertyanimator) to update the annotation’s location property.
