### ISSUE TITLE
Investigate dead reckoning code

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-navigation-ios#629]
https://github.com/mapbox/mapbox-navigation-ios/blob/16312c8ce2d6ce8220f6bb243ec416d70c5761eb/MapboxCoreNavigation/RouteController.swift#L538-L539

Two thoughts:

1. We've learned that using `location.speed` in the past can come back to bite us when the speed is invalid. 
1. We're also looking at a point somewhere in front of the user. If there is a turn ahead and the dead reckoning time interval is large enough, the user would be rerouted.

/cc @1ec5 @frederoni @ericrwolfe

**Comment by frederoni** [comment]
> We've learned that using location.speed in the past can come back to bite us when the speed is invalid.

Yes, I think we should keep a buffer and use the average speed from the 5 most recent locations after filtering out unqualified locations.

> We're also looking at a point somewhere in front of the user. If there is a turn ahead and the dead reckoning time interval is large enough, the user would be rerouted.

In the continuous dead reckoning (that triggers in a tunnel)
https://github.com/mapbox/mapbox-navigation-ios/blob/16312c8ce2d6ce8220f6bb243ec416d70c5761eb/MapboxCoreNavigation/RouteController.swift#L408
we use `coordinate(at:fromStartOf:)` so going off route shouldn't be an issue there. The problem is that we stay on route even if the user makes a wrong turn until we get a real location update.

I think it would be better to assume that the user continues on the right path instead of following the previous course.

**Comment by bsudekum** [comment]
A few more heuristics we came up with last week:

* If the user is traveling at (expected) speed
* (and?) there is no congestion in the tunnel
* (and?) the tunnel is relatively short

Animate the puck through the tunnel.

**Comment by 1ec5** [comment]
> We're also looking at a point somewhere in front of the user. If there is a turn ahead and the dead reckoning time interval is large enough, the user would be rerouted.

Given ongoing issues that are suspected to stem from this issue, I think we should remove the dead reckoning feature until we can ensure that the dead-reckoned location still lies along the route. We had to do something similar for the puck’s visual-only dead reckoning in mapbox/mapbox-navigation-ios#1710.

**Comment by 1ec5** [comment]
The dead reckoning code does already attempt to snap to the existing route geometry:

https://github.com/mapbox/mapbox-navigation-ios/blob/c55c13beb15d611e4a23eb826a9a966406afd8d3/MapboxCoreNavigation/CLLocation.swift#L135-L136

The reliance of the informational-only `speed` reading is still an issue, as it can cause the camera’s projection along the route to stutter. But this code should already guard against unnecessary reroutes due to dead reckoning.
