### ISSUE TITLE
Adding custom image (shield or badge) to street name

### ISSUE THREAD

**Issue by Sealos** [mapbox/mapbox-navigation-ios#637]
On the current NavigationViewController, the European [E4](https://en.wikipedia.org/wiki/European_route_E4) route is currently displayed as E 4.26.

The badge in question is:
![e4](https://user-images.githubusercontent.com/4553825/30693807-7806240e-9ed1-11e7-8076-8531e00cba13.png)

![img_0007](https://user-images.githubusercontent.com/4553825/30693561-6da4886c-9ed0-11e7-89f0-8ca823dace9d.PNG)

Two possible approaches
1. Change the text before its displayed
2. Provide a delegate function to return an optional image for a given street

**Comment by frederoni** [comment]
Previous discussions about [expanding shield coverage beyond the US (#334)](https://github.com/mapbox/mapbox-navigation-ios/issues/334) and [inlining shields (#365)](https://github.com/mapbox/mapbox-navigation-ios/issues/365)

**Comment by Sealos** [comment]
@frederoni Thanks!, in the meantime, is it possible to change the text to remove that the ".26"?

**Comment by 1ec5** [comment]
The turn banner is saying to continue onto [this way in OpenStreetMap](http://www.openstreetmap.org/way/76169023), which is tagged `ref=E 4.26`. If I understand correctly, this is how link roads are numbered in some countries. Is that tag inconsistent with the signage in this area?

**Comment by Sealos** [comment]
The .26 is not shown, only the E4 (spacing changes, some roads add space, others don't) is shown. For example:
![image](https://user-images.githubusercontent.com/4553825/30735922-01c7c044-9f81-11e7-8be9-cfb17ae01cd9.png)
![image](https://user-images.githubusercontent.com/4553825/30735863-ccc722b8-9f80-11e7-8bf0-e144956f2593.png)

In some cases, you can also see an "N" or "S" depending on the direction of the road.
![image](https://user-images.githubusercontent.com/4553825/30735951-218536e6-9f81-11e7-9384-e415427d1457.png)
![image](https://user-images.githubusercontent.com/4553825/30735938-12e5295c-9f81-11e7-9334-1fc3a46290f0.png)

**Comment by frederoni** [comment]
Link numbers on link roads are never shown or used externally but seem to be used frequently at [Trafikverket](https://www.trafikverket.se/contentassets/bc412e89c0e1492392dbf315540274fe/filer/skyddsklassade_vagar_stockholm_160623.pdf) which makes me hesitative whether this issue is a data issue or client issue. Either way, we should expose a way to modify the instruction. I'd suggest a [VisualInstructionFormatter](https://github.com/mapbox/mapbox-navigation-ios/blob/master/MapboxCoreNavigation/VisualInstructionFormatter.swift) property on `NavigationViewController` and the formatter should be refactored to use NSAttributedString and support for asynchronous as well as synchronous updates to fully support inlining images.

**Comment by davols** [comment]
Been told they are officially/technically the name of the link road at nvdb/trafikverket. So wouldn't that make it a client issue? The link number is never used on signage or "real life". 

Or perhaps an issue towards osrm-text-instructions or osrm-backend for rewriting those tags? Since the link number exists on the web and android as well.

**Comment by 1ec5** [comment]
> The link number is never used on signage or "real life".

The prevailing practice in OpenStreetMap is to reserve the `ref` tag for signposted route numbers. Numbers that aren’t signposted prominently enough for wayfinding, such as government inventory numbers, should go in [`official_ref`](https://wiki.openstreetmap.org/wiki/Key:official_ref), [`unsigned_ref`](https://wiki.openstreetmap.org/wiki/Key%3Aunsigned_ref), or ad-hoc tags like [`ref:penndot`](https://www.openstreetmap.org/user/oini/diary/38444) (using the name of the roads agency).

It’d wouldn’t be practical to special-case inventory numbers in this library, especially since they aren’t easily identifiable without more context. For example, some U.S. counties and townships prominently post [decimal route numbers](http://www.aaroads.com/shields/show.php?image=OH19900221), while the U.S. state of Pennsylvania has a system of virtually unsignposted “[quadrant routes](https://lists.openstreetmap.org/pipermail/talk-us/2015-January/014173.html)” consisting of four-digit numbers. Yet OSRM doesn’t even provide this library with enough information to know whether “E” means a European route, [an express road in Colorado](http://www.openstreetmap.org/way/37888278), or something else. #334 would give the SDK more context, but even then, list of patterns of unsignposted routes would be difficult to maintain even in OSRM-backend.

At the moment, there are [1,624 ways](http://overpass-turbo.eu/s/rU1) tagged with what looks like a link E road number. Ultimately, I think retagging them would be appropriate if these numbers are always unsignposted. The first step would be contacting the [talk-se](https://lists.openstreetmap.org/listinfo/talk-se) mailing list, but I don’t know a lick of Swedish. 😅

**Comment by 1ec5** [comment]
> In some cases, you can also see an "N" or "S" depending on the direction of the road.

This is good to know. Both the Mapbox Directions API and Navigation SDK currently rely on a tagging scheme that’s [prevalent in the U.S.](https://wiki.openstreetmap.org/wiki/Highway_Directions_In_The_United_States) but could conceivably be used in Europe as well: link roads leading to motorways are tagged e.g. `destination=SR 123 North`. Unfortunately it’s an unstructured format, as opposed to [`destination_sign` relations](https://wiki.openstreetmap.org/wiki/Relation:destination_sign), but it’s the best we can do until Project-OSRM/osrm-backend#482 and related functionality is fully implemented in the router.
