### ISSUE TITLE
Snap to road on two way streets

### ISSUE THREAD

**Issue by Sealos** [mapbox/mapbox-navigation-ios#639]
Snapping to the road is not taking into consideration the user heading and street heading.

When multiple segments are present on the same street
![img_0003](https://user-images.githubusercontent.com/4553825/30697055-f4ffa118-9edd-11e7-9f31-6bc7ed746666.PNG)

After finishing that multi-segment
![img_0004](https://user-images.githubusercontent.com/4553825/30697060-f6f0ae4a-9edd-11e7-96f4-1a20e71fdad7.PNG)

**Comment by bsudekum** [comment]
I think the issue here is that we use `routeProgress.currentLegProgress.nearbyCoordinates` which includes the previous step, current step and upcoming step coordinates to calculate where to snap. I think it might safe to only look at the current step coordinates if the upcoming step is a maneuver type == .uturn.
