### ISSUE TITLE
Add `RouteControllerDidIncrementRouteStepIndex`

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-navigation-ios#641]
There are a lot of hacks we do to figure out if the step has been incremented. Instead of relying on alert levels to know if the step index has been incremented, let's add a Notification.

/cc @ericrwolfe @1ec5 @frederoni

**Comment by 1ec5** [comment]
For context, originally, RouteProgress was implemented as a struct so that `RouteControllerProgressDidChange` could’ve easily come with an `oldProgress` and `newProgress` and an observer could compare the step indices on the old and new progress structs. But since we converted it into a class for Objective-C compatibility, having lots of progress objects floating around can be confusing, so we pass around the route progress object almost like a singleton (albeit still scoped to a single RouteController instance).

A notification upon starting a new step sounds fine, but we should also implement a companion delegate method.

**Comment by bsudekum** [comment]
Haven't needed this thus far, so I think we're good to close this.
