### ISSUE TITLE
Transition from awaiting to navigation state

### ISSUE THREAD

**Issue by Jauzee** [mapbox/mapbox-navigation-ios#655]
Is it possible to use the same viewController for navigation? (ex.: the Swift example's root `ViewController`)

- User uses long press gesture to pick a destination
- ViewController draws a route
- User taps _Navigate_ button
- MapView camera changes and navigation starts

I'm trying to achieve this, but when I create `RouteController` instance, uncaught exception occurs.

Will able to provide sample project if it'll help.

**Comment by frederoni** [comment]
Many features in `NavigationViewController` and `RouteController` relies on a `route` and coordinates which is forcefully unwrapped which probably triggers the exceptions you refer to.
However, you can achieve the desired effect by passing a pending camera and use a [custom transition animation](https://developer.apple.com/library/content/featuredarticles/ViewControllerPGforiPhoneOS/CustomizingtheTransitionAnimations.html) so that it looks like the view controller remains the same.

**Comment by Jauzee** [comment]
@frederoni but it seems like I'm just delaying configuration of route & routeController. What's going wrong if I move the configuration code little bit far from viewDidLoad and call it by some action.

The question is: can I ever achieve what I'm described in the question or it's unable to do with current implementation. Thank you!

**Comment by frederoni** [comment]
`RouteController` and `NavigationViewController` along with the embedded view controllers such as `RouteTableViewController` and `RouteManeuverViewController` can't handle a state where `route` is unset.

`NavigationViewController` defines `route` as an implicitly unwrapped optional `var route: Route!` which means it has to be defined in `viewDidLoad` or before.

We have been discussing if we should make the route optional in order to support cases like this but it's not currently on the roadmap.

**Comment by Jauzee** [comment]
I'm not using the `NavigationController`. Instead I created a custom one as in example. I'll try to look  in `RouteController` and understand what is the problem.

**Comment by frederoni** [comment]
Oh ok, you have full control of the map view and the route controller if you follow the custom example so that should be feasible.
What kind of exception do you get?
When you request a route using MapboxDirection, do you use the `NavigationRouteOptions` or the regular `RouteOptions`? In case of `RouteOptions`, do you set `includesSteps = true`?

Also, a sample project would be nice if this doesn't solve your issue.

**Comment by Jauzee** [comment]
@frederoni used both options. I will create a sample project later today.

**Comment by Jauzee** [comment]
Sometimes you need a clean look to decide what's going wrong. I was pretty sure that I'm configured everything as needed, but definitely something was wrong in my code.

Short version: everything is working as expected in a new project.

@frederoni thank you for the support!
