### ISSUE TITLE
Expose more MGLMapViewDelegate methods

### ISSUE THREAD

**Issue by frederoni** [mapbox/mapbox-navigation-ios#685]
We only delegate `mapView(_:viewFor:)` and `mapView(_:imageFor:)` to the `NavigationViewControllerDelegate` currently. Let's add a few more requested (#666) delegate methods.

- [ ] `mapView(_:regionWillChangeAnimated:)`
- [ ] `mapView(_:regionDidChangeAnimated:)`
* [ ] `mapView(_:didFinishLoading:)` (both methods)
* [ ] `mapView(_:viewForAnnotation:)`
* [ ] `mapView(_:didAddAnnotationViews:)`
* [ ] `mapView(_:annotationCanShowCallout:)`
* [ ] `mapView(_:tapOnCalloutForAnnotation:)`

@bsudekum @1ec5

**Comment by 1ec5** [comment]
NavigationMapView currently seems to implement only `mapView(_:imageFor:)` and `mapView(_:viewFor:)`, and it does so by turning around and ultimately asking the NavigationViewControllerDelegate’s implementation of those methods. So does NavigationMapViewController even need to be NavigationMapView’s delegate? If not, we can remove all these pass-throughs and let the developer set the map view’s delegate to their own view controller.

**Comment by frederoni** [comment]
@1ec5 It would be great if we could expose all of MGLMapViewDelegate but the RouteMapViewController needs `mapView:didFinishLoadingStyle:` and `mapView:regionDidChangeAnimated:`. 🤔

**Comment by 1ec5** [comment]
We could imitate `-mapView:didFinishLoadingStyle:` by key-value observing the `style` key path. We could move RouteMapViewController off `-mapView:regionDidChangeAnimated:` using `didSet` handlers on various properties like `tracksUserCourse`.

**Comment by akitchen** [comment]
see also https://github.com/mapbox/mapbox-navigation-ios/issues/1526

**Comment by lemwerks** [comment]
@akitchen This is something [Roadtrippers](https://github.com/mapbox/support/issues/741) brought up. Their goal is to add annotations you can tap on to open for more details. They can add them to the map, but annotations don’t seem to open. 

@1ec5 made some suggestions that weren't capable at this time. Flagging here to a: give you an idea of the need of this from a long time Enterprise Customer and they want to use the Nav SDK and b. Keep tabs on this development. 

Here's also some additional [context from Slack](https://mapbox.slack.com/archives/CAPRWBZ1B/p1529522598000479) about a proposed solution to assign a class (usually a view controller) as the map view’s delegate, then implement `-mapView:annotationCanShowCallout:` to return `YES`. But it didn't pan out because our documentation said not to.

**Comment by 1ec5** [comment]
Edited the original post with some more MGLMapViewDelegates that developers have told us they’d like to see exposed through NavigationMapViewDelegate and/or NavigationViewControllerDelegate.

**Comment by akitchen** [comment]
Is there a reason why we don't offer message passing of the entire `MGLMapViewDelegate` family of delegate methods? Are there any which would negatively impact the navigation experience or be otherwise disruptive?

**Comment by 1ec5** [comment]
Passing the entire public interface of MGLMapViewDelegate is the most straightforward solution. The downsides would be that NavigationViewControllerDelegate becomes even more bloated and that we still rely on manually plumbing delegate methods through both RouteMapViewController and NavigationViewController as they’re added to the map SDK. (We’ll need to keep a close eye on the map SDK for any such additions.)

We could expose RouteMapViewController publicly as the go-to class for customizing the map view that’s embedded in NavigationViewController, removing one level of indirection. But there will still be the same issue of NavigationViewController hogging access to the RouteMapViewController’s delegate methods.
