### ISSUE TITLE
Animate zoom level depending on location on step and step type

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-navigation-ios#766]
Let's resurrect https://github.com/mapbox/mapbox-navigation-ios/pull/656 and add some simple rules for animating the camera altitude based on road class, distance to maneuver. Rules:

* If the road class is of type `.motorway` and
* The distance to the maneuver is greater than X meters

Then set the altitude to 2000m

If the altitude is 2000m:

* And the distance remaining is less than X meters
* And the upcoming step is not a motorway

Reset the altitude to the default.

If the the altitude is 2000m:

* and the upcoming step is a motorway
* and is also long

Keep the altitude at 2000m

/cc @JThramer @ericrwolfe

**Comment by 1ec5** [comment]
There are a lot of conditionals in this logic. That means a lot of edge cases, so look out for possible yo-yoing around each of these thresholds. If that turns out to be a rabbit hole, consider coming up with formulas that match all these thresholds by interpolating values.

**Comment by ericrwolfe** [comment]
The idea here would be to have the voice announcements trigger a camera change, so that when a driver hears an announcement and looks at the screen, the camera will have updated accordingly.

Zooming out for long steps would allow us to heavily throttle the render calls for significant battery changes (when zoomed out, the location puck will move 1px less frequently), and also give the driver more context about the long stretch of road ahead.

**Comment by 1ec5** [comment]
> give the driver more context about the long stretch of road ahead

Very much in favor of this. There’s a lot more we can do a long these lines as tail work, but the logic above should do for now, as long as we only reevaluate it on each spoken instruction.

**Comment by 1ec5** [comment]
Implemented in #769.
