### ISSUE TITLE
After Upgrade from 0.8 to 0.9 CALayer position contains NaN: [nan nan]

### ISSUE THREAD

**Issue by K-Leon** [mapbox/mapbox-navigation-ios#776]
Hello :)
First of congrats for this awesome Project!! It's really great what you're doing here!

I just stumbled about an issue i can't really explain:

After Upgrading to 0.9 i'm seeing this error constantly: 

`CALayer position contains NaN: [nan nan]`

0.8 is working absolutely fine. 

This is more or less what i'm doing:

```
[selfaddChildViewController:navigationController];
navigationController.view.frame = self.bounds;
[self addSubview:navigationController.view];
[navigationController didMoveToParentViewController:self];
```

Is there anything new in 0.9 View Creation which could prevent this usecase?

Best Regards,
Leon

**Comment by frederoni** [comment]
Thanks! 

My first guess would be that it has something to do with the day and night style switch but that was introduced in 0.7. To rule it out, try using just one style when you initialize the `NavigationViewController`.

Another long shot would be to try `[navigationController willMoveToParentViewController:self]` prior to your snippet above, even though it shouldn't be necessary.

Does this happen both using the simulator and device?

Do you get the same error if you present the NavigationViewController modally instead of embedding in your own view controller?

**Comment by bsudekum** [comment]
@K-Leon is this still an issue?

**Comment by frederoni** [comment]
Closing b/c of inactivity and we have not seen this issue since.
