### ISSUE TITLE
When pressing recenter, distance resets value until next location tick

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-navigation-ios#795]
To reproduce:

1. pan map off user
1. hit recenter
1. notice change in the distance label

It might be the default value found in the storyboard. This value should remain constant.

/cc @frederoni

**Comment by frederoni** [comment]
I think this is by design as of https://github.com/mapbox/mapbox-navigation-ios/pull/769/commits/6388c1d8e44b7af40428398f9692da3c30659634? /cc @JThramer

**Comment by JThramer** [comment]
Correct, this is by design. `adjustCameraAltitude(for:)` is called when you hit the Resume Button. That function sets the camera altitude if one of two conditions are matched:

- It sets the camera to `zoomedOutMotorwayAltitude` (2000m) if you are on a motorway (and not about to exit.)
- It sets the camera to `defaultAltitude` (1000m) if you are on the last instruction of your maneuver.

Otherwise the function does nothing.

**Comment by JThramer** [comment]
I think the issue is coming from https://github.com/mapbox/mapbox-navigation-ios/blob/master/MapboxNavigation/RouteMapViewController.swift#L606, but I'm still digging into it.

**Comment by JThramer** [comment]
Issue fixed.
