### ISSUE TITLE
SDWebImage dependency issue 

### ISSUE THREAD

**Issue by waqas-tahir** [mapbox/mapbox-navigation-ios#799]
I am using MWPhotoBrowser which require SDWebImage as static library.
Adding MapboxNavigation using cocospod is conflicting 
- `SDWebImage (!= 3.7.2, ~> 3.7)` required by `MWPhotoBrowser (2.1.2)`
- `SDWebImage (~> 4.0)` required by `MapboxNavigation (0.5.0)`

I solved this problem by adding MapboxNavigation framework to project builded by the carthage and all went well till xcode 8 

Moving my project to xcode 9 has started causing issue giving error msg of :
- Typedef redefinition with different types ('void (^)()' vs 'void (^)(void)')  

Please provide me a way by which I can add mapbox-navigation to project. Thanks

**Comment by bsudekum** [comment]
@waqas-tahir so looking at 

- `SDWebImage (!= 3.7.2, ~> 3.7)` required by `MWPhotoBrowser (2.1.2)`
- `SDWebImage (~> 4.0)` required by `MapboxNavigation (0.5.0)`

It appears to be that `MWPhotoBrowser` is pretty far behind. If it were updated to something that is more current, would this solve your problem? Perhaps the right course of action is to update `MWPhotoBrowser` instead of Mapbox Navigation.

**Comment by bsudekum** [comment]
Going to close this out. I'd say try and update `MWPhotoBrowser` to v4.x
