### ISSUE TITLE
"Merge" icon still reversed

### ISSUE THREAD

**Issue by ericrwolfe** [mapbox/mapbox-navigation-ios#802]
It looks like the merge icon is still reversed. This was a "merge left" maneuver but the icon shows merge right:

![img_0224](https://user-images.githubusercontent.com/664805/32465895-17d76fe6-c313-11e7-8db8-4300ec2990ff.PNG)

cc @frederoni

**Comment by frederoni** [comment]
This particular merge is a straight merge:
```
bearing_after:161
bearing_before:153
modifier:"straight"
```

so we end up not flipping the icon because it's not left, slight left, or sharp left.

Merge, take off ramp, and reach fork should use a different logic where the slightest difference in bearing should determine the direction.

**Comment by ericrwolfe** [comment]
For merge straight (or any straight modifiers) we should probably just show a straight arrow.

**Comment by 1ec5** [comment]
When we say “merge left”, what that means is that there’s traffic coming in over the user’s left shoulder, not that the user needs to turn left at the maneuver. Since we aren’t having users literally fall off ramps into traffic below, there should be no such thing as a “straight merge”.

/ref Project-OSRM/osrm-text-instructions#183

**Comment by 1ec5** [comment]
Fixed upstream, server-side, in Project-OSRM/osrm-backend#4670.
