### ISSUE TITLE
Custom controls

### ISSUE THREAD

**Issue by frederoni** [mapbox/mapbox-navigation-ios#830]
We've had a few requests about adding custom controls to the navigation view controller.
I suggest we expose a grid that's properly aligned with the map view. A public UIStackView in each corner that's customizable by the user. Similar to the current set of controls (overview, mute & feedback), pinned to the top|right, but for all edges and exposed publicly.

/cc @bsudekum @1ec5 @JThramer

**Comment by 1ec5** [comment]
Would the grid be limited to RouteMapViewController’s portion of the window, or would other parts of the window be in scope for this feature?

**Comment by frederoni** [comment]
RouteMapViewController is full size as of #785 (perhaps we should consider merging RouteMapVC and NavigationVC) but I'm thinking the size of the map view to begin with. Adding components to the instructions banner or the bottom banner would be trickier.

**Comment by 1ec5** [comment]
> perhaps we should consider merging RouteMapVC and NavigationVC

In the future, that might limit our ability to temporarily replace the map view controller with a different view controller for specialized UI. But I agree that flattening the view controller hierarchy would probably simplify a few things like the delegates.

**Comment by JThramer** [comment]
Hey guys,

So bobby asked me to take a good look at this, and after giving it some serious thought over the past few days, here's what I've come up with.

While thinking through this problem, it occurred to me that there are actually two main use-cases to consider:

- Advanced: It seems that for most of our bigger clients, it's highly unlikely that they will use our vanilla UI as-written. Ideally they would use components of our UI framework in an ad-hoc, or "Lego" fashion, engineering a solution that fits their needs, while still taking advantage of as much "code reuse" as they can. For example, they may use our `InstructionBannerView`, but on a ViewController of their own making. Because of this, we should commit to providing _modular, loosely coupled_ UI components with _clear, expressible interfaces_.
- Simple: There are other implementers out there who may not have such an advanced use-case, perhaps they just want to add "a little something extra" to the vanilla UI. In this case, it may be tedious to roll their own `UIViewController` or subclass `RouteMapViewController` just to add "one extra thing", so it _does_ make sense to provide some customizable functionality. However, we want to keep scope in mind here, as the value here would be to provide an easy interface for adding trivial customization, _not_ to create a "[Bootstrap](https://getbootstrap.com) for `RouteMapViewController`". 

The advanced case is out-of-scope of this issue, but for the simple case, I propose the following: Have a single `UIStackView` at each "corner" of the map in the `RouteMapViewController`. For any existing UI elements, they would go at the beginning of the stack view. For example, the `Resume` button would be the first element of the bottom-left stack view. the on-map buttons (Overview, mute, feedback) would be at indices 0-2 of the top-right stack view. Orientation of stack-views will be settable to Horizontal or Vertical. (except perhaps in the top-right case, which would be enforced with an `assert()`, but I'm still going back-and-forth on this.) The likely method signature to add these custom views would look something like this: 

```swift
//puts a "Profile Chiclet" above the "Resume" button
addCustomViews([profileChicletView], position: .bottomLeft, orientation: .vertical)
```

NB: One thing we should be mindful of going forward with this ask is that all future UI work "on the map" in the `RouteMapViewController` is going to need to be made with these stack-views in mind. Depending on the capabilities of these "custom accessory" stack views, this may complicate layout logic.

Other thoughts: 
-  We could expose all constraints to the implementers, which might add quite a bit more capability for customization, but I'm on-the-fence with this. Arguably, we shouldn't expose properties of our components that could allow implementers to "break" our baked-in layout.
- We should make sure our reference implementations are responsive. They should be able to adapt to being embedded in a container, whether that's a `UINavigationController`, `UITabBarController`, etc etc.

/cc @bsudekum @1ec5 @frederoni @ericrwolfe

**Comment by bsudekum** [comment]
@JThramer good write up. What are you next steps here?

**Comment by JThramer** [comment]
@bsudekum Ah yes, I forgot to actually put in action-items. I will be creating Said stack views in the RMVC. Ideally it will be trivial to get all four stack views in, but I don't want to commit to all four corners in one pass quite yet, just in case there's a significant difference in difficulty between implementing, say, the `.topLeft` and `.topRight` stack views.

**Comment by ericrwolfe** [comment]
@JThramer the idea you proposed under Advanced sounds like a great long term solution. You mention it being out of scope for this issue, is there some way we could break the problem down so that it's a bit easier to bite off?

Could we make it so that developers can selectively hide some of the core UI elements, such as the top banner, the bottom summary view, each of the floating buttons, and the current way name label, so that they could then add their own custom implementations of whatever they've hidden as an overlay (with the NavigationViewController being contained within a separate subview)?

I'm a little worried about developers inserting custom views into our existing view, as our view hierarchy could change in the future. Could we expose some of the core views (top banner, etc) as properties on the view controller, so that developers can access the current frames to determine where to place their own content?

**Comment by 1ec5** [comment]
> Could we expose some of the core views (top banner, etc) as properties on the view controller, so that developers can access the current frames to determine where to place their own content?

This sounds even more risky than exposing constraints publicly, given that the SDK is laid out using Auto Layout rather than manual layout.

**Comment by ericrwolfe** [comment]
> I'm a little worried about developers inserting custom views into our existing view, as our view hierarchy could change in the future.

Can we think about ways that would enable + encourage developers to add their own views as siblings to whatever contains the navigation SDK views, rather than as subviews of the NavigationViewController's view itself?

**Comment by JThramer** [comment]
Second half of this ticket, recorded for posterity: 

- [ ] Add an example where you're embedding a custom element above the bottom bar.

**Comment by JThramer** [comment]
@frederoni quick update:

Well, adding the "chiclet" custom element didn't go very well. It turns out that `NavigationViewController` / `RouteMapViewController` doesn't lend itself to being subclassed well, at all. The basic reason here is that the `RouteMapViewController` is instantiated directly from Storyboard, which doesn't define a UI _template_ for a class, merely a repeatable serialized instance. When you subclass a ViewController class that's been laid-out in storyboard, you inherit that class's behavior, but you do _not_ inherit it's UI layout configuration. Bummer.

...And if you can't effectively subclass, then there's no benefit to using `additionalSafeAreaInsets`.

Incidentally, I'm _really_ starting to lose my faith in storyboarding for SDK work.  

 because of this, I'm thinking that your "corner stack views" solution is a good way to go for this use-case, but that got de-prioritized because... 

## NVC-in-things
![image](https://user-images.githubusercontent.com/887225/34546179-77bd82b4-f0af-11e7-9231-43eef27f8771.png)

After talking with @bsudekum it sounds like we now want to try for this kind of demo. The general gist here is "arbitrary view on top, arbitrary view on bottom (visualized as a `UIToolbar` and `UITabBar`, respectively, but could be anything), and map containerized in the middle", which is a much more straightforward task.

Interestingly, #968 is all about decoupling the NavigationViewController from it's initializer, which would allow it to be embedded in a container in storyboarding, but it's not blocking us because there's no reason that we can't set up a VC that includes a container programatically.

/cc @ericrwolfe

**Comment by lmgreer** [comment]
@JThramer , thank you for your looking into this. We are also interested in the solution. To be clear - is there a workaround right now? Can I stuff the vanilla UI in a container like you have shown? Or are you all in the process of implementing this functionality?
