### ISSUE TITLE
app crash, plz help!

### ISSUE THREAD

**Issue by zijiazhai** [mapbox/mapbox-navigation-ios#843]
hi, all
I am using 0.8.3
Some of my users reported crash to me, which I could not reproduce. Also, I think all of them are using ios11. And I guess the crash is in the RouteManeuverViewController. My crash log shows this,
![snip20171113_4](https://user-images.githubusercontent.com/10751092/32755202-c81b99b4-c899-11e7-8e73-e9d07483266d.png)

My second problem is, for some reason, every voice direction command repeat twice.

I am still use let options = RouteOptions(coordinates: [mapView.userLocation!.coordinate, destination.coordinate]) to request route.
 Right now, I am not sure if updating to 0.10 will solve those two problems or not?

**Comment by bsudekum** [comment]
Hi @zijiazhai,

We're going to need more information than the log you posted. As far as your second error, we highly recommend you use `NavigationRouteOptions` instead of `RouteOptions`, it is more highly tuned for navigation.

We have fixed many bugs in v0.10.0, so I'd give that a go. If you can post back a more detailed crash log, we can dig deeper into it.
