### ISSUE TITLE
RouteController drops batched location updates

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#949]
`CLLocationManagerDelegate.locationManager(_:didUpdateLocations:)` accepts an array of locations in chronological order, but we drop all but the latest in any given location update:

https://github.com/mapbox/mapbox-navigation-ios/blob/447dbf11162aec7d690d8e7d91584d6c37d17ff6/MapboxCoreNavigation/RouteController.swift#L508-L512

Sometimes location updates occur in a burst. If the user is traveling along a straight path, the older locations don’t matter. But if they’re traveling along a curve or turning at an intersection, the dropped locations could significantly affect camera movement.

/ref #939 mapbox/mapbox-gl-native#3610
/cc @mapbox/navigation-ios

**Comment by ericrwolfe** [comment]
Is this a real issue? Are there concrete examples of issues with camera movements caused by missed location bursts?

From past experience, bursts of locations in `didUpdateLocations` generally only occur when 1) first starting a location manager and `didUpdateLocations` immediately returns a set of cached/stale locations and 2) when using [`allowDeferredLocationUpdates(untilTraveled:timeout:)`](https://developer.apple.com/documentation/corelocation/cllocationmanager/1620547-allowdeferredlocationupdates).

**Comment by 1ec5** [comment]
You’re right, I can’t say that this is a real issue in practice (emphasis on _could_ above). However, we’re starting to talk about inserting maneuver locations and other control points between actual location updates in order to stabilize the camera and puck, so it seems natural that we’d use these extra locations – if any – to better model the road.

**Comment by bsudekum** [comment]
Noting we now filter out unqualified locations, however we still look at the last item in this array of qualified locations.

**Comment by 1ec5** [comment]
Since the migration to MapboxNavigationNative, RouteController sends all locations to the navigator.
