### ISSUE TITLE
Profile and evaluate SDK memory usage

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-navigation-ios#963]
I saw a few cases over the past 2 weeks where I'd:

* Start navigation
* Open a few new apps
* Resume navigation app

The app would no longer be in navigation mode. Looking at our OOM (Out Of Memory) logs, we do have quite a few of these crashes. Perhaps there are things we can unload when entering the background to alleviate memory consumption.

/cc @mapbox/navigation-ios

**Comment by 1ec5** [comment]
State restoration (#100) would mitigate this issue by automatically returning the user to the screen they were on when relaunching the application.

> Perhaps there are things we can unload when entering the background to alleviate memory consumption.

`UIApplicationDidReceiveMemoryWarningNotification` is posted before the application is force-quit. It’s our last opportunity to unload unneeded resources. The map SDK already reacts to this notification by flushing caches.

**Comment by bsudekum** [comment]
Per conversation with @ericrwolfe and @boundsj, this could be the desired of iOS. If you open many apps, older apps will be terminated by iOS.  One item @boundsj brought up, is that the likeliness of iOS terminating the app decreases if location always on permissions are enabled. In a few tests I did, this seemed true. 

Bottomline, we're less likely to get killed off we can reduce our memory footprint, especially when entering the background.

Are there any other in memory caches we can empty when entering the background other than polly voice mp3s?

**Comment by bsudekum** [comment]
@1ec5 are you sure we actually clear the cache when a memory warning is emitted? https://github.com/mapbox/mapbox-gl-native/blob/master/platform/ios/src/MGLMapView.mm#L705-L710

**Comment by 1ec5** [comment]
Yes, that’s what `mbgl::RendererFrontend::onLowMemory()` does (in core).

**Comment by bsudekum** [comment]
@mapbox/navigation-ios I think we should take a look into how we can increase the percent of OOM free sessions. Right now, it's very easy for the OS to completely kill the app just by opening 2 apps and putting navigation into the background.

**Comment by 1ec5** [comment]
Maybe we could look into making Route and related classes mutable. In a pinch, we could remove completed steps from memory, along with all the associated information like congestion attributes, intersections, and the step properties that are duplicated on each banner object.

**Comment by 1ec5** [comment]
We could brainstorm all day about things that’ll make the SDK lighterweight, but there’s no substitute for profiling to identify hotspots.

**Comment by ChrisLoer** [comment]
Pulling #11197 should help a good bit with this, but since we still hold onto currently rendered tiles for each map view, holding onto multiple map views will keep you from slimming down as much as you'd like. There are still further things we could do:

- Copy GL buffers into memory before going into background so that we can release them if necessary in response to a low memory warning
- Clear out textures on going into the background (maybe more of an issue with satellite maps -- didn't show up as very significant for me when I was playing with the streets style).
- Share more memory between map views (https://github.com/mapbox/mapbox-gl-native/issues/9203)

Please feel free to push us to work on any of these! I think the background memory use fell through the cracks a little (at least on the gl-core side) because responsibility was spread between Nav/iOS/gl-core...

/cc @kkaefer @friedbunny
